# generated by datamodel-codegen:
#   filename:  core_v1_rateplan.json
#   timestamp: 2026-05-12T12:25:38+00:00

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class VatType(StrEnum):
    null = "Null"
    very_reduced = "VeryReduced"
    reduced = "Reduced"
    normal = "Normal"
    without = "Without"
    special = "Special"
    special1 = "Special1"
    special2 = "Special2"
    reduced_covid19 = "ReducedCovid19"
    normal_covid19 = "NormalCovid19"
    mixed = "Mixed"


class ServiceType(StrEnum):
    other = "Other"
    accommodation = "Accommodation"
    food_and_beverages = "FoodAndBeverages"


class AccountingConfigModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    vat_type: VatType = Field(..., alias="vatType", description="The VAT type")
    service_type: ServiceType = Field(
        ..., alias="serviceType", description="The service type"
    )
    sub_account_id: str | None = Field(
        None, alias="subAccountId", description="The sub-accounts id"
    )
    valid_from: date = Field(
        ...,
        alias="validFrom",
        description="Which date this configuration is valid from",
        examples=["2020-10-10"],
    )


class AddressModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    address_line1: str = Field(..., alias="addressLine1", min_length=1)
    address_line2: str | None = Field(None, alias="addressLine2")
    postal_code: str = Field(..., alias="postalCode", min_length=1)
    city: str = Field(..., min_length=1)
    region_code: str | None = Field(None, alias="regionCode")
    country_code: str = Field(..., alias="countryCode")


class AgeCategoryCreatedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The age category id")


class AgeCategoryItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The age category id")
    code: str = Field(..., description="The code for the age category")
    property_id: str = Field(
        ...,
        alias="propertyId",
        description="The id of the property for which the age category will be created",
    )
    name: str = Field(..., description="The name for the age category", min_length=1)
    min_age: int = Field(
        ...,
        alias="minAge",
        description="The minimum age for the age category. The specified value is included in the age range",
    )
    max_age: int = Field(
        ...,
        alias="maxAge",
        description="The maximum age for the age category. The specified value is included in the age range",
    )


class AgeCategoryListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    age_categories: list[AgeCategoryItemModel] = Field(
        ..., alias="ageCategories", description="List of age categories"
    )
    count: int = Field(..., description="Total count of items")


class AgeCategoryModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The age category id")
    code: str = Field(..., description="The code for the age category")
    property_id: str = Field(
        ...,
        alias="propertyId",
        description="The id of the property for which the age category will be created",
    )
    name: dict[str, str] = Field(..., description="The name for the age category")
    min_age: int = Field(
        ...,
        alias="minAge",
        description="The minimum age for the age category. The specified value is included in the age range",
    )
    max_age: int = Field(
        ...,
        alias="maxAge",
        description="The maximum age for the age category. The specified value is included in the age range",
    )


class AgeCategorySurchargeModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    adults: int = Field(..., description="The number of adults")
    value: float = Field(
        ...,
        description="The absolute value in the currency of the rate plan as surcharge for each child accompanied by the given number of 'adults'.\nThe minimum value is 0.",
        ge=0.0,
        le=2147483647.0,
    )


class Mode(StrEnum):
    arrival = "Arrival"
    departure = "Departure"
    daily = "Daily"


class DaysOfWeekEnum(StrEnum):
    monday = "Monday"
    tuesday = "Tuesday"
    wednesday = "Wednesday"
    thursday = "Thursday"
    friday = "Friday"
    saturday = "Saturday"
    sunday = "Sunday"


class AvailabilityModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    mode: Mode = Field(
        ...,
        description="You can choose if the service will only be offered\nfor the arrival or departure time slice like early check-in or a final cleaning service. You can also define\na service that is available to be booked for the whole stay. The property defaults to 'Daily'.",
    )
    quantity: int | None = Field(
        None, description="Quota/Limit for service. By default service is unlimited."
    )
    days_of_week: list[DaysOfWeekEnum] | None = Field(
        None,
        alias="daysOfWeek",
        description="You can choose if the service should be available for specific days of the week",
    )


class BookingPeriodModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    from_: AwareDatetime = Field(
        ...,
        alias="from",
        description='Start of booking period<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    to: AwareDatetime = Field(
        ...,
        description='End of booking period<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )


class CancellationPolicyCreatedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The cancellation policy ID")


class Reference(StrEnum):
    prior_to_arrival = "PriorToArrival"
    after_booking = "AfterBooking"


class CompanyAddressModel(AddressModel):
    pass


class CompanyCreatedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The company ID")


class CompanyRatePlanModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="Company ID that can use this rate plan")
    code: str = Field(
        ..., description="The code of the company that can book this rate plan"
    )
    corporate_code: str = Field(
        ...,
        alias="corporateCode",
        description="Company rate plan code, identifying the company + rate plan pair. Is used is offers.",
    )
    name: str = Field(
        ...,
        description="The name of the company that can book this rate plan",
        min_length=1,
    )


class CorporateCodeModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    code: str = Field(..., description="The corporate rate code")
    company_id: str = Field(..., alias="companyId", description="The company ID")
    company_code: str = Field(..., alias="companyCode", description="The company code")
    company_name: str = Field(
        ..., alias="companyName", description="The company name", min_length=1
    )
    rate_plan_id: str = Field(..., alias="ratePlanId", description="The rate plan ID")


class CountModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    count: int


class CreateAgeCategoryModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    code: str = Field(
        ...,
        description="The code for the age category",
        max_length=10,
        min_length=3,
        pattern="^[a-zA-Z0-9_]*$",
    )
    property_id: str = Field(
        ...,
        alias="propertyId",
        description="The id of the property for which the age category will be created",
    )
    name: dict[str, str] = Field(..., description="The name for the age category")
    min_age: int = Field(
        ...,
        alias="minAge",
        description="The minimum age for the age category. The specified value is included in the age range",
        ge=0,
        le=17,
    )
    max_age: int = Field(
        ...,
        alias="maxAge",
        description="The maximum age for the age category. The specified value is included in the age range and the maximum value\nis 17",
        ge=0,
        le=17,
    )


class CreateCompanyRatePlanModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="Company ID that can use this rate plan")
    corporate_code: str | None = Field(
        None,
        alias="corporateCode",
        description="Optional rate plan code that is used by the company. Default is companyCode-ratePlanCode.\nSame code can be specified for several rate plans in one company.\nNo two companies can have a rate plan with the same code.",
    )


class Type(StrEnum):
    absolute = "Absolute"
    percent = "Percent"


class CreatePricingRuleModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    base_rate_plan_id: str = Field(
        ...,
        alias="baseRatePlanId",
        description="The id of the rate plan that will be used as base when calculating the rates.\nThe derivation level of the rate plan used as base rate plan cannot be greater than 2",
    )
    type: Type = Field(
        ...,
        description="The type used to control the calculation of the difference to the rates of the defined base\nrate plan",
    )
    value: float = Field(
        ...,
        description="The value used to control the calculation of the difference to the rates of the defined base\nrate plan. It can be a positive and a negative value. The system will prevent you to define\na value that would lead to negative rates",
    )


class CreateRatePlanCompanyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="Rate plan ID that is used by this company")
    corporate_code: str | None = Field(
        None,
        alias="corporateCode",
        description="Optional rate plan code that is used by this company. Default is companyCode-ratePlanCode.\nSame code can be specified for several rate plans in one company.\nNo two companies can have a rate plan with the same code.",
    )


class ChannelCode(StrEnum):
    direct = "Direct"
    booking_com = "BookingCom"
    ibe = "Ibe"
    channel_manager = "ChannelManager"
    expedia = "Expedia"
    homelike = "Homelike"
    hrs = "Hrs"
    alto_vita = "AltoVita"
    des_vu = "DesVu"


class MinGuaranteeType(StrEnum):
    pm6_hold = "PM6Hold"
    credit_card = "CreditCard"
    prepayment = "Prepayment"
    company = "Company"


class PriceCalculationMode(StrEnum):
    truncate = "Truncate"
    round = "Round"


class PricingUnit(StrEnum):
    room = "Room"
    person = "Person"


class EmbeddedMarketSegmentModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The market segment id")
    code: str | None = Field(None, description="The market segment code")
    name: str | None = Field(None, description="The market segment name")


class EmbeddedNoShowPolicyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The no-show policy id")
    code: str | None = Field(
        None,
        description="The code for the no-show policy that can be shown in reports and table views",
    )
    name: str | None = Field(None, description="The name for the no-show policy")
    description: str | None = Field(
        None, description="The description for the no-show policy"
    )


class EmbeddedPropertyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The property id")
    code: str | None = Field(
        None,
        description="The code for the property that can be shown in reports and table views",
    )
    name: str | None = Field(None, description="The name for the property")
    description: str | None = Field(
        None, description="The description for the property"
    )


class EmbeddedRatePlanModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The rate plan id")
    code: str | None = Field(
        None,
        description="The code for the rate plan that can be shown in reports and table views",
    )
    name: str | None = Field(None, description="The name for the rate plan")
    description: str | None = Field(
        None, description="The description for the rate plan"
    )
    is_subject_to_city_tax: bool = Field(
        ...,
        alias="isSubjectToCityTax",
        description="Whether the rate plan is subject to city tax or not",
    )


class EmbeddedServiceModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The service id")
    code: str | None = Field(None, description="The code for the service")
    name: str | None = Field(None, description="The name for the service")
    description: str | None = Field(None, description="The description for the service")


class Template(StrEnum):
    day_use = "DayUse"
    over_night = "OverNight"


class EmbeddedTimeSliceDefinitionModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The time slice definition id")
    name: str = Field(
        ..., description="The name for the time slice definition", min_length=1
    )
    template: Template = Field(
        ..., description="The template used by the time slice defintion"
    )
    check_in_time: str = Field(
        ...,
        alias="checkInTime",
        description='The check-in time for reservations based on this rate plan<br />A time (without fractional second part) as defined in the <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    check_out_time: str = Field(
        ...,
        alias="checkOutTime",
        description='The check-out time for reservations based on this rate plan<br />A time (without fractional second part) as defined in the <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )


class Type1(StrEnum):
    bed_room = "BedRoom"
    meeting_room = "MeetingRoom"
    event_space = "EventSpace"
    parking_lot = "ParkingLot"
    other = "Other"


class EmbeddedUnitGroupModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The unit group id")
    code: str | None = Field(
        None,
        description="The code for the unit group that can be shown in reports and table views",
    )
    name: str | None = Field(None, description="The name for the unit group")
    description: str | None = Field(
        None, description="The description for the unit group"
    )
    type: Type1 | None = Field(None, description="The unit group type")


class Network(StrEnum):
    peppol = "Peppol"


class InvoiceNetworkIdentityModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    network: Network = Field(
        ..., description="The Network through which to send the Invoice\ne. g. Peppol"
    )
    id: str = Field(
        ...,
        description='The Id of the company at the network.\ne.g. "0208:123456789"',
        min_length=1,
    )


class MessageItemCollection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    messages: list[str] | None = None


class MonetaryValueModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    amount: float
    currency: str


class NoShowPolicyCreatedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The no-show policy ID")


class Operation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    value: Any | None = None
    path: str | None = None
    op: str | None = None
    from_: str | None = Field(None, alias="from")


class PercentValueModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    percent: int = Field(
        ...,
        description="Percent to take from the base. Must be between 0 and 100.",
        ge=0,
        le=100,
    )
    limit: int | None = Field(
        None,
        description="If set, limits the calculation base to the specified number of time slices, starting from the beginning.\n\nIf not set, the entire stay will be used as a base.",
    )
    include_service_ids: list[str] | None = Field(
        None,
        alias="includeServiceIds",
        description="Services included in the calculation base. If none are set, only charges for the unit will be used.\n\nThe services are only included, if they are part of the rate plan. Extra services are ignored.",
    )


class PeriodModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    hours: int | None = Field(None, description="The number of hours within the period")
    days: int | None = Field(None, description="The number of days within the period")
    months: int | None = Field(
        None, description="The number of months within the period"
    )


class PricingRuleModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    base_rate_plan: EmbeddedRatePlanModel = Field(..., alias="baseRatePlan")
    type: Type = Field(
        ...,
        description="The type used to control the calculation of the difference to the rates of the defined base\nrate plan",
    )
    value: float = Field(
        ...,
        description="The value used to control the calculation of the difference to the rates of the defined base\nrate plan. It can be a positive and a negative value",
    )


class PromoCodeModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    code: str = Field(
        ...,
        description="The code of special rate or discount\nor agreement between the hotel and an organization",
    )
    related_rateplan_ids: list[str] = Field(
        ...,
        alias="relatedRateplanIds",
        description="All rate plan IDs having this code",
    )


class RatePatchModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    from_: str = Field(
        ...,
        alias="from",
        description='The start of the time range to filter the rates by. All rates where the from date and time is equal or later than\nthe specified date and optional time will be affected<br />Specify either a pure date or a date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    to: str = Field(
        ...,
        description='The end of the time range to filter the rates by. All rates where the from date and time is earlier than\nthe specified date and optional time will be affected<br />Specify either a pure date or a date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    week_days: list[DaysOfWeekEnum] | None = Field(
        None,
        alias="weekDays",
        description="The weekdays that will be patched. If not specified, all weekdays will be patched.",
    )
    operations: list[Operation] | None = None


class RatePlanAgeCategoryModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The id of the age category")
    surcharges: list[AgeCategorySurchargeModel] = Field(
        ...,
        description="Additional charges for the current age category. The absolute value will be added to the manually defined or calculated derived rates.\nThe values for 'adults' must be unique within the list, and starting from 1. Values equal or higher than\nthe maximum unit group occupancy will be silently ignored.",
    )


class RatePlanCompanyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="Rate plan ID that is used by this company")
    code: str = Field(..., description="Rate plan code that is used by this company")
    corporate_code: str | None = Field(
        None,
        alias="corporateCode",
        description="Company rate plan code, identifying the company + rate plan pair. Is used is offers.",
    )
    name: str = Field(..., description="The name of the rate plan", min_length=1)


class RatePlanCreatedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The rate plan id")


class PricingMode(StrEnum):
    included = "Included"
    additional = "Additional"


class RatePlanServiceItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    service: EmbeddedServiceModel
    gross_price: MonetaryValueModel = Field(..., alias="grossPrice")
    pricing_mode: PricingMode = Field(
        ...,
        alias="pricingMode",
        description="Whether the service price is included in or added to the base rate. The property defaults to `Included`.",
    )


class RatePlanServiceModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    service_id: str = Field(
        ..., alias="serviceId", description="Service id to be included in the rate plan"
    )
    gross_price: MonetaryValueModel = Field(..., alias="grossPrice")
    pricing_mode: PricingMode | None = Field(
        None,
        alias="pricingMode",
        description="Whether the service price is included in or added to the base rate. The property defaults to `Included`.",
    )


class RateRestrictionsModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    min_length_of_stay: int | None = Field(
        None,
        alias="minLengthOfStay",
        description="The minimum length of stay in order to book the rate. If at least this number\nof time slices are covered by the stay duration the rate will be offered.",
        ge=1,
        le=2147483647,
    )
    max_length_of_stay: int | None = Field(
        None,
        alias="maxLengthOfStay",
        description="The maximum length of stay in order to book the rate. If not more than this number\nof time slices are covered by the stay duration the rate will be offered.",
        ge=1,
        le=2147483647,
    )
    closed: bool = Field(
        ..., description="Whether the rate can be booked for a stay-through reservation"
    )
    closed_on_arrival: bool = Field(
        ...,
        alias="closedOnArrival",
        description="Whether the rate can be booked on the reservation's arrival date",
    )
    closed_on_departure: bool = Field(
        ...,
        alias="closedOnDeparture",
        description="Whether the rate can be booked on the reservation's departure date",
    )


class RatesPatchRequestModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    rates: list[RatePatchModel] | None = None


class RatesRangeModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    from_: date = Field(
        ...,
        alias="from",
        description="The first date when the rate plan has rates set",
        examples=["2020-10-10"],
    )
    to: date = Field(
        ...,
        description="The last date when the rate plan has rates set",
        examples=["2020-10-10"],
    )


class ReplaceCompanyRatePlanModel(CreateCompanyRatePlanModel):
    pass


class ReplaceRateModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    from_: AwareDatetime = Field(
        ...,
        alias="from",
        description='Date and time the rate begins<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    to: AwareDatetime = Field(
        ...,
        description='Date and time the rate ends<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    price: MonetaryValueModel | None = None
    restrictions: RateRestrictionsModel | None = None


class ServiceCreatedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The item id")


class ServiceItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="Id")
    name: str = Field(..., description="Name", min_length=1)
    code: str = Field(..., description="The code for the service")
    description: str = Field(..., description="Description", min_length=1)
    default_gross_price: MonetaryValueModel = Field(..., alias="defaultGrossPrice")
    pricing_unit: PricingUnit | None = Field(
        None,
        alias="pricingUnit",
        description="Defines per which unit (flat, room, person) this item is offered and priced",
    )
    post_next_day: bool = Field(
        ...,
        alias="postNextDay",
        description="Whether the service is delivered and posted on the same business date as the accommodation, or on the next day.",
    )
    service_type: ServiceType = Field(
        ...,
        alias="serviceType",
        description="The service type, used by accounting to determine the correct revenue account",
    )
    vat_type: VatType = Field(
        ...,
        alias="vatType",
        description="The vat type, used by accounting to determine the correct vat amount and account",
    )
    availability: AvailabilityModel
    property: EmbeddedPropertyModel
    sub_account_id: str | None = Field(
        None,
        alias="subAccountId",
        description="ID of the custom sub-account, used by accounting to determine the correct revenue account",
    )
    channel_codes: list[ChannelCode] | None = Field(
        None,
        alias="channelCodes",
        description="The channel codes the service is sold through",
    )
    age_category_id: str | None = Field(
        None,
        alias="ageCategoryId",
        description="The id of the age category associated with this service.",
    )


class ServiceListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    services: list[ServiceItemModel] = Field(..., description="List of packages")
    count: int = Field(..., description="Total count of items")


class ServiceModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The service id")
    code: str = Field(..., description="The code for the service")
    name: dict[str, str] = Field(..., description="The name for the service")
    description: dict[str, str] = Field(
        ..., description="The description for the service"
    )
    default_gross_price: MonetaryValueModel = Field(..., alias="defaultGrossPrice")
    pricing_unit: PricingUnit = Field(
        ...,
        alias="pricingUnit",
        description="Defines the granularity (room, person) for which this item is offered and priced",
    )
    post_next_day: bool = Field(
        ...,
        alias="postNextDay",
        description="Whether the service is delivered and posted on the same business date as the accommodation, or on the next day.",
    )
    availability: AvailabilityModel
    accounting_configs: list[AccountingConfigModel] = Field(
        ...,
        alias="accountingConfigs",
        description="The collection of accounting configs with validity periods.",
    )
    property: EmbeddedPropertyModel
    channel_codes: list[ChannelCode] | None = Field(
        None,
        alias="channelCodes",
        description="The channel codes the service is sold through. When no channels are defined, the service is sold only in a package",
    )
    age_category_id: str | None = Field(
        None,
        alias="ageCategoryId",
        description="The id of the age category associated with this service.",
    )


class SurchargeModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    adults: int = Field(..., description="The total numbers of adults")
    type: Type = Field(..., description="Specifies how to interpret 'Value'")
    value: float = Field(
        ...,
        description="The percent or absolute value (in the rate plan's currency) of the surcharge",
    )


class BookingRestrictionsModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    min_advance: PeriodModel | None = Field(None, alias="minAdvance")
    max_advance: PeriodModel | None = Field(None, alias="maxAdvance")
    late_booking_until: str | None = Field(
        None,
        alias="lateBookingUntil",
        description='Time of day until the late booking can be made for this rate plan\nRestrictions:\n- the time has to be between the check-in (excl.) and check-out time (excl.)\n- can only be set, if MinAdvance is not set<br />A time (without fractional second part) as defined in the <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )


class CalculatedRateModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    adults: int = Field(..., description="Number of adults this rate is valid for")
    price: MonetaryValueModel
    included_services_price: MonetaryValueModel | None = Field(
        None, alias="includedServicesPrice"
    )


class CompanyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The ID of this company")
    code: str = Field(..., description="The code for the company")
    property_id: str = Field(
        ..., alias="propertyId", description="The ID of the property"
    )
    name: str = Field(..., description="The name of the company", min_length=1)
    invoicing_email: str | None = Field(
        None,
        alias="invoicingEmail",
        description="The email address for invoicing purposes",
    )
    phone: str | None = Field(None, description="The company's phone number")
    tax_id: str | None = Field(
        None, alias="taxId", description="The tax ID of the company"
    )
    additional_tax_id: str | None = Field(
        None,
        alias="additionalTaxId",
        description="The additional tax ID of the company (e.g. SIRET in France, Codice Destinatario in Italy, SST in Malaysia)",
    )
    additional_tax_id2: str | None = Field(
        None,
        alias="additionalTaxId2",
        description="The additional tax ID of the company (e.g. Codice Fiscale in Italy, BRN in Malaysia)",
    )
    invoice_network_identity: InvoiceNetworkIdentityModel | None = Field(
        None, alias="invoiceNetworkIdentity"
    )
    address: CompanyAddressModel
    can_check_out_on_ar: bool = Field(
        ...,
        alias="canCheckOutOnAr",
        description="Whether or not the company is allowed to check out on AR / invoice",
    )
    rate_plans: list[RatePlanCompanyModel] | None = Field(
        None,
        alias="ratePlans",
        description="Rate plans that can be booked by this company",
    )


class CorporateCodeListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    corporate_codes: list[CorporateCodeModel] = Field(
        ..., alias="corporateCodes", description="List of existing corporate codes"
    )
    count: int = Field(..., description="Total count of items")


class CreateCompanyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    code: str = Field(
        ...,
        description="The code for the company",
        max_length=10,
        min_length=3,
        pattern="^[a-zA-Z0-9_]*$",
    )
    property_id: str = Field(
        ..., alias="propertyId", description="The ID of the property"
    )
    name: str = Field(..., description="The name of the company", min_length=1)
    invoicing_email: str | None = Field(
        None,
        alias="invoicingEmail",
        description="The email address for invoicing purposes",
    )
    phone: str | None = Field(None, description="The company's phone")
    tax_id: str | None = Field(
        None, alias="taxId", description="The tax ID of the company"
    )
    additional_tax_id: str | None = Field(
        None,
        alias="additionalTaxId",
        description="The additional tax ID of the company (e.g. SIRET in France, Codice Destinatario in Italy, SST in Malaysia)",
    )
    additional_tax_id2: str | None = Field(
        None,
        alias="additionalTaxId2",
        description="The additional tax ID of the company (e.g. Codice Fiscale in Italy, BRN in Malaysia)",
    )
    invoice_network_identity: InvoiceNetworkIdentityModel | None = Field(
        None, alias="invoiceNetworkIdentity"
    )
    address: AddressModel
    can_check_out_on_ar: bool = Field(
        ...,
        alias="canCheckOutOnAr",
        description="Whether or not the company is allowed to check out on AR / invoice",
    )
    rate_plans: list[CreateRatePlanCompanyModel] | None = Field(
        None,
        alias="ratePlans",
        description="Rate plans that can be booked by this company",
    )


class CreateRatePlanModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    code: str = Field(
        ...,
        description="The code for the rate plan that can be shown in reports and table views",
        max_length=20,
        min_length=3,
        pattern="^[a-zA-Z0-9_]*$",
    )
    property_id: str = Field(
        ...,
        alias="propertyId",
        description="The id of the property for which the rate plan will be created",
    )
    unit_group_id: str = Field(
        ...,
        alias="unitGroupId",
        description="The id of the unit group offered with this rate plan",
    )
    cancellation_policy_id: str = Field(
        ...,
        alias="cancellationPolicyId",
        description="The id of the cancellation policy valid for this rate plan",
    )
    no_show_policy_id: str | None = Field(
        None,
        alias="noShowPolicyId",
        description="The id of the no-show policy valid for this rate plan",
    )
    channel_codes: list[ChannelCode] = Field(
        ...,
        alias="channelCodes",
        description="The channel codes the rate plan is sold through",
    )
    promo_codes: list[str] | None = Field(
        None,
        alias="promoCodes",
        description="The rate codes for promotional and hidden rates. If at least one code is set the rate will be not publicly visible\nanymore and only be offered when one of the promo codes is given in the offer request.\nFor backward compatibility it is still not possible to set multiple promo codes.",
    )
    is_subject_to_city_tax: bool | None = Field(
        None,
        alias="isSubjectToCityTax",
        description="Whether the rate plan is subject to city tax or not.\nDefault value is `true`",
    )
    time_slice_definition_id: str = Field(
        ...,
        alias="timeSliceDefinitionId",
        description="Defines the time periods for which the unit group related to this rate plan is rented out",
    )
    name: dict[str, str] = Field(..., description="The name for the rate plan")
    description: dict[str, str] = Field(
        ..., description="The description for the rate plan"
    )
    min_guarantee_type: MinGuaranteeType = Field(
        ...,
        alias="minGuaranteeType",
        description="The minimum guarantee to be provided when this rate plan is booked so\nthe reservation will be guaranteed to the guest",
    )
    price_calculation_mode: PriceCalculationMode | None = Field(
        None,
        alias="priceCalculationMode",
        description="The calculation mode is used when calculating the adults' surcharges and derived rates.\nDefaults to Truncate. Example: for a rate of 125.99 and a surcharge of +10%,\nwhen Truncate is selected, the result would be 125.99 + 12 = 137.99\nWhen Round is selected, the result would be 125.99 + 12.60 = 138.59",
    )
    booking_periods: list[BookingPeriodModel] | None = Field(
        None,
        alias="bookingPeriods",
        description="Time periods when the rate plan is bookable",
    )
    restrictions: BookingRestrictionsModel | None = None
    pricing_rule: CreatePricingRuleModel | None = Field(None, alias="pricingRule")
    surcharges: list[SurchargeModel] | None = Field(
        None,
        description="Additional charges for more than single occupancy. The percent or absolute value will be added to\nthe manually defined or calculated derived rates.\nThe values for 'adults' must be unique within the list and starting from occupancy of 2 adults. Values higher than the maximum unit group occupancy will be silently ignored.\nThe surcharges are required for all possible occupancies defined by the 'MaxPersons' of the unit group.",
    )
    age_categories: list[RatePlanAgeCategoryModel] | None = Field(
        None, alias="ageCategories", description="Additional charges per age category."
    )
    included_services: list[RatePlanServiceModel] | None = Field(
        None,
        alias="includedServices",
        description="Services that are included in the rate plan",
    )
    companies: list[CreateCompanyRatePlanModel] | None = Field(
        None, description="Companies that can use this rate plan"
    )
    accounting_configs: list[AccountingConfigModel] | None = Field(
        None,
        alias="accountingConfigs",
        description="The collection of accounting configs with validity periods.\nThis is a temporary field, avoid using it.",
    )
    market_segment_id: str | None = Field(
        None,
        alias="marketSegmentId",
        description="The id of the market segment for this rate plan",
    )


class CreateServiceModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    code: str = Field(
        ...,
        description="The code for the service that can be shown in reports and table views",
        max_length=10,
        min_length=3,
        pattern="^[a-zA-Z0-9_]*$",
    )
    name: dict[str, str] = Field(..., description="The name for the service")
    description: dict[str, str] = Field(
        ..., description="The description for the service"
    )
    property_id: str = Field(
        ...,
        alias="propertyId",
        description="The id of the property where the item will be created",
    )
    default_gross_price: MonetaryValueModel = Field(..., alias="defaultGrossPrice")
    pricing_unit: PricingUnit = Field(
        ...,
        alias="pricingUnit",
        description="Defines the granularity for which this item is offered and priced.",
    )
    post_next_day: bool = Field(
        ...,
        alias="postNextDay",
        description="Whether the service is delivered and posted on the same business date as the accommodation, or on the next day.",
    )
    availability: AvailabilityModel | None = None
    channel_codes: list[ChannelCode] | None = Field(
        None,
        alias="channelCodes",
        description="The channel codes the service is sold through. When no channels are defined, the service is sold only in a package",
    )
    accounting_configs: list[AccountingConfigModel] | None = Field(
        None,
        alias="accountingConfigs",
        description="The collection of accounting configs with validity periods.\nThis is a temporary field, avoid using it.",
    )
    age_category_id: str | None = Field(
        None,
        alias="ageCategoryId",
        description="The id of the age category associated with this service.",
    )


class EmbeddedCancellationPolicyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The cancellation policy id")
    code: str | None = Field(
        None,
        description="The code for the cancellation policy that can be shown in reports and table views",
    )
    name: str | None = Field(None, description="The name for the cancellation policy")
    description: str | None = Field(
        None, description="The description for the cancellation policy"
    )
    period_prior_to_arrival: PeriodModel | None = Field(
        None, alias="periodPriorToArrival"
    )


class FeeDetailsModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    vat_type: VatType = Field(
        ..., alias="vatType", description="VAT that applies for the fee"
    )
    fixed_value: MonetaryValueModel | None = Field(None, alias="fixedValue")
    percent_value: PercentValueModel | None = Field(None, alias="percentValue")


class NoShowPolicyItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The no-show policy id")
    code: str = Field(..., description="The code for the policy")
    name: str = Field(..., description="The name for the no-show policy", min_length=1)
    description: str = Field(
        ..., description="The description for the no-show policy", min_length=1
    )
    property_id: str = Field(
        ...,
        alias="propertyId",
        description="The id of the property where the no-show policy was created",
    )
    fee: FeeDetailsModel


class NoShowPolicyListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    no_show_policies: list[NoShowPolicyItemModel] = Field(
        ..., alias="noShowPolicies", description="List of no-show policies"
    )
    count: int = Field(..., description="Total count of items")


class NoShowPolicyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The no-show policy id")
    code: str = Field(
        ...,
        description="The code for the policy",
        max_length=10,
        min_length=3,
        pattern="^[a-zA-Z0-9_]*$",
    )
    name: dict[str, str] = Field(..., description="The name for the no-show policy")
    description: dict[str, str] = Field(
        ..., description="The description for the no-show policy"
    )
    property_id: str = Field(
        ...,
        alias="propertyId",
        description="The id of the property where the no-show policy was created",
    )
    fee: FeeDetailsModel


class PromoCodeListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    promo_codes: list[PromoCodeModel] = Field(
        ..., alias="promoCodes", description="List of existing promo codes"
    )
    count: int = Field(..., description="Total count of items")


class RateItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    from_: AwareDatetime = Field(
        ...,
        alias="from",
        description='Date and time the rate begins<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    to: AwareDatetime = Field(
        ...,
        description='Date and time the rate ends<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    price: MonetaryValueModel | None = None
    included_services_price: MonetaryValueModel | None = Field(
        None, alias="includedServicesPrice"
    )
    calculated_prices: list[CalculatedRateModel] | None = Field(
        None,
        alias="calculatedPrices",
        description="A list of prices for occupancies 2 or higher. Only set, if the rate plan defines surcharges for different occupancies",
    )
    restrictions: RateRestrictionsModel | None = None


class RateListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    rates: list[RateItemModel] = Field(..., description="List of rates")
    count: int = Field(..., description="Total count of items")


class RatePlanItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The rate plan id")
    code: str = Field(
        ...,
        description="The code for the rate plan that can be shown in reports and table views",
    )
    name: str = Field(..., description="The name for the rate plan", min_length=1)
    description: str = Field(
        ..., description="The description for the rate plan", min_length=1
    )
    min_guarantee_type: MinGuaranteeType = Field(
        ...,
        alias="minGuaranteeType",
        description="The minimum guarantee to be provided when this rate plan is booked so\nthe reservation will be guaranteed to the guest",
    )
    price_calculation_mode: PriceCalculationMode | None = Field(
        None,
        alias="priceCalculationMode",
        description="The calculation mode is used when calculating the adults' surcharges and derived rates.\nDefaults to Truncate. Example: for a rate of 125.99 and a surcharge of +10%,\nwhen Truncate is selected, the result would be 125.99 + 12 = 137.99\nWhen Round is selected, the result would be 125.99 + 12.60 = 138.59",
    )
    property: EmbeddedPropertyModel
    unit_group: EmbeddedUnitGroupModel = Field(..., alias="unitGroup")
    cancellation_policy: EmbeddedCancellationPolicyModel = Field(
        ..., alias="cancellationPolicy"
    )
    no_show_policy: EmbeddedNoShowPolicyModel = Field(..., alias="noShowPolicy")
    channel_codes: list[ChannelCode] = Field(
        ...,
        alias="channelCodes",
        description="The channel codes the rate plan is sold through",
    )
    promo_codes: list[str] | None = Field(
        None,
        alias="promoCodes",
        description="The rate codes for promotional and hidden rates. If at least one code is set the rate will be not publicly visible\nanymore and only be offered when one of the promo codes is given in the offer request.\nFor backward compatibility it is still not possible to set multiple promo codes.",
    )
    time_slice_definition: EmbeddedTimeSliceDefinitionModel = Field(
        ..., alias="timeSliceDefinition"
    )
    restrictions: BookingRestrictionsModel | None = None
    booking_periods: list[BookingPeriodModel] | None = Field(
        None,
        alias="bookingPeriods",
        description="Time periods when the rate plan is bookable",
    )
    is_bookable: bool = Field(
        ...,
        alias="isBookable",
        description="Indicates whether the rate plan has an active booking period",
    )
    is_subject_to_city_tax: bool = Field(
        ...,
        alias="isSubjectToCityTax",
        description="Whether the rate plan is subject to city tax or not",
    )
    pricing_rule: PricingRuleModel | None = Field(None, alias="pricingRule")
    is_derived: bool = Field(
        ...,
        alias="isDerived",
        description="Indicates whether the rates for this rate plan are derived from another rate plan",
    )
    derivation_level: int = Field(
        ...,
        alias="derivationLevel",
        description="Indicates the derivation level of the rate plan. When zero, it is a rate plan with manually managed prices.",
    )
    surcharges: list[SurchargeModel] | None = Field(
        None,
        description="Additional charges for more than single occupancy. The percent or absolute value will be added to the manually defined or calculated derived rates.",
    )
    age_categories: list[RatePlanAgeCategoryModel] | None = Field(
        None, alias="ageCategories", description="Additional charges per age category."
    )
    included_services: list[RatePlanServiceItemModel] | None = Field(
        None,
        alias="includedServices",
        description="Services that are included in the rate plan",
    )
    companies: list[CompanyRatePlanModel] | None = Field(
        None, description="Companies that can use this rate plan"
    )
    rates_range: RatesRangeModel | None = Field(None, alias="ratesRange")
    accounting_configs: list[AccountingConfigModel] = Field(
        ...,
        alias="accountingConfigs",
        description="The collection of accounting configs with validity periods.",
    )
    market_segment: EmbeddedMarketSegmentModel | None = Field(
        None, alias="marketSegment"
    )
    is_archived: bool | None = Field(
        None,
        alias="isArchived",
        description="Whether the rate plan is archived or not.",
    )


class RatePlanListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    rate_plans: list[RatePlanItemModel] = Field(
        ..., alias="ratePlans", description="List of rate plans"
    )
    count: int = Field(..., description="Total count of items")


class RatePlanModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The rate plan  id")
    code: str = Field(
        ...,
        description="The code for the rate plan that can be shown in reports and table views",
    )
    name: dict[str, str] = Field(..., description="The name for the rate plan")
    description: dict[str, str] = Field(
        ..., description="The description for the rate plan"
    )
    min_guarantee_type: MinGuaranteeType = Field(
        ...,
        alias="minGuaranteeType",
        description="The minimum guarantee to be provided when this rate plan is booked so\nthe reservation will be guaranteed to the guest",
    )
    price_calculation_mode: PriceCalculationMode | None = Field(
        None,
        alias="priceCalculationMode",
        description="The calculation mode is used when calculating the adults' surcharges and derived rates.\nDefaults to Truncate. Example: for a rate of 125.99 and a surcharge of +10%,\nwhen Truncate is selected, the result would be 125.99 + 12 = 137.99\nWhen Round is selected, the result would be 125.99 + 12.60 = 138.59",
    )
    property: EmbeddedPropertyModel
    unit_group: EmbeddedUnitGroupModel = Field(..., alias="unitGroup")
    cancellation_policy: EmbeddedCancellationPolicyModel = Field(
        ..., alias="cancellationPolicy"
    )
    no_show_policy: EmbeddedNoShowPolicyModel = Field(..., alias="noShowPolicy")
    channel_codes: list[ChannelCode] = Field(
        ...,
        alias="channelCodes",
        description="The channel codes the rate plan is sold through",
    )
    accounting_configs: list[AccountingConfigModel] = Field(
        ...,
        alias="accountingConfigs",
        description="The collection of accounting configs with validity periods.",
    )
    promo_codes: list[str] | None = Field(
        None,
        alias="promoCodes",
        description="The rate codes for promotional and hidden rates. If at least one code is set the rate will be not publicly visible\nanymore and only be offered when one of the promo codes is given in the offer request.\nFor backward compatibility it is still not possible to set multiple promo codes.",
    )
    time_slice_definition: EmbeddedTimeSliceDefinitionModel = Field(
        ..., alias="timeSliceDefinition"
    )
    restrictions: BookingRestrictionsModel | None = None
    booking_periods: list[BookingPeriodModel] | None = Field(
        None,
        alias="bookingPeriods",
        description="Time periods when the rate plan is bookable",
    )
    is_bookable: bool = Field(
        ...,
        alias="isBookable",
        description="Indicates whether the rate plan has an active booking period",
    )
    is_subject_to_city_tax: bool = Field(
        ...,
        alias="isSubjectToCityTax",
        description="Whether the rate plan is subject to city tax or not.\nDefault value is `true`",
    )
    pricing_rule: PricingRuleModel | None = Field(None, alias="pricingRule")
    is_derived: bool = Field(
        ...,
        alias="isDerived",
        description="Indicates whether the rates for this rate plan are derived from another rate plan",
    )
    derivation_level: int = Field(
        ...,
        alias="derivationLevel",
        description="Indicates the derivation level of the rate plan. When zero, it is a rate plan with manually managed prices.",
    )
    surcharges: list[SurchargeModel] | None = Field(
        None,
        description="Additional charges for more than single occupancy. The percent or absolute value will be added to the manually defined or calculated derived rates.",
    )
    age_categories: list[RatePlanAgeCategoryModel] | None = Field(
        None, alias="ageCategories", description="Additional charges per age category."
    )
    included_services: list[RatePlanServiceModel] | None = Field(
        None,
        alias="includedServices",
        description="Services that are included in the rate plan",
    )
    companies: list[CompanyRatePlanModel] | None = Field(
        None, description="Companies that can use this rate plan"
    )
    rates_range: RatesRangeModel | None = Field(None, alias="ratesRange")
    market_segment: EmbeddedMarketSegmentModel | None = Field(
        None, alias="marketSegment"
    )
    is_archived: bool | None = Field(
        None, alias="isArchived", description="Whether the rate plan is archived or not"
    )


class ReplaceRateListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    rates: list[ReplaceRateModel] = Field(..., description="List of rates")


class ReplaceRatePlanModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    name: dict[str, str] = Field(..., description="The name for the rate plan")
    description: dict[str, str] = Field(
        ..., description="The description for the rate plan"
    )
    min_guarantee_type: MinGuaranteeType = Field(
        ...,
        alias="minGuaranteeType",
        description="The minimum guarantee to be provided when this rate plan is booked so\nthe reservation will be guaranteed to the guest",
    )
    price_calculation_mode: PriceCalculationMode | None = Field(
        None,
        alias="priceCalculationMode",
        description="The calculation mode is used when calculating the adults' surcharges and derived rates.\nDefaults to Truncate. Example: for a rate of 125.99 and a surcharge of +10%,\nwhen Truncate is selected, the result would be 125.99 + 12 = 137.99\nWhen Round is selected, the result would be 125.99 + 12.60 = 138.59",
    )
    channel_codes: list[ChannelCode] = Field(
        ...,
        alias="channelCodes",
        description="The channel codes the rate plan is sold through",
    )
    promo_codes: list[str] | None = Field(
        None,
        alias="promoCodes",
        description="The rate codes for promotional and hidden rates. If at least one code is set the rate will be not publicly visible\nanymore and only be offered when one of the promo codes is given in the offer request.\nFor backward compatibility it is still not possible to set multiple promo codes.",
    )
    is_subject_to_city_tax: bool | None = Field(
        None,
        alias="isSubjectToCityTax",
        description="Whether the rate plan is subject to city tax or not.\nDefault value is `true`",
    )
    cancellation_policy_id: str = Field(
        ...,
        alias="cancellationPolicyId",
        description="The id of the cancellation policy valid for this rate plan",
    )
    no_show_policy_id: str | None = Field(
        None,
        alias="noShowPolicyId",
        description="The id of the no-show policy valid for this rate plan",
    )
    booking_periods: list[BookingPeriodModel] | None = Field(
        None,
        alias="bookingPeriods",
        description="Time periods when the rate plan is bookable",
    )
    restrictions: BookingRestrictionsModel | None = None
    included_services: list[RatePlanServiceModel] | None = Field(
        None,
        alias="includedServices",
        description="Services that are included in the rate plan",
    )
    companies: list[ReplaceCompanyRatePlanModel] | None = Field(
        None, description="Companies that can use this rate plan"
    )
    pricing_rule: CreatePricingRuleModel | None = Field(None, alias="pricingRule")
    surcharges: list[SurchargeModel] | None = Field(
        None,
        description="Additional charges for more than single occupancy. The percent or absolute value will be added to the manually defined or calculated derived rates.\nThe values for 'adults' must be unique within the list and starting from occupancy of 2 adults. Values higher than the maximum unit group occupancy will be silently ignored.\nThe surcharges are required for all possible occupancies defined by the 'MaxPersons' of the unit group.",
    )
    age_categories: list[RatePlanAgeCategoryModel] | None = Field(
        None, alias="ageCategories", description="Additional charges per age category."
    )
    accounting_configs: list[AccountingConfigModel] | None = Field(
        None,
        alias="accountingConfigs",
        description="The collection of accounting configs with validity periods.",
    )
    market_segment_id: str | None = Field(
        None,
        alias="marketSegmentId",
        description="The id of the market segment for this rate plan",
    )


class CancellationPolicyItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="Id")
    name: str = Field(..., description="Name", min_length=1)
    code: str = Field(..., description="The code for the cancellation policy")
    description: str = Field(..., description="Description", min_length=1)
    property_id: str = Field(
        ...,
        alias="propertyId",
        description="The id of the property where the cancellation policy was created",
    )
    period_from_reference: PeriodModel = Field(..., alias="periodFromReference")
    reference: Reference = Field(
        ...,
        description="The due date for the cancellation policy will be calculated based on this reference point, and the defined time period.\n\n\n\nExamples:\n\n- 1 day and 12 hours prior to arrival\n\n- 0 prior to arrival (meaning, cancellations are always free)\n\n- 24 hours after booking\n\n- 0 after booking (meaning, cancellations ar never free)",
    )
    fee: FeeDetailsModel


class CancellationPolicyListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    cancellation_policies: list[CancellationPolicyItemModel] = Field(
        ..., alias="cancellationPolicies", description="List of cancellation policies"
    )
    count: int = Field(..., description="Total count of items")


class CancellationPolicyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The cancellation policy id")
    code: str = Field(
        ...,
        description="The code for the policy",
        max_length=10,
        min_length=3,
        pattern="^[a-zA-Z0-9_]*$",
    )
    name: dict[str, str] = Field(
        ..., description="The name for the cancellation policy"
    )
    description: dict[str, str] = Field(
        ..., description="The description for the cancellation policy"
    )
    property_id: str = Field(
        ...,
        alias="propertyId",
        description="The id of the property where the cancellation policy was created",
    )
    period_from_reference: PeriodModel = Field(..., alias="periodFromReference")
    reference: Reference = Field(
        ...,
        description="The due date for the cancellation policy will be calculated based on this reference point, and the defined time period.\n\n\n\nExamples:\n\n- 1 day and 12 hours prior to arrival\n\n- 0 prior to arrival (meaning, cancellations are always free)\n\n- 24 hours after booking\n\n- 0 after booking (meaning, cancellations ar never free)",
    )
    fee: FeeDetailsModel


class CompanyListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    companies: list[CompanyModel] = Field(..., description="List of companies")
    count: int = Field(..., description="Total count of items")


class CreateCancellationPolicyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    code: str = Field(
        ...,
        description="The code for the cancellation policy, used to assemble its id",
        max_length=10,
        min_length=3,
        pattern="^[a-zA-Z0-9_]*$",
    )
    name: dict[str, str] = Field(
        ..., description="The name for the cancellation policy"
    )
    description: dict[str, str] = Field(
        ..., description="The description for the cancellation policy"
    )
    property_id: str = Field(
        ...,
        alias="propertyId",
        description="The id of the property where the cancellation policy will be created",
    )
    period_from_reference: PeriodModel | None = Field(None, alias="periodFromReference")
    reference: Reference = Field(
        ...,
        description="The due date for the cancellation policy will be calculated based on this reference point",
    )
    fee: FeeDetailsModel


class CreateNoShowPolicyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    code: str = Field(
        ...,
        description="The code for the no-show policy, used to assemble its id",
        max_length=10,
        min_length=3,
        pattern="^[a-zA-Z0-9_]*$",
    )
    name: dict[str, str] = Field(..., description="The name for the no-show policy")
    description: dict[str, str] = Field(
        ..., description="The description for the no-show policy"
    )
    property_id: str = Field(
        ...,
        alias="propertyId",
        description="The id of the property where the no-show policy will be created",
    )
    fee: FeeDetailsModel
