# generated by datamodel-codegen:
#   filename:  core_v1_finance.json
#   timestamp: 2026-05-12T12:22:02+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, Field


class Command(StrEnum):
    post_charge = "PostCharge"
    post_payment = "PostPayment"
    move_line_item = "MoveLineItem"
    post_prepayment = "PostPrepayment"
    post_to_accounts_receivables = "PostToAccountsReceivables"
    post_prepayment_vat = "PostPrepaymentVat"
    post_to_loss_of_accounts_receivables = "PostToLossOfAccountsReceivables"
    system = "System"


class ReferenceType(StrEnum):
    house = "House"
    guest = "Guest"
    external = "External"
    booking = "Booking"


class AddedChargeModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The id of the added charge")
    fee_charge_ids: list[str] | None = Field(
        None, alias="feeChargeIds", description="The fee charges ids"
    )


class AddressModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    address_line1: str = Field(..., alias="addressLine1", min_length=1)
    address_line2: str | None = Field(None, alias="addressLine2")
    postal_code: str = Field(..., alias="postalCode", min_length=1)
    city: str = Field(..., min_length=1)
    region_code: str | None = Field(None, alias="regionCode")
    country_code: str = Field(..., alias="countryCode")


class ServiceType(StrEnum):
    other = "Other"
    accommodation = "Accommodation"
    food_and_beverages = "FoodAndBeverages"
    cancellation_fees = "CancellationFees"
    no_show = "NoShow"
    city_tax = "CityTax"
    second_city_tax = "SecondCityTax"


class VatType(StrEnum):
    null = "Null"
    very_reduced = "VeryReduced"
    reduced = "Reduced"
    normal = "Normal"
    without = "Without"
    special = "Special"
    special1 = "Special1"
    special2 = "Special2"
    reduced_covid19 = "ReducedCovid19"
    normal_covid19 = "NormalCovid19"
    mixed = "Mixed"


class AmountModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    gross_amount: float = Field(..., alias="grossAmount")
    net_amount: float = Field(..., alias="netAmount")
    vat_type: VatType = Field(..., alias="vatType")
    vat_percent: float = Field(..., alias="vatPercent")
    currency: str


class BankAccountModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    iban: str | None = None
    bic: str | None = None
    bank: str | None = None


class BulkAllowanceCreatedItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The id of the created allowance")
    source_charge_id: str = Field(
        ...,
        alias="sourceChargeId",
        description="The id of the charge the allowance has been added to",
    )


class BulkAllowanceCreatedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    items: list[BulkAllowanceCreatedItemModel] = Field(
        ..., description="Allowances that have been created"
    )


class BulkMoveItemRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    source_folio_id: str = Field(
        ..., alias="sourceFolioId", description="ID of the source folio"
    )
    target_folio_id: str = Field(
        ..., alias="targetFolioId", description="ID of the target folio"
    )
    charge_ids: list[str] | None = Field(
        None,
        alias="chargeIds",
        description="The IDs of the charges that should be moved",
    )


class BulkMoveRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    items: list[BulkMoveItemRequest] = Field(
        ..., description="The list of actions to perform"
    )
    reason: str = Field(
        ..., description="Description of why the move is performed", min_length=1
    )


class ReasonCode(StrEnum):
    change_of_recipient_details = "ChangeOfRecipientDetails"
    change_of_invoice_recipient = "ChangeOfInvoiceRecipient"
    change_of_payment_method = "ChangeOfPaymentMethod"
    change_of_invoice_transactions = "ChangeOfInvoiceTransactions"
    other = "Other"


class CancelInvoiceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    reason_code: ReasonCode = Field(
        ...,
        alias="reasonCode",
        description="The code of the reason why the invoice is cancelled.",
    )


class Type(StrEnum):
    direct = "Direct"
    time_slice = "TimeSlice"
    included_service = "IncludedService"
    extra_service = "ExtraService"
    city_tax = "CityTax"
    no_show_fee = "NoShowFee"
    cancellation_fee = "CancellationFee"
    service_fee = "ServiceFee"
    tax = "Tax"
    second_city_tax = "SecondCityTax"


class CommercialInfoModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    register_entry: str = Field(..., alias="registerEntry", min_length=1)
    tax_id: str = Field(..., alias="taxId", min_length=1)
    managing_directors: str | None = Field(None, alias="managingDirectors")


class CorrectFolioRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    reason: str = Field(
        ..., description="Description of why the correction is performed", min_length=1
    )
    charge_ids: list[str] | None = Field(
        None,
        alias="chargeIds",
        description="The IDs of the charges that should be moved",
    )
    allowance_ids: list[str] | None = Field(
        None,
        alias="allowanceIds",
        description="The IDs of the allowances that should be moved\nOnly moving global allowances is supported",
    )
    transitory_charge_ids: list[str] | None = Field(
        None,
        alias="transitoryChargeIds",
        description="The IDs of the transitory charges that should be moved",
    )


class CountModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    count: int


class AccountOwner(StrEnum):
    guest = "Guest"
    booker = "Booker"


class ServiceType2(StrEnum):
    other = "Other"
    accommodation = "Accommodation"
    food_and_beverages = "FoodAndBeverages"
    city_tax = "CityTax"
    second_city_tax = "SecondCityTax"


class ReferenceType1(StrEnum):
    psp_reference = "PspReference"
    authorization_id = "AuthorizationId"


class Method(StrEnum):
    cash = "Cash"
    bank_transfer = "BankTransfer"
    credit_card = "CreditCard"
    amex = "Amex"
    visa_credit = "VisaCredit"
    visa_debit = "VisaDebit"
    master_card = "MasterCard"
    master_card_debit = "MasterCardDebit"
    maestro = "Maestro"
    giro_card = "GiroCard"
    discover_card = "DiscoverCard"
    diners = "Diners"
    jcb = "Jcb"
    booking_com = "BookingCom"
    v_pay = "VPay"
    pay_pal = "PayPal"
    postcard = "Postcard"
    reka = "Reka"
    twint = "Twint"
    lunchcheck = "Lunchcheck"
    voucher = "Voucher"
    china_union_pay = "ChinaUnionPay"
    other = "Other"
    cheque = "Cheque"
    airbnb = "Airbnb"
    holiday_check = "HolidayCheck"
    representation = "Representation"
    i_deal = "IDeal"


class Type1(StrEnum):
    guest = "Guest"
    external = "External"


class CreateInvoiceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    folio_id: str = Field(
        ...,
        alias="folioId",
        description="The ID of the folio for which the invoice should be created.",
    )
    language_code: str = Field(
        ...,
        alias="languageCode",
        description="The language in which the invoice should be produced.",
    )


class Type2(StrEnum):
    invoice_already_exists = "InvoiceAlreadyExists"
    not_all_charges_posted = "NotAllChargesPosted"
    debitor_details_missing = "DebitorDetailsMissing"
    invoice_has_pending_payments = "InvoiceHasPendingPayments"
    no_company_found = "NoCompanyFound"
    company_cannot_check_out_on_ar = "CompanyCannotCheckOutOnAr"
    is_house_folio = "IsHouseFolio"
    cannot_create_company_invoice_for_external = "CannotCreateCompanyInvoiceForExternal"
    check_out_on_ar_is_not_allowed = "CheckOutOnArIsNotAllowed"
    is_empty_folio = "IsEmptyFolio"
    cash_payment_limit_exceeded = "CashPaymentLimitExceeded"
    folio_state = "FolioState"


class CreateInvoiceWarningModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Type2 = Field(
        ...,
        description="The general classification of the warning, why an invoice would not be created if you would try to create it for the current folio.",
    )
    message: str | None = Field(
        None, description="Optionally, additional information about the warning"
    )


class CreateRoutingFilterModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    folio_ids: list[str] | None = Field(
        None, alias="folioIds", description="The folio ids to filter by"
    )
    sub_account_ids: list[str] | None = Field(
        None, alias="subAccountIds", description="The subaccount ids to filter by"
    )
    service_types: list[ServiceType] | None = Field(
        None, alias="serviceTypes", description="The service types to filter by"
    )
    service_ids: list[str] | None = Field(
        None, alias="serviceIds", description="The service ids to filter by"
    )
    from_: date_aliased | None = Field(
        None,
        alias="from",
        description="The start date to filter by",
        examples=["2020-10-10"],
    )
    to: date_aliased | None = Field(
        None, description="The end date to filter by", examples=["2020-10-10"]
    )


class CreateRoutingModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    booking_id: str = Field(..., alias="bookingId", description="The ID of the booking")
    property_id: str = Field(
        ..., alias="propertyId", description="The ID of the property"
    )
    filter: CreateRoutingFilterModel | None = None
    destination_folio_id: str = Field(
        ..., alias="destinationFolioId", description="The ID of the destination folio"
    )


class CreatedSubResourceIdModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str


class CurrencyListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    iso_currencies: list[str] = Field(
        ..., alias="isoCurrencies", description="List of ISO currencies."
    )


class EmbeddedCompanyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The company ID")
    code: str | None = Field(None, description="The code of the company")
    name: str | None = Field(None, description="The name of the company")
    can_check_out_on_ar: bool | None = Field(
        None,
        alias="canCheckOutOnAr",
        description="Whether or not the company can check out on AR",
    )


class EmbeddedFolioModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="Folio ID")
    debitor: str | None = Field(
        None, description="Name of the debitor - the one who will pay the bill"
    )


class EmbeddedInvoiceModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="Invoice id")


class EmbeddedPropertyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The property id")
    code: str | None = Field(
        None,
        description="The code for the property that can be shown in reports and table views",
    )
    name: str | None = Field(None, description="The name for the property")
    description: str | None = Field(
        None, description="The description for the property"
    )


class EmbeddedReservationModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="Reservation id")
    booking_id: str = Field(..., alias="bookingId", description="Booking id")


class Type3(StrEnum):
    revenues = "Revenues"
    payments = "Payments"
    liabilities = "Liabilities"
    receivables = "Receivables"
    vat = "Vat"
    house = "House"
    accounts_receivable = "AccountsReceivable"
    city_taxes = "CityTaxes"
    transitory_items = "TransitoryItems"
    vat_on_liabilities = "VatOnLiabilities"
    loss_of_accounts_receivable = "LossOfAccountsReceivable"
    second_city_tax = "SecondCityTax"


class ExportAccountModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    name: str = Field(..., description="The account name", min_length=1)
    number: str = Field(..., description="The account number", min_length=1)
    parent_number: str | None = Field(
        None, alias="parentNumber", description="The number of the parent account"
    )
    type: Type3 = Field(..., description="The account type")


class ExternalReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    merchant_reference: str = Field(
        ...,
        alias="merchantReference",
        description="The merchant reference ('order number')",
        min_length=1,
    )
    psp_reference: str = Field(
        ...,
        alias="pspReference",
        description="The globally unique identifier of this payment in the reports of the payment service",
        min_length=1,
    )


class FolioCreatedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The folio id")


class Type5(StrEnum):
    booker = "Booker"
    primary_guest = "PrimaryGuest"
    company = "Company"
    additional_guest = "AdditionalGuest"
    property = "Property"


class Title(StrEnum):
    mr = "Mr"
    ms = "Ms"
    dr = "Dr"
    prof = "Prof"
    mrs = "Mrs"
    other = "Other"


class FolioWarning(StrEnum):
    incomplete_billing_address = "IncompleteBillingAddress"
    incomplete_billing_details = "IncompleteBillingDetails"


class AllowedAction(StrEnum):
    add_charge = "AddCharge"
    add_deposit_item = "AddDepositItem"
    add_allowance = "AddAllowance"
    add_cancellation_fee = "AddCancellationFee"
    add_no_show_fee = "AddNoShowFee"
    add_payment = "AddPayment"
    add_refund = "AddRefund"
    checkout_on_ar = "CheckoutOnAr"
    close = "Close"
    post_open_charges = "PostOpenCharges"
    correct_folio = "CorrectFolio"
    change_address = "ChangeAddress"
    change_address_with_simple_debitor = "ChangeAddressWithSimpleDebitor"
    delete = "Delete"
    reopen = "Reopen"
    create_invoice = "CreateInvoice"
    create_advance_invoice = "CreateAdvanceInvoice"
    cancel_last_invoice = "CancelLastInvoice"
    create_invoice_with_simple_debitor = "CreateInvoiceWithSimpleDebitor"
    create_prepayment_notice = "CreatePrepaymentNotice"
    create_pro_forma_invoice = "CreateProFormaInvoice"
    create_deposit_receipt = "CreateDepositReceipt"
    preview_invoice = "PreviewInvoice"


class Status(StrEnum):
    open = "Open"
    closed = "Closed"
    closed_with_invoice = "ClosedWithInvoice"


class Method2(StrEnum):
    cash = "Cash"
    bank_transfer = "BankTransfer"
    credit_card = "CreditCard"
    invoice = "Invoice"
    amex = "Amex"
    visa_credit = "VisaCredit"
    visa_debit = "VisaDebit"
    master_card = "MasterCard"
    master_card_debit = "MasterCardDebit"
    maestro = "Maestro"
    giro_card = "GiroCard"
    discover_card = "DiscoverCard"
    diners = "Diners"
    jcb = "Jcb"
    booking_com = "BookingCom"
    v_pay = "VPay"
    pay_pal = "PayPal"
    postcard = "Postcard"
    reka = "Reka"
    twint = "Twint"
    lunchcheck = "Lunchcheck"
    voucher = "Voucher"
    china_union_pay = "ChinaUnionPay"
    other = "Other"
    cheque = "Cheque"
    airbnb = "Airbnb"
    holiday_check = "HolidayCheck"
    psp_cash = "PspCash"
    psp_debit = "PspDebit"
    psp_banking = "PspBanking"
    psp_open_invoice = "PspOpenInvoice"
    psp_wallet = "PspWallet"
    representation = "Representation"
    i_deal = "IDeal"


class Status2(StrEnum):
    pending = "Pending"
    success = "Success"
    failure = "Failure"
    canceled = "Canceled"


class FailureCode(StrEnum):
    failed = "Failed"
    timed_out = "TimedOut"


class Type8(StrEnum):
    custom = "Custom"
    terminal = "Terminal"
    payment_account = "PaymentAccount"
    authorization = "Authorization"
    payment_link = "PaymentLink"
    pre_authorization = "PreAuthorization"


class InvoiceCreatedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The invoice id")


class Type9(StrEnum):
    initial = "Initial"
    cancellation = "Cancellation"
    correction = "Correction"
    advance = "Advance"
    advance_cancellation = "AdvanceCancellation"
    advance_correction = "AdvanceCorrection"
    proforma = "Proforma"


class Status3(StrEnum):
    fully_paid = "FullyPaid"
    unpaid = "Unpaid"
    written_off = "WrittenOff"


class AllowedAction2(StrEnum):
    correct_address = "CorrectAddress"
    correct_charges = "CorrectCharges"
    mark_as_paid = "MarkAsPaid"
    cancel = "Cancel"
    write_off = "WriteOff"


class Network(StrEnum):
    peppol = "Peppol"


class InvoiceNetworkIdentityModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    network: Network = Field(
        ..., description="The Network through which to send the Invoice\ne. g. Peppol"
    )
    id: str = Field(
        ...,
        description='The Id of the company at the network.\ne.g. "0208:123456789"',
        min_length=1,
    )


class InvoiceSenderModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    name: str = Field(..., min_length=1)
    address: AddressModel | None = None


class MessageItemCollection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    messages: list[str] | None = None


class MonetaryValueModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    amount: float
    currency: str


class MoveAllChargesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    target_folio_id: str = Field(
        ..., alias="targetFolioId", description="ID of the target folio"
    )
    reason: str = Field(
        ..., description="Description of why the move is performed", min_length=1
    )


class MoveChargesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    target_folio_id: str = Field(
        ..., alias="targetFolioId", description="ID of the target folio"
    )
    reason: str = Field(
        ..., description="Description of why the move is performed", min_length=1
    )
    charge_ids: list[str] | None = Field(
        None,
        alias="chargeIds",
        description="The IDs of the charges that should be moved",
    )
    allowance_ids: list[str] | None = Field(
        None,
        alias="allowanceIds",
        description="The IDs of the allowances that should be moved.\nOnly moving global allowances is supported",
    )
    transitory_charge_ids: list[str] | None = Field(
        None,
        alias="transitoryChargeIds",
        description="The IDs of the transitory charges that should be moved",
    )


class MovePaymentsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    target_folio_id: str = Field(
        ..., alias="targetFolioId", description="ID of the target folio"
    )
    reason: str = Field(
        ..., description="Description of why the move is performed", min_length=1
    )
    payment_ids: list[str] = Field(
        ...,
        alias="paymentIds",
        description="The IDs of the payments that should be moved",
    )


class NonStrictAddressModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    address_line1: str | None = Field(None, alias="addressLine1")
    address_line2: str | None = Field(None, alias="addressLine2")
    postal_code: str | None = Field(None, alias="postalCode")
    city: str | None = None
    region_code: str | None = Field(None, alias="regionCode")
    country_code: str | None = Field(None, alias="countryCode")


class Operation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    value: Any | None = None
    path: str | None = None
    op: str | None = None
    from_: str | None = Field(None, alias="from")


class PayInvoiceRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    payment_method: Method = Field(
        ...,
        alias="paymentMethod",
        description="The payment method used for paying the invoice. Used for accounting.",
    )
    receipt: str = Field(
        ...,
        description="The receipt for the payment. Each transaction in accounting has a receipt set.",
        min_length=1,
    )


class PaymentCreatedModel(CreatedSubResourceIdModel):
    pass


class PaymentMethodListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    payment_methods: list[Method] = Field(
        ..., alias="paymentMethods", description="List of supported payment methods."
    )


class PaymentModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(
        ..., description="Id of the payment. This is unique within one folio."
    )
    method: Method2 = Field(..., description="The Payment Method.")
    amount: MonetaryValueModel
    external_reference: ExternalReference | None = Field(
        None, alias="externalReference"
    )
    receipt: str | None = Field(
        None,
        description="Receipt for the payment. For payments done by the payment service provider integration, this is the same as the pspReference.",
    )
    payment_date: AwareDatetime | None = Field(
        None,
        alias="paymentDate",
        description='The date when the payment was done<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    moved_from: EmbeddedFolioModel | None = Field(None, alias="movedFrom")
    moved_to: EmbeddedFolioModel | None = Field(None, alias="movedTo")
    moved_reason: str | None = Field(
        None,
        alias="movedReason",
        description="A reason why move operation was performed",
    )
    source_payment_id: str | None = Field(
        None,
        alias="sourcePaymentId",
        description="A link to the original payment in case of splitting payments",
    )
    business_date: date_aliased = Field(
        ...,
        alias="businessDate",
        description="The business date of the payment",
        examples=["2020-10-10"],
    )


class PaymentPaidChargesRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    charge_id: str = Field(
        ..., alias="chargeId", description="The ID of the charge being paid"
    )
    amount: float = Field(
        ...,
        description="The amount being covered with the payment. If not provided it is assumed that the payment is covering the full amount of the charge",
    )


class PendingPaymentModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="Id of the payment task.")
    amount: MonetaryValueModel
    terminal_id: str | None = Field(
        None, alias="terminalId", description="The terminal used for the payment."
    )


class PreciseMonetaryValueModel(MonetaryValueModel):
    pass


class CreateInvoiceAction(StrEnum):
    cannot_create_invoice = "CannotCreateInvoice"
    creates_invoice = "CreatesInvoice"
    creates_invoice_and_closes_folio = "CreatesInvoiceAndClosesFolio"
    creates_ar_invoice_and_closes_folio = "CreatesArInvoiceAndClosesFolio"


class Type11(StrEnum):
    custom = "Custom"
    reservation = "Reservation"
    invoice = "Invoice"
    psp_reference = "PspReference"


class ReceiptModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Type11 | None = Field(None, description="The type of receipt.")
    number: str = Field(..., description="The receipt number.", min_length=1)


class RefundCreatedModel(CreatedSubResourceIdModel):
    pass


class RefundModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="Id of the refund")
    method: Method2 = Field(..., description="The payment method")
    amount: MonetaryValueModel
    external_reference: ExternalReference | None = Field(
        None, alias="externalReference"
    )
    receipt: str | None = Field(
        None,
        description="Receipt for the payment. For payments run through the apaleo payment services it is set to the pspReference",
    )
    refund_date: AwareDatetime = Field(
        ...,
        alias="refundDate",
        description='The date when the refund was done<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    source_payment_id: str | None = Field(
        None,
        alias="sourcePaymentId",
        description="A link to the payment that the refund was done for",
    )
    status: Status2 = Field(..., description="Status of the refund")
    failure_reason: str | None = Field(None, alias="failureReason")
    failure_code: FailureCode | None = Field(None, alias="failureCode")
    moved_from: EmbeddedFolioModel | None = Field(None, alias="movedFrom")
    moved_to: EmbeddedFolioModel | None = Field(None, alias="movedTo")
    moved_reason: str | None = Field(
        None,
        alias="movedReason",
        description="A reason why the move operation was performed",
    )
    business_date: date_aliased = Field(
        ...,
        alias="businessDate",
        description="The business date of the refund",
        examples=["2020-10-10"],
    )
    reason: str | None = Field(None, description="The reason for payment refund")


class RoutingCreatedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The ID of the routing")


class RoutingFolioModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The ID of the folio")
    debitor_type: Type5 | None = Field(
        None, alias="debitorType", description="The debitor type of the folio"
    )


class RoutingServiceModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The ID of the service")
    name: str = Field(..., description="The name of the service", min_length=1)


class RoutingSubAccountModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The ID of the subaccount")
    name: str = Field(..., description="The name of the subaccount", min_length=1)


class ServiceTypeListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    service_types: list[ServiceType] = Field(
        ..., alias="serviceTypes", description="List of supported payment methods."
    )


class Type13(StrEnum):
    by_percent = "ByPercent"
    by_amount = "ByAmount"


class SplitChargeRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    percent: float | None = Field(
        None, description="The percent to split charge (between 0 and 100)"
    )
    amount: MonetaryValueModel | None = None
    type: Type13 = Field(
        ...,
        description="How to split the charge: by percent value, or by absolute amount",
    )


class SplitChargeResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    allowance_id: str = Field(..., alias="allowanceId")
    first_charge_id: str = Field(..., alias="firstChargeId")
    second_charge_id: str = Field(..., alias="secondChargeId")


class SplitPaymentRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    percent: float | None = Field(
        None, description="The percent to split payment (between 0 and 100)"
    )
    amount: MonetaryValueModel | None = None
    type: Type13 = Field(
        ...,
        description="How to split the payment: by percent value, or by absolute amount",
    )


class SplitPaymentResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    refund_id: str | None = Field(None, alias="refundId")
    first_payment_id: str | None = Field(None, alias="firstPaymentId")
    second_payment_id: str | None = Field(None, alias="secondPaymentId")


class StayInfoModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    guest_name: str = Field(
        ..., alias="guestName", description="Name of the primary guest", min_length=1
    )
    arrival_date: date_aliased = Field(
        ...,
        alias="arrivalDate",
        description="The arrival date",
        examples=["2020-10-10"],
    )
    departure_date: date_aliased = Field(
        ...,
        alias="departureDate",
        description="The departure date",
        examples=["2020-10-10"],
    )
    reservation_id: str = Field(
        ...,
        alias="reservationId",
        description="ID of the reservation this invoice is for, if any.",
        min_length=1,
    )
    room_number: str | None = Field(
        None, alias="roomNumber", description="The last room number"
    )


class TaxAmountModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: VatType = Field(..., description="The VAT type")
    percent: float = Field(
        ..., description="The currently valid percent to calculate the VAT"
    )
    amount: float = Field(..., description="The tax amount")


class TaxDetailModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    vat_type: VatType = Field(..., alias="vatType")
    vat_percent: float = Field(..., alias="vatPercent")
    net: MonetaryValueModel
    tax: MonetaryValueModel


class TransitoryChargeModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(
        ..., description="ID for transitory charge. This is unique within one folio."
    )
    name: str = Field(
        ...,
        description="The name, article number, or other description of this item",
        min_length=1,
    )
    amount: MonetaryValueModel
    service_type: ServiceType | None = Field(
        None,
        alias="serviceType",
        description="The service type of this transitory charge. As revenue and VAT of transitory charges are not recorded for the hotel, this is just FYI.",
    )
    service_date: date_aliased = Field(
        ...,
        alias="serviceDate",
        description="The date when this charge was added.",
        examples=["2020-10-10"],
    )
    created: AwareDatetime = Field(
        ...,
        description='Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    receipt: str | None = Field(None, description="Receipt for this transaction")
    moved_from: EmbeddedFolioModel | None = Field(None, alias="movedFrom")
    moved_to: EmbeddedFolioModel | None = Field(None, alias="movedTo")
    moved_reason: str | None = Field(
        None,
        alias="movedReason",
        description="A reason why move operation was performed",
    )
    quantity: int = Field(..., description="The count of services provided")


class VatItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: VatType = Field(..., description="The VAT type")
    percent: float = Field(
        ..., description="The currently valid percent to calculate the VAT"
    )


class VatListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    vat_types: list[VatItemModel] | None = Field(None, alias="vatTypes")


class Action(StrEnum):
    cancel = "Cancel"
    online_refund = "OnlineRefund"
    manual_refund = "ManualRefund"


class Action1(StrEnum):
    delete = "Delete"
    modify = "Modify"


class Code(StrEnum):
    cancel_not_allowed_for_payment_not_in_status_pending = (
        "CancelNotAllowedForPaymentNotInStatusPending"
    )
    cancel_not_allowed_for_payment_not_of_payment_link_type = (
        "CancelNotAllowedForPaymentNotOfPaymentLinkType"
    )
    online_refund_not_allowed_for_restricted_payment_method_or_acquirer = (
        "OnlineRefundNotAllowedForRestrictedPaymentMethodOrAcquirer"
    )
    manual_refund_not_allowed_when_online_refund_is_possible = (
        "ManualRefundNotAllowedWhenOnlineRefundIsPossible"
    )
    cancel_not_allowed_for_incomplete_payment_link = (
        "CancelNotAllowedForIncompletePaymentLink"
    )


class ActionReasonModelNotAllowedPaymentActionReason(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    code: Code
    message: str = Field(..., min_length=1)


class Code1(StrEnum):
    delete_not_allowed_for_destination_folio_closed = (
        "DeleteNotAllowedForDestinationFolioClosed"
    )
    delete_not_allowed_for_destination_folio_with_advance_invoice = (
        "DeleteNotAllowedForDestinationFolioWithAdvanceInvoice"
    )
    delete_not_allowed_for_destination_folio_with_moved_out_routed_charges = (
        "DeleteNotAllowedForDestinationFolioWithMovedOutRoutedCharges"
    )
    delete_not_allowed_for_source_folios_closed = (
        "DeleteNotAllowedForSourceFoliosClosed"
    )
    delete_not_allowed_for_source_folios_with_advance_invoice = (
        "DeleteNotAllowedForSourceFoliosWithAdvanceInvoice"
    )
    modify_not_allowed_for_destination_folio_closed = (
        "ModifyNotAllowedForDestinationFolioClosed"
    )
    modify_not_allowed_for_destination_folio_with_advance_invoice = (
        "ModifyNotAllowedForDestinationFolioWithAdvanceInvoice"
    )
    modify_not_allowed_for_source_folios_with_advance_invoice = (
        "ModifyNotAllowedForSourceFoliosWithAdvanceInvoice"
    )
    modify_not_allowed_for_destination_folio_with_moved_out_routed_charges = (
        "ModifyNotAllowedForDestinationFolioWithMovedOutRoutedCharges"
    )
    delete_not_allowed_for_source_folios_with_pending_invoice = (
        "DeleteNotAllowedForSourceFoliosWithPendingInvoice"
    )
    delete_not_allowed_for_destination_folio_with_pending_invoice = (
        "DeleteNotAllowedForDestinationFolioWithPendingInvoice"
    )
    modify_not_allowed_for_source_folios_with_pending_invoice = (
        "ModifyNotAllowedForSourceFoliosWithPendingInvoice"
    )
    modify_not_allowed_for_destination_folio_with_pending_invoice = (
        "ModifyNotAllowedForDestinationFolioWithPendingInvoice"
    )


class ActionReasonModelNotAllowedRoutingActionReason(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    code: Code1
    message: str = Field(..., min_length=1)


class AccountingTransactionModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    timestamp: AwareDatetime = Field(
        ...,
        description='Timestamp with time zone information, when the booking was done<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    date: date_aliased = Field(
        ...,
        description="The business date when the booking was done",
        examples=["2020-10-10"],
    )
    debited_account: ExportAccountModel = Field(..., alias="debitedAccount")
    credited_account: ExportAccountModel = Field(..., alias="creditedAccount")
    command: Command = Field(
        ..., description="The type of business transaction which triggered the booking"
    )
    amount: PreciseMonetaryValueModel
    receipt: ReceiptModel | None = None
    entry_number: str = Field(
        ...,
        alias="entryNumber",
        description="All transactions having the same number form one booking",
        min_length=1,
    )
    reference: str = Field(
        ...,
        description="The reference for the transactions, reservation id for guest folios, folio id for external folios, property code for the house folio",
    )
    reference_type: ReferenceType = Field(
        ...,
        alias="referenceType",
        description="Does this transaction belong to a reservation, a house or an external folio",
    )
    entry_group_number: str = Field(
        ...,
        alias="entryGroupNumber",
        description="All transactions triggered by the same business transaction share one group number",
        min_length=1,
    )


class AccountingTransactionPairModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    debited_account: ExportAccountModel = Field(..., alias="debitedAccount")
    credited_account: ExportAccountModel = Field(..., alias="creditedAccount")
    amount: PreciseMonetaryValueModel


class AggregateTransactionItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    account: ExportAccountModel
    credited_amount: PreciseMonetaryValueModel = Field(..., alias="creditedAmount")
    debited_amount: PreciseMonetaryValueModel = Field(..., alias="debitedAmount")
    balance: PreciseMonetaryValueModel


class AggregatesTotalModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    credited_amount: PreciseMonetaryValueModel = Field(..., alias="creditedAmount")
    debited_amount: PreciseMonetaryValueModel = Field(..., alias="debitedAmount")
    balance: PreciseMonetaryValueModel


class AllowanceModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(
        ..., description="ID for allowances. This is unique within one folio."
    )
    amount: AmountModel
    reason: str = Field(
        ..., description="Reason why this allowance was posted", min_length=1
    )
    service_type: ServiceType = Field(..., alias="serviceType")
    service_date: date_aliased = Field(
        ..., alias="serviceDate", examples=["2020-10-10"]
    )
    created: AwareDatetime = Field(
        ...,
        description='Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    moved_from: EmbeddedFolioModel | None = Field(None, alias="movedFrom")
    moved_to: EmbeddedFolioModel | None = Field(None, alias="movedTo")
    moved_reason: str | None = Field(
        None,
        alias="movedReason",
        description="A reason why move operation was performed",
    )
    source_charge_id: str | None = Field(
        None,
        alias="sourceChargeId",
        description="ID of a charge allowance posted for. `Null` if posted for folio",
    )
    sub_account_id: str | None = Field(
        None,
        alias="subAccountId",
        description="ID of the custom sub-account the allowance has been posted to",
    )


class ChargeModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="ID for charges. This is unique within one folio.")
    service_type: ServiceType = Field(
        ..., alias="serviceType", description="The type of the service or good"
    )
    name: str = Field(
        ...,
        description="The name, article number, or other description of this charge",
        min_length=1,
    )
    translated_names: dict[str, str] | None = Field(
        None,
        alias="translatedNames",
        description="The name, article number, or other description of this charge\ntranslated in different languages",
    )
    is_posted: bool = Field(
        ..., alias="isPosted", description="Status: is this already posted?"
    )
    service_date: date_aliased = Field(
        ...,
        alias="serviceDate",
        description="The day when the line item is (or was) due to be charged.",
        examples=["2020-10-10"],
    )
    created: AwareDatetime = Field(
        ...,
        description='Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    moved_from: EmbeddedFolioModel | None = Field(None, alias="movedFrom")
    moved_to: EmbeddedFolioModel | None = Field(None, alias="movedTo")
    moved_reason: str | None = Field(
        None,
        alias="movedReason",
        description="A reason why move operation was performed",
    )
    routed_from: EmbeddedFolioModel | None = Field(None, alias="routedFrom")
    routed_to: EmbeddedFolioModel | None = Field(None, alias="routedTo")
    amount: AmountModel
    receipt: str | None = Field(None, description="Receipt for this transaction")
    group_id: str | None = Field(
        None,
        alias="groupId",
        description="Identifier used for grouping related charges together",
    )
    sub_account_id: str | None = Field(
        None,
        alias="subAccountId",
        description="ID of the custom sub-account the charge has been posted to",
    )
    quantity: int = Field(..., description="The count of services provided")
    type: Type = Field(..., description="The type of the charge")


class CompanyInfoModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    name: str = Field(..., description="Name of the company", min_length=1)
    tax_id: str | None = Field(
        None, alias="taxId", description="Tax or Vat ID of the company"
    )
    additional_tax_id: str | None = Field(
        None,
        alias="additionalTaxId",
        description="The additional tax ID of the company (e.g. SIRET in France, Codice Destinatario in Italy, SST in Malaysia)",
    )
    additional_tax_id2: str | None = Field(
        None,
        alias="additionalTaxId2",
        description="The additional tax ID of the company (e.g. Codice Fiscale in Italy, BRN in Malaysia)",
    )
    invoice_network_identity: InvoiceNetworkIdentityModel | None = Field(
        None, alias="invoiceNetworkIdentity"
    )


class CreateAccountPaymentRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    account_owner: AccountOwner | None = Field(
        None,
        alias="accountOwner",
        description="Account owner of the payment account, default is `Guest`.\nWill be ignored if PaymentAccountId is provided - <b>DEPRECATED: AccountOwner is deprecated, use PaymentAccountId instead. This field will be removed on May 15, 2026. From this date onwards, PaymentAccountId will be a required parameter.</b>",
    )
    payment_account_id: str | None = Field(
        None,
        alias="paymentAccountId",
        description="Optional payment account id.\nIf passed, it is verified that the provided payment account is available for the folio.\nFrom Feb 15, 2026 onwards, PaymentAccountId will be a required parameter.",
    )
    amount: MonetaryValueModel
    paid_charges: list[PaymentPaidChargesRequest] | None = Field(
        None,
        alias="paidCharges",
        description="List of charges and amount being covered by this payment.",
    )


class CreateAllowanceBulkItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    charge_id: str = Field(..., alias="chargeId", description="The ID of the charge")
    amount: MonetaryValueModel


class CreateAllowanceBulkModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    items: list[CreateAllowanceBulkItemModel] = Field(
        ..., description="The list of actions to perform"
    )
    reason: str = Field(
        ..., description="Description of why allowances are added", min_length=1
    )
    business_date: date_aliased | None = Field(
        None,
        alias="businessDate",
        description="The business date of the allowance. Defaults to the current date.\nIn some cases you might want to post the allowances to the previous business date, this is only possible until 6 AM of the current day.",
        examples=["2020-10-10"],
    )


class CreateAllowanceForChargeModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    reason: str = Field(
        ..., description="Reason why this allowance is posted", min_length=1
    )
    amount: MonetaryValueModel
    business_date: date_aliased | None = Field(
        None,
        alias="businessDate",
        description="The business date of the allowance. Defaults to the current date.\nIn some cases you might want to post the allowances to the previous business date, this is only possible until 6 AM of the current day.",
        examples=["2020-10-10"],
    )


class CreateAllowanceForFolioModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    service_type: ServiceType2 = Field(
        ...,
        alias="serviceType",
        description="The service type, used by accounting to determine the correct revenue account",
    )
    vat_type: VatType = Field(
        ...,
        alias="vatType",
        description="The VAT type, used by accounting to determine the correct vat amount and account",
    )
    sub_account_id: str | None = Field(
        None,
        alias="subAccountId",
        description="ID of the custom sub-account to post the allowance to, used by accounting to determine the correct revenue account",
    )
    reason: str = Field(
        ..., description="Reason why this allowance is posted", min_length=1
    )
    amount: MonetaryValueModel
    business_date: date_aliased | None = Field(
        None,
        alias="businessDate",
        description="The business date of the allowance. Defaults to the current date.\nIn some cases you might want to post the allowances to the previous business date, this is only possible until 6 AM of the current day.",
        examples=["2020-10-10"],
    )


class CreateAuthorizationPaymentRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    transaction_reference: str = Field(
        ...,
        alias="transactionReference",
        description="Reference to the original authorization transaction",
        min_length=1,
    )
    reference_type: ReferenceType1 | None = Field(
        None,
        alias="referenceType",
        description="Type of TransactionReference used, default is PspReference\nWhen capturing a Consumption or Damage authorization, use AuthorizationId",
    )
    amount: MonetaryValueModel
    paid_charges: list[PaymentPaidChargesRequest] | None = Field(
        None,
        alias="paidCharges",
        description="List of charges and amount being covered by this payment.",
    )


class CreateChargeModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    service_type: ServiceType2 = Field(
        ...,
        alias="serviceType",
        description="The service type, used by accounting to determine the correct revenue account",
    )
    vat_type: VatType = Field(
        ...,
        alias="vatType",
        description="The VAT type, used by accounting to determine the correct vat amount and account",
    )
    sub_account_id: str | None = Field(
        None,
        alias="subAccountId",
        description="ID of the custom sub-account to post the charge to, used by accounting to determine the correct revenue account",
    )
    name: str = Field(
        ...,
        description="The name, article number, or other description of this charge",
        min_length=1,
    )
    amount: MonetaryValueModel
    receipt: str | None = Field(None, description="Receipt for this transaction")
    quantity: int | None = Field(
        None,
        description="The count of services provided. Defaults to 1.\nNOTE: this field will become required 07.05.2020.",
    )
    business_date: date_aliased | None = Field(
        None,
        alias="businessDate",
        description="The business date of the charge. Defaults to the current date.\nIn some cases you might want to post the charges to the previous business date, this is only possible until 6 AM of the current day.",
        examples=["2020-10-10"],
    )


class CreateCustomPaymentRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    method: Method = Field(
        ...,
        description="The payment method. Use 'CreditCard', if none of the specific credit cards types matches. 'Booking.com' only makes sense, if\nthe property (hotel) configured Booking.com > Finance to be 'Payments by Booking.com'",
    )
    receipt: str | None = Field(
        None,
        description="The optional receipt you want to store for the payment. It defaults to the reservation or external folio id.\nThis field is required if you are adding payment to the house account",
    )
    business_date: date_aliased | None = Field(
        None,
        alias="businessDate",
        description="The business date of the payment. Defaults to the current date.\nIn some cases you might want to post the payments to the previous business date, this is only possible until 6 AM of the current day.",
        examples=["2020-10-10"],
    )
    amount: MonetaryValueModel
    paid_charges: list[PaymentPaidChargesRequest] | None = Field(
        None,
        alias="paidCharges",
        description="List of charges and amount being covered by this payment.",
    )


class CreateFolioRefundRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    method: Method = Field(
        ..., description="The payment method the refund will be accounted to"
    )
    amount: MonetaryValueModel
    receipt: str | None = Field(None, description="The receipt for the refund")
    business_date: date_aliased | None = Field(
        None,
        alias="businessDate",
        description="The business date of the refund. Defaults to the current date.\nIn some cases you might want to post the refunds to the previous business date, this is only possible until 6 AM of the current day.",
        examples=["2020-10-10"],
    )
    reason: str | None = Field(None, description="The reason for payment refund")


class CreatePaymentLinkRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    expires_at: AwareDatetime = Field(
        ...,
        alias="expiresAt",
        description='The date that the link expires<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    country_code: str = Field(
        ...,
        alias="countryCode",
        description="The payer's country code. Used to provide suitable for the payer payment methods and use default country language",
        min_length=1,
    )
    description: str | None = Field(
        None,
        description="Payment description. It will be shown on the payment form of the link",
        max_length=280,
    )
    payer_email: EmailStr | None = Field(
        None,
        alias="payerEmail",
        description="The email address of the payer or cardholder. It can be used to verify the identity of the payer and\nallow to catch a fraudulent usage of the payment account if the email address does not match the one\non file at the bank",
    )
    amount: MonetaryValueModel
    paid_charges: list[PaymentPaidChargesRequest] | None = Field(
        None,
        alias="paidCharges",
        description="List of charges and amount being covered by this payment.",
    )


class CreatePaymentRefundRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    amount: MonetaryValueModel
    business_date: date_aliased | None = Field(
        None,
        alias="businessDate",
        description="The business date of the refund. Defaults to the current date.\nIn some cases you might want to post the refunds to the previous business date, this is only possible until 6 AM of the current day.",
        examples=["2020-10-10"],
    )
    reason: str | None = Field(None, description="The reason for payment refund")


class CreateTerminalPaymentRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    terminal_id: str = Field(
        ...,
        alias="terminalId",
        description="Terminal to be used for the payment",
        min_length=1,
    )
    amount: MonetaryValueModel
    paid_charges: list[PaymentPaidChargesRequest] | None = Field(
        None,
        alias="paidCharges",
        description="List of charges and amount being covered by this payment.",
    )


class CreateTransitoryChargeModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    name: str = Field(
        ...,
        description="The name, article number, or other description of this item",
        min_length=1,
    )
    amount: MonetaryValueModel
    receipt: str | None = Field(None, description="Receipt for this transaction")
    group_id: str | None = Field(
        None,
        alias="groupId",
        description="Identifier used for grouping related charges together",
    )
    service_type: ServiceType2 | None = Field(
        None,
        alias="serviceType",
        description="The service type. This is not used by accounting, but can be entered and stored on the charge.",
    )
    quantity: int | None = Field(
        None,
        description="The count of services provided. Defaults to 1.\nNOTE: this field will become required 07.05.2020.",
    )
    business_date: date_aliased | None = Field(
        None,
        alias="businessDate",
        description="The business date of the charge. Defaults to the current date.\nIn some cases you might want to post the charges to the previous business date, this is only possible until 6 AM of the current day.",
        examples=["2020-10-10"],
    )


class ExportGrossTransactionItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    timestamp: AwareDatetime = Field(
        ...,
        description='Timestamp with time zone information, when the booking was done<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    date: date_aliased = Field(
        ...,
        description="The business date when the booking was done",
        examples=["2020-10-10"],
    )
    debited_account: ExportAccountModel = Field(..., alias="debitedAccount")
    credited_account: ExportAccountModel = Field(..., alias="creditedAccount")
    command: Command = Field(
        ..., description="The type of business transaction which triggered the booking"
    )
    currency: str = Field(..., description="The currency of the transaction")
    gross_amount: float = Field(
        ..., alias="grossAmount", description="The gross amount being booked"
    )
    net_amount: float = Field(
        ..., alias="netAmount", description="The net amount being booked"
    )
    taxes: list[TaxAmountModel] | None = Field(
        None,
        description="The taxes which make up the difference between net and gross amount",
    )
    receipt: ReceiptModel
    source_entry_number: str = Field(
        ...,
        alias="sourceEntryNumber",
        description="The original raw transaction entry number which got converted to these one or 2 lines.",
        min_length=1,
    )
    reference: str = Field(
        ...,
        description="The reference for the transactions, reservation id for guest folios, booking id for booking folio, folio id for external folios, property code for the house folio",
    )
    reference_type: ReferenceType = Field(
        ...,
        alias="referenceType",
        description="Does this transaction belong to a reservation, a house or an external folio",
    )


class ExportGrossTransactionListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    transactions: list[ExportGrossTransactionItemModel] = Field(
        ..., description="List of transactions with all details."
    )


class FinanceAccountModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    account_number: str = Field(
        ...,
        alias="accountNumber",
        description="The account number. Unique identifier within one property.",
        min_length=1,
    )
    name: str = Field(..., description="The name of the account.", min_length=1)
    type: Type3 = Field(..., description="The type of account.")
    has_children: bool = Field(
        ...,
        alias="hasChildren",
        description="Indicates whether this account has children / sub accounts or not. The children can be retrieved via GET /accounts and querying\nby parent.",
    )
    parent_number: str | None = Field(
        None,
        alias="parentNumber",
        description="Parent account number. Null for top-level accounts.",
    )
    is_archived: bool = Field(
        ...,
        alias="isArchived",
        description="Indicates whether this account is archived ot not.",
    )
    transactions: list[AccountingTransactionModel] | None = Field(
        None, description="All transactions / bookings involving this account."
    )


class FolioDebitorModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Type5 | None = Field(
        None,
        description="Whether the debitor is the booker, the primary guest, an additional guest, or the company.\nWhen the folio has a company, the only possible value is 'Company'. 'Property' is a reserved type for the house folio.",
    )
    title: Title | None = Field(None, description="Title")
    first_name: str | None = Field(None, alias="firstName", description="First name")
    name: str | None = Field(None, description="Last name")
    address: NonStrictAddressModel | None = None
    company: CompanyInfoModel | None = None
    personal_tax_id: str | None = Field(
        None,
        alias="personalTaxId",
        description="Debitor's Tax Id if debitor is a person",
    )
    reference: str | None = Field(
        None,
        description="Any additional information about the debitor that should be present on the invoice",
        max_length=80,
    )
    email: str | None = Field(None, description="Debitor's email")
    phone: str | None = Field(None, description="Debitor's phone")


class FolioItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The id of the folio")
    created: AwareDatetime = Field(
        ...,
        description='Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    updated: AwareDatetime = Field(
        ...,
        description='Date of update<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    type: ReferenceType | None = Field(None, description="The folio type")
    debitor: FolioDebitorModel | None = None
    closing_date: date_aliased | None = Field(
        None,
        alias="closingDate",
        description="The date when the folio has been closed",
        examples=["2020-10-10"],
    )
    is_main_folio: bool | None = Field(
        None,
        alias="isMainFolio",
        description="Set to `true` if this is the main folio for the reservation",
    )
    is_empty: bool | None = Field(
        None,
        alias="isEmpty",
        description="Set to `true` if the folio has no unmoved [transitory] charges, unmoved payments, and allowances.",
    )
    reservation: EmbeddedReservationModel | None = None
    booking_id: str | None = Field(
        None,
        alias="bookingId",
        description="The id of the booking linked to this folio",
    )
    company: EmbeddedCompanyModel | None = None
    balance: MonetaryValueModel
    checked_out_on_accounts_receivable: bool | None = Field(
        None,
        alias="checkedOutOnAccountsReceivable",
        description="Set to true, if the folio has been checked out on accounts receivable",
    )
    folio_warnings: list[FolioWarning] | None = Field(
        None,
        alias="folioWarnings",
        description="Depending on the state of the folio, certain warnings are shown.\nThis list includes all folio warnings.",
    )
    allowed_actions: list[AllowedAction] | None = Field(
        None,
        alias="allowedActions",
        description="Depending on the state of the folio, certain actions are allowed or not.\nThis list includes all actions you can perform on this folio.",
    )
    related_invoices: list[EmbeddedInvoiceModel] | None = Field(
        None,
        alias="relatedInvoices",
        description="All invoices that have been created for this folio. This is only set on folios of type 'guest'",
    )
    status: Status = Field(..., description="Status of the folio")
    charges: list[ChargeModel] | None = Field(None, description="The list of charges")
    allowances: list[AllowanceModel] | None = Field(
        None, description="The list of allowances"
    )
    transitory_charges: list[TransitoryChargeModel] | None = Field(
        None, alias="transitoryCharges", description="The list of transitory charges"
    )
    payments: list[PaymentModel] | None = Field(
        None, description="The list of payments"
    )


class FolioListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    folios: list[FolioItemModel] = Field(..., description="List of folios.")
    count: int = Field(..., description="Total count of items")


class FolioModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The id of the folio")
    created: AwareDatetime = Field(
        ...,
        description='Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    updated: AwareDatetime = Field(
        ...,
        description='Date of update<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    type: ReferenceType | None = Field(None, description="The folio type")
    debitor: FolioDebitorModel | None = None
    closing_date: date_aliased | None = Field(
        None,
        alias="closingDate",
        description="The date when the folio has been closed",
        examples=["2020-10-10"],
    )
    reservation: EmbeddedReservationModel | None = None
    booking_id: str | None = Field(
        None,
        alias="bookingId",
        description="The id of the booking linked to this folio",
    )
    company: EmbeddedCompanyModel | None = None
    property: EmbeddedPropertyModel
    charges: list[ChargeModel] | None = Field(None, description="The list of charges")
    transitory_charges: list[TransitoryChargeModel] | None = Field(
        None, alias="transitoryCharges", description="The list of charges"
    )
    payments: list[PaymentModel] | None = Field(
        None,
        description="The list of payments - <b>DEPRECATED: This field will be removed on July 3rd 2020. Use GET /finance/v1/folios/{folioId}/payments or GET /finance/v1/folios/{folioId}/refunds instead.</b>",
    )
    pending_payments: list[PendingPaymentModel] | None = Field(
        None,
        alias="pendingPayments",
        description="The list of pending payments - <b>DEPRECATED: This field will be removed on July 3rd 2020. Use GET /finance/v1/folios/{folioId}/payments instead.</b>",
    )
    allowances: list[AllowanceModel] | None = Field(
        None, description="The list of allowances"
    )
    balance: MonetaryValueModel
    checked_out_on_accounts_receivable: bool | None = Field(
        None,
        alias="checkedOutOnAccountsReceivable",
        description="Set to `true`, if the folio has been checked out on accounts receivable.\nIf you create an invoice from this folio, it will display the outstanding payments",
    )
    is_main_folio: bool | None = Field(
        None,
        alias="isMainFolio",
        description="Set to `true` if this is a main folio for the reservation",
    )
    is_empty: bool | None = Field(
        None,
        alias="isEmpty",
        description="Set to `true` if the folio has no unmoved [transitory] charges, unmoved payments, and allowances.",
    )
    related_folios: list[EmbeddedFolioModel] | None = Field(
        None,
        alias="relatedFolios",
        description="All folios that are related to this folio. Either because they belong to the same reservation/booking or\ncharges were moved/routed between them. It is only set on folios of type 'guest', 'booking', and 'external'.",
    )
    related_invoices: list[EmbeddedInvoiceModel] | None = Field(
        None,
        alias="relatedInvoices",
        description="All invoices that have been created for this folio. This is only set on folios of type 'guest'",
    )
    folio_warnings: list[FolioWarning] | None = Field(
        None,
        alias="folioWarnings",
        description="Depending on the state of the folio, certain warnings are shown.\nThis list includes all folio warnings.",
    )
    allowed_actions: list[AllowedAction] | None = Field(
        None,
        alias="allowedActions",
        description="Depending on the state of the folio, certain actions are allowed or not.\nThis list includes all actions you can perform on this folio.",
    )
    allowed_payment: float | None = Field(
        None,
        alias="allowedPayment",
        description="The maximum payment that can be posted on this folio",
    )
    maximum_allowance: float | None = Field(
        None,
        alias="maximumAllowance",
        description="The maximum allowance (gross) that can be posted on this folio",
    )
    status: Status = Field(..., description="Status of the folio")


class IncludedLineItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    description: str | None = Field(
        None, description="The description of the item or service"
    )
    price: MonetaryValueModel
    vat_type: VatType | None = Field(
        None, alias="vatType", description="The applied VAT type."
    )
    vat_percent: float | None = Field(
        None, alias="vatPercent", description="The applied VAT percent"
    )


class InvoiceItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="Invoice identifier")
    number: str = Field(..., description="Invoice number", min_length=1)
    type: Type9 = Field(..., description="Invoice type")
    series: str | None = Field(None, description="Invoice number series")
    language_code: str = Field(
        ...,
        alias="languageCode",
        description="Language which was used to create the invoice",
    )
    folio_id: str = Field(
        ..., alias="folioId", description="The folio for this invoice"
    )
    reservation_id: str | None = Field(
        None, alias="reservationId", description="The reservation for this invoice"
    )
    booking_id: str | None = Field(
        None, alias="bookingId", description="The booking for this invoice"
    )
    property_id: str = Field(
        ..., alias="propertyId", description="The ID of the property"
    )
    related_invoice_number: str | None = Field(
        None,
        alias="relatedInvoiceNumber",
        description="If the invoice is related to another invoice, this field contains related invoice number\nFor example, if the invoice has Cancellation type,\nthis field contains the number of invoice which is being cancelled",
    )
    write_off_reason: str | None = Field(
        None,
        alias="writeOffReason",
        description="If the invoice was written-off, this field contains the reason why it was written-off",
    )
    cancellation_reason_code: ReasonCode | None = Field(
        None,
        alias="cancellationReasonCode",
        description="If the invoice is a cancellation invoice, this field contains the code of the cancellation reason",
    )
    sub_total: MonetaryValueModel = Field(..., alias="subTotal")
    outstanding_payment: MonetaryValueModel | None = Field(
        None, alias="outstandingPayment"
    )
    payment_settled: bool = Field(
        ...,
        alias="paymentSettled",
        description="True, if this invoice had no outstanding payments or was settled.",
    )
    status: Status3 = Field(..., description="Status of the invoice")
    created: AwareDatetime = Field(
        ...,
        description='Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    guest_name: str | None = Field(
        None, alias="guestName", description="Name of the guest"
    )
    guest_company: str | None = Field(
        None, alias="guestCompany", description="Company the guest specified"
    )
    allowed_actions: list[AllowedAction2] | None = Field(
        None,
        alias="allowedActions",
        description="Depending on the state of the invoice, certain actions are allowed or not.\nThis list includes all actions you can perform on this invoice.",
    )
    company: EmbeddedCompanyModel | None = None


class InvoiceLineItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    date: date_aliased = Field(
        ...,
        description="The date on which this item or service is delivered",
        examples=["2020-10-10"],
    )
    description: str = Field(
        ..., description="The description of the item or service", min_length=1
    )
    price: MonetaryValueModel
    vat_type: VatType | None = Field(
        None, alias="vatType", description="The applied VAT type."
    )
    vat_percent: float | None = Field(
        None, alias="vatPercent", description="The applied VAT percent"
    )
    is_no_show_fee: bool = Field(
        ...,
        alias="isNoShowFee",
        description="Whether this line item represents a no-show fee",
    )
    included_line_items: list[IncludedLineItemModel] | None = Field(
        None,
        alias="includedLineItems",
        description="Items which are included in the package, if there are any",
    )
    guest: str | None = Field(
        None,
        description="Guest who the service has been provided to. Is defined only when the invoice has charges from multiple folios with different guests.",
    )
    quantity: int | None = Field(None, description="The count of services provided")


class InvoiceLineItemsModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    line_items: list[InvoiceLineItemModel] | None = Field(None, alias="lineItems")
    sub_total: MonetaryValueModel = Field(..., alias="subTotal")


class InvoiceListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    invoices: list[InvoiceItemModel] = Field(..., description="List of invoices.")
    count: int = Field(..., description="Total count of items")


class InvoicePaymentModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(
        ..., description="Id of the payment. This is unique within one folio."
    )
    method: Method2 = Field(..., description="The Payment Method type.")
    method_name: str = Field(
        ...,
        alias="methodName",
        description="The Payment Method name translated in the requested language of the invoice",
        min_length=1,
    )
    amount: MonetaryValueModel
    payment_date: AwareDatetime | None = Field(
        None,
        alias="paymentDate",
        description='The date when the payment was done<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    business_date: date_aliased | None = Field(
        None,
        alias="businessDate",
        description="The business date of the payment, can be different from the payment date for some payments posted after midnight and before 6AM.",
        examples=["2020-10-10"],
    )


class InvoiceRecipientModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    name: str | None = None
    address: NonStrictAddressModel | None = None
    company_name: str | None = Field(None, alias="companyName")
    company_tax_id: str | None = Field(None, alias="companyTaxId")
    reference: str | None = None
    personal_tax_id: str | None = Field(None, alias="personalTaxId")


class PreviewInvoiceModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    to: InvoiceRecipientModel | None = None
    create_invoice_action: CreateInvoiceAction = Field(
        ...,
        alias="createInvoiceAction",
        description="Describes what will happen, when you try to create an invoice with the folio in the state it is in now.",
    )
    create_invoice_warning: CreateInvoiceWarningModel | None = Field(
        None, alias="createInvoiceWarning"
    )
    invoice_date: date_aliased = Field(
        ...,
        alias="invoiceDate",
        description="Date the invoice has been created",
        examples=["2020-10-10"],
    )
    folio_id: str = Field(
        ..., alias="folioId", description="The folio this invoice was requested for"
    )
    from_: InvoiceSenderModel = Field(..., alias="from")
    commercial_information: CommercialInfoModel = Field(
        ..., alias="commercialInformation"
    )
    bank_account: BankAccountModel | None = Field(None, alias="bankAccount")
    payment_terms: str | None = Field(
        None,
        alias="paymentTerms",
        description="Specification of the payment terms, as defined in the property",
    )
    line_items: InvoiceLineItemsModel = Field(..., alias="lineItems")
    payments: list[InvoicePaymentModel] | None = Field(
        None, description="A list of all payments"
    )
    outstanding_payment: MonetaryValueModel | None = Field(
        None, alias="outstandingPayment"
    )
    tax_details: list[TaxDetailModel] | None = Field(
        None,
        alias="taxDetails",
        description="The subtotal, displaying net and tax amount for each VAT type",
    )
    total: MonetaryValueModel
    stay_info: StayInfoModel | None = Field(None, alias="stayInfo")
    property_id: str = Field(
        ..., alias="propertyId", description="The ID of the property"
    )
    property_country_code: str = Field(
        ...,
        alias="propertyCountryCode",
        description="The country code of the property",
        min_length=1,
    )
    language_code: str = Field(
        ...,
        alias="languageCode",
        description="Language which was used to create the invoice",
        min_length=1,
    )
    company: EmbeddedCompanyModel | None = None


class RefundListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    refunds: list[RefundModel] = Field(..., description="List of refunds")
    count: int = Field(..., description="Total count of items")


class RoutingFilterModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    folio_ids: list[str] | None = Field(
        None, alias="folioIds", description="The folio ids filter"
    )
    sub_accounts: list[RoutingSubAccountModel] | None = Field(
        None, alias="subAccounts", description="The subaccounts filter"
    )
    service_types: list[ServiceType] | None = Field(
        None, alias="serviceTypes", description="The service types filter"
    )
    services: list[RoutingServiceModel] | None = Field(
        None, description="The services filter"
    )
    from_: date_aliased | None = Field(
        None, alias="from", description="The start date filter", examples=["2020-10-10"]
    )
    to: date_aliased | None = Field(
        None, description="The end date filter", examples=["2020-10-10"]
    )


class SlimFinanceAccountModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    account_number: str = Field(
        ...,
        alias="accountNumber",
        description="The account number. Unique identifier within one property.",
        min_length=1,
    )
    name: str = Field(..., description="The name of the account.", min_length=1)
    type: Type3 = Field(..., description="The type of account.")
    parent_number: str | None = Field(
        None,
        alias="parentNumber",
        description="Parent account number. Null for top-level accounts.",
    )
    has_children: bool = Field(
        ...,
        alias="hasChildren",
        description="Indicates whether this account has children / sub accounts or not.",
    )
    is_archived: bool = Field(
        ...,
        alias="isArchived",
        description="Indicates whether this account is archived ot not.",
    )
    vat: VatItemModel | None = None
    sub_accounts: list[SlimFinanceAccountModel] | None = Field(
        None, alias="subAccounts", description="Sub accounts for this accounts."
    )


class ActionModelPaymentActionNotAllowedPaymentActionReason(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    action: Action
    is_allowed: bool = Field(..., alias="isAllowed")
    reasons: list[ActionReasonModelNotAllowedPaymentActionReason] | None = None


class ActionModelRoutingActionNotAllowedRoutingActionReason(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    action: Action1
    is_allowed: bool = Field(..., alias="isAllowed")
    reasons: list[ActionReasonModelNotAllowedRoutingActionReason] | None = None


class AccountingTransactionListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    transactions: list[AccountingTransactionModel] = Field(
        ..., description="The list of transactions"
    )


class AccountingTransactionPairListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    account_transaction_pairs: list[AccountingTransactionPairModel] = Field(
        ...,
        alias="accountTransactionPairs",
        description="The list of aggregated transaction pairs",
    )


class AggregateTransactionListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    aggregations: list[AggregateTransactionItemModel] = Field(
        ..., description="Aggregated data for the main accounts."
    )
    total: AggregatesTotalModel


class ChartOfAccountsModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    global_accounts: list[SlimFinanceAccountModel] = Field(
        ...,
        alias="globalAccounts",
        description="The predefined list of global accounts of a property's subledger",
    )
    guest_accounts: list[SlimFinanceAccountModel] = Field(
        ...,
        alias="guestAccounts",
        description="The predefined list of guest specific accounts of a property's subledger.",
    )
    external_accounts: list[SlimFinanceAccountModel] = Field(
        ...,
        alias="externalAccounts",
        description="The predefined list of external accounts of a property's subledger.",
    )
    booking_accounts: list[SlimFinanceAccountModel] = Field(
        ...,
        alias="bookingAccounts",
        description="The predefined list of booking accounts of a property's subledger.",
    )


class CreateFolioModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    reservation_id: str | None = Field(
        None,
        alias="reservationId",
        description="The ID of the reservation for which a guest folio should be created",
    )
    company_id: str | None = Field(
        None,
        alias="companyId",
        description="The ID of the company for which a folio should be created",
    )
    debitor: FolioDebitorModel
    type: Type1 | None = Field(
        None,
        description="The type of the folio to create. Default is the guest folio.\nThis field will become required 01.11.2019.",
    )
    property_id: str | None = Field(
        None,
        alias="propertyId",
        description="The ID of the property for which an external folio should be created.",
    )
    code: str | None = Field(
        None,
        description="Optional code for external folios.\nIf present, the id of the folio will be propertyId-code (MUC-SOMETHING);\nIf no code is provided, the id of the folio will be propertyId-ext-number (MUC-EXT-282).",
    )


class FinanceAccountListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    accounts: list[SlimFinanceAccountModel] = Field(
        ..., description="List of accounts in a property, having one specific parent."
    )
    count: int = Field(..., description="Total count of items")


class FolioPaymentModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(
        ..., description="Id of the payment. This is unique within one folio"
    )
    method: Method2 | None = Field(None, description="The payment method")
    amount: MonetaryValueModel
    external_reference: ExternalReference | None = Field(
        None, alias="externalReference"
    )
    receipt: str | None = Field(None, description="Receipt for the payment")
    payment_date: AwareDatetime = Field(
        ...,
        alias="paymentDate",
        description='The date and time when the payment was created<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    moved_from: EmbeddedFolioModel | None = Field(None, alias="movedFrom")
    moved_to: EmbeddedFolioModel | None = Field(None, alias="movedTo")
    moved_reason: str | None = Field(
        None,
        alias="movedReason",
        description="A reason why the move operation was performed",
    )
    source_payment_id: str | None = Field(
        None,
        alias="sourcePaymentId",
        description="A link to the original payment in case of splitting payments",
    )
    status: Status2 = Field(..., description="Status of the payment")
    failure_reason: str | None = Field(
        None, alias="failureReason", description="Human readable failure reason"
    )
    failure_code: FailureCode | None = Field(
        None, alias="failureCode", description="Machine-readable failure code"
    )
    type: Type8 = Field(..., description="Type of the payment")
    expires_at: AwareDatetime | None = Field(
        None,
        alias="expiresAt",
        description='The date and time a payment link expires<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    description: str | None = Field(None, description="Payment link description")
    url: str | None = Field(None, description="Payment link url")
    actions: list[ActionModelPaymentActionNotAllowedPaymentActionReason] | None = Field(
        None, description="The list of actions for this payment"
    )
    business_date: date_aliased = Field(
        ...,
        alias="businessDate",
        description="The business date of the payment",
        examples=["2020-10-10"],
    )


class InvoiceModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="Invoice identifier")
    number: str = Field(..., description="Invoice number", min_length=1)
    type: Type9 = Field(..., description="Invoice type")
    series: str | None = Field(None, description="Invoice number series")
    to: InvoiceRecipientModel
    payment_settled: bool = Field(
        ...,
        alias="paymentSettled",
        description="True, if this invoice had no outstanding payments or was settled.",
    )
    status: Status3 = Field(..., description="Status of the invoice")
    created: AwareDatetime = Field(
        ...,
        description='Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    related_invoice_number: str | None = Field(
        None,
        alias="relatedInvoiceNumber",
        description="If the invoice is related to another invoice, this field contains related invoice number\nFor example, if the invoice has Cancellation type,\nthis field contains the number of invoice which is being cancelled",
    )
    write_off_reason: str | None = Field(
        None,
        alias="writeOffReason",
        description="If the invoice was written-off, this field contains the reason why it was written-off",
    )
    cancellation_reason_code: ReasonCode | None = Field(
        None,
        alias="cancellationReasonCode",
        description="If the invoice is a cancellation invoice, this field contains the code of the cancellation reason",
    )
    allowed_actions: list[AllowedAction2] | None = Field(
        None,
        alias="allowedActions",
        description="Depending on the state of the invoice, certain actions are allowed or not.\nThis list includes all actions you can perform on this invoice.",
    )
    invoice_date: date_aliased = Field(
        ...,
        alias="invoiceDate",
        description="Date the invoice has been created",
        examples=["2020-10-10"],
    )
    folio_id: str = Field(
        ..., alias="folioId", description="The folio this invoice was requested for"
    )
    from_: InvoiceSenderModel = Field(..., alias="from")
    commercial_information: CommercialInfoModel = Field(
        ..., alias="commercialInformation"
    )
    bank_account: BankAccountModel | None = Field(None, alias="bankAccount")
    payment_terms: str | None = Field(
        None,
        alias="paymentTerms",
        description="Specification of the payment terms, as defined in the property",
    )
    line_items: InvoiceLineItemsModel = Field(..., alias="lineItems")
    payments: list[InvoicePaymentModel] | None = Field(
        None, description="A list of all payments"
    )
    outstanding_payment: MonetaryValueModel | None = Field(
        None, alias="outstandingPayment"
    )
    tax_details: list[TaxDetailModel] | None = Field(
        None,
        alias="taxDetails",
        description="The subtotal, displaying net and tax amount for each VAT type",
    )
    total: MonetaryValueModel
    stay_info: StayInfoModel | None = Field(None, alias="stayInfo")
    property_id: str = Field(
        ..., alias="propertyId", description="The ID of the property"
    )
    property_country_code: str = Field(
        ...,
        alias="propertyCountryCode",
        description="The country code of the property",
        min_length=1,
    )
    language_code: str = Field(
        ...,
        alias="languageCode",
        description="Language which was used to create the invoice",
        min_length=1,
    )
    company: EmbeddedCompanyModel | None = None


class PaymentListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    payments: list[FolioPaymentModel] = Field(..., description="List of payments")
    count: int = Field(..., description="Total count of items")


class RoutingModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The ID of the routing")
    booking_id: str = Field(..., alias="bookingId", description="The ID of the booking")
    property_id: str = Field(
        ..., alias="propertyId", description="The ID of the property"
    )
    filter: RoutingFilterModel | None = None
    destination_folio: RoutingFolioModel = Field(..., alias="destinationFolio")
    actions: list[ActionModelRoutingActionNotAllowedRoutingActionReason] | None = Field(
        None, description="The list of actions for this routing"
    )


class RoutingListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    routings: list[RoutingModel] = Field(..., description="The list of routings")
    count: int = Field(..., description="Total count of items")


SlimFinanceAccountModel.model_rebuild()
