# generated by datamodel-codegen:
#   filename:  core_v0_inventory.json
#   timestamp: 2026-02-28T07:47:22+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class AddressModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    address_line1: str = Field(..., alias="addressLine1", min_length=1)
    address_line2: str | None = Field(None, alias="addressLine2")
    postal_code: str = Field(..., alias="postalCode", min_length=1)
    city: str = Field(..., min_length=1)
    region_code: str | None = Field(None, alias="regionCode")
    country_code: str = Field(..., alias="countryCode")


class BankAccountModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    iban: str | None = None
    bic: str | None = None
    bank: str | None = None


class BulkUnitsCreatedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    ids: list[str] = Field(..., description="The unit ids")


class ConnectedUnitGroupModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The unit group id")
    name: str = Field(..., description="The name for the unit group", min_length=1)
    description: str = Field(
        ..., description="The description for the unit group", min_length=1
    )
    member_count: int = Field(
        ...,
        alias="memberCount",
        description="The number of units taken from this connected unit group",
    )
    max_persons: int | None = Field(
        None,
        alias="maxPersons",
        description="Maximum number of persons for the unit group",
    )


class Condition(StrEnum):
    clean = "Clean"
    clean_to_be_inspected = "CleanToBeInspected"
    dirty = "Dirty"


class ConnectedUnitModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The unit id")
    name: str = Field(..., description="The name for the unit", min_length=1)
    description: str = Field(
        ..., description="The description for the unit", min_length=1
    )
    unit_group_id: str = Field(
        ..., alias="unitGroupId", description="The unit group id"
    )
    condition: Condition = Field(..., description="The current status of the unit")
    max_persons: int = Field(
        ..., alias="maxPersons", description="Maximum number of persons for the unit"
    )


class CountModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    count: int


class CountryListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    country_codes: list[str] = Field(
        ..., alias="countryCodes", description="List of ISO country codes."
    )


class CreateAddressModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    address_line1: str = Field(..., alias="addressLine1", min_length=1)
    address_line2: str | None = Field(None, alias="addressLine2")
    postal_code: str = Field(..., alias="postalCode", min_length=1)
    city: str = Field(..., min_length=1)
    region_code: str | None = Field(
        None,
        alias="regionCode",
        description="The ISO 3166-2 code",
        max_length=6,
        min_length=2,
    )
    country_code: str = Field(
        ...,
        alias="countryCode",
        description="The country code, in ISO 3166-1 alpha-2 code",
        max_length=2,
        min_length=2,
    )


class CreateConnectedUnitGroupModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    unit_group_id: str = Field(
        ..., alias="unitGroupId", description="The connected unit group id"
    )
    member_count: int = Field(
        ...,
        alias="memberCount",
        description="The number of units for this connected unit group",
        ge=1,
        le=2147483647,
    )


class CreateConnectedUnitModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    unit_id: str = Field(..., alias="unitId", description="The connected unit id")


class CreatePropertyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    code: str = Field(
        ...,
        description="The code for the property that can be shown in reports and table views",
        max_length=10,
        min_length=3,
        pattern="^[a-zA-Z0-9_]*$",
    )
    name: dict[str, str] = Field(..., description="The name for the property")
    company_name: str = Field(
        ...,
        alias="companyName",
        description="The legal name of the company running the property.",
        min_length=1,
    )
    managing_directors: str | None = Field(
        None,
        alias="managingDirectors",
        description="The managing director(s) of the company, as they should appear on invoices",
    )
    commercial_register_entry: str = Field(
        ...,
        alias="commercialRegisterEntry",
        description="The entry in the Commercial Reigster of the company running the property, as it should appear on invoices",
        min_length=1,
    )
    tax_id: str = Field(
        ...,
        alias="taxId",
        description="The Tax-ID of the company running the property, as it should appear on invoices",
        min_length=1,
    )
    description: dict[str, str] | None = Field(
        None, description="The description for the property"
    )
    location: CreateAddressModel
    bank_account: BankAccountModel | None = Field(None, alias="bankAccount")
    payment_terms: dict[str, str] = Field(
        ...,
        alias="paymentTerms",
        description="The payment terms used for all rate plans",
    )
    time_zone: str = Field(
        ...,
        alias="timeZone",
        description="The time zone name of the property from the IANA Time Zone Database.\r\n(see: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)",
        min_length=1,
    )
    default_check_in_time: str = Field(
        ...,
        alias="defaultCheckInTime",
        description='The default check-in time<br />A time (without fractional second part) as defined in the <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    default_check_out_time: str = Field(
        ...,
        alias="defaultCheckOutTime",
        description='The default check-out time<br />A time (without fractional second part) as defined in the <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    currency_code: str = Field(
        ..., alias="currencyCode", description="The currency a property works with."
    )


class CreateUnitAttributeDefinitionModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    name: str = Field(
        ..., description="The name of the unit attribute", max_length=50, min_length=1
    )
    description: str | None = Field(
        None, description="The description of the unit attribute"
    )


class CreateUnitAttributeModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="Id of unit attribute")


class Type(StrEnum):
    bed_room = "BedRoom"
    meeting_room = "MeetingRoom"
    event_space = "EventSpace"
    parking_lot = "ParkingLot"


class CreateUnitGroupModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    code: str = Field(
        ...,
        description="The code for the unit group that can be shown in reports and table views",
        max_length=10,
        min_length=3,
        pattern="^[a-zA-Z0-9_]*$",
    )
    property_id: str = Field(
        ...,
        alias="propertyId",
        description="The id of the property where unit group will be created",
    )
    name: dict[str, str] = Field(..., description="The name for the unit group")
    description: dict[str, str] = Field(
        ..., description="The description for the unit group"
    )
    max_persons: int = Field(
        ...,
        alias="maxPersons",
        description="Maximum number of persons for the unit group",
        ge=1,
        le=2147483647,
    )
    rank: int | None = Field(
        None,
        description="The unit group rank\r\nRestrictions:\r\n- Should be greater or equal to one",
        ge=1,
        le=2147483647,
    )
    type: Type | None = Field(None, description="The unit group type")
    connected_unit_groups: list[CreateConnectedUnitGroupModel] | None = Field(
        None,
        alias="connectedUnitGroups",
        description="The list of connected unit groups this unit group is composed of",
    )


class CreateUnitModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    property_id: str = Field(
        ...,
        alias="propertyId",
        description="The id of the property where the unit will be created",
    )
    name: str = Field(..., description="The name for the unit", min_length=1)
    description: dict[str, str] = Field(..., description="The description for the unit")
    unit_group_id: str | None = Field(
        None, alias="unitGroupId", description="The id of the unit group"
    )
    max_persons: int = Field(
        ...,
        alias="maxPersons",
        description="Maximum number of persons for the unit",
        ge=1,
        le=2147483647,
    )
    condition: Condition | None = Field(None, description="Condition of the unit")
    attributes: list[CreateUnitAttributeModel] | None = Field(
        None, description="Collection of user defined attributes of unit"
    )
    connected_units: list[CreateConnectedUnitModel] | None = Field(
        None,
        alias="connectedUnits",
        description="The list of units this unit is composed of",
    )


class EmbeddedPropertyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The property id")
    code: str | None = Field(
        None,
        description="The code for the property that can be shown in reports and table views",
    )
    name: str | None = Field(None, description="The name for the property")
    description: str | None = Field(
        None, description="The description for the property"
    )


class Type1(StrEnum):
    bed_room = "BedRoom"
    meeting_room = "MeetingRoom"
    event_space = "EventSpace"
    parking_lot = "ParkingLot"
    other = "Other"


class EmbeddedUnitGroupModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The unit group id")
    code: str | None = Field(
        None,
        description="The code for the unit group that can be shown in reports and table views",
    )
    name: str | None = Field(None, description="The name for the unit group")
    description: str | None = Field(
        None, description="The description for the unit group"
    )
    type: Type1 | None = Field(None, description="The unit group type")


class EmbeddedUnitModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The unit id")
    name: str | None = Field(None, description="The name for the unit")
    description: str | None = Field(None, description="The description for the unit")
    unit_group_id: str | None = Field(
        None, alias="unitGroupId", description="The unit group id"
    )


class MessageItemCollection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    messages: list[str] | None = None


class Operation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    value: Any | None = None
    path: str | None = None
    op: str | None = None
    from_: str | None = Field(None, alias="from")


class PropertyCreatedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The property id")


class Status(StrEnum):
    test = "Test"
    live = "Live"


class ReplaceConnectedUnitGroupModel(CreateConnectedUnitGroupModel):
    pass


class ReplaceUnitGroupModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    name: dict[str, str] = Field(..., description="The name for the unit group")
    description: dict[str, str] = Field(
        ..., description="The description for the unit group"
    )
    max_persons: int | None = Field(
        None,
        alias="maxPersons",
        description="Maximum number of persons for the unit group.\r\nIf this value is increased, the surcharges for the related rate plans must be specified in order for the rate plans to be sellable for the new possible occupancies.",
    )
    rank: int | None = Field(
        None,
        description="The unit group rank\r\nRestrictions:\r\n- Should be greater or equal to one",
        ge=1,
        le=2147483647,
    )
    connected_unit_groups: list[ReplaceConnectedUnitGroupModel] | None = Field(
        None,
        alias="connectedUnitGroups",
        description="The list of connected unit groups this unit group is composed of",
    )


class UnitAttributeDefinitionCreatedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The unit attribute id")


class UnitAttributeDefinitionModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The id of the unit attribute")
    name: str = Field(..., description="The name of the unit attribute", min_length=1)
    description: str | None = Field(
        None, description="The description of the unit attribute"
    )


class UnitAttributeModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="Id of unit attribute")
    name: str = Field(..., description="The name of the unit attribute", min_length=1)
    description: str | None = Field(None, description="Description of unit attribute")


class UnitCreatedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The unit id")


class UnitGroupCreatedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The unit group id")


class UnitGroupItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The unit group id")
    code: str = Field(
        ...,
        description="The code for the unit group that can be shown in reports and table views",
    )
    name: str = Field(..., description="The name for the unit group", min_length=1)
    description: str = Field(
        ..., description="The description for the unit group", min_length=1
    )
    member_count: int = Field(
        ..., alias="memberCount", description="Number of units in this group"
    )
    max_persons: int | None = Field(
        None,
        alias="maxPersons",
        description="Maximum number of persons for the unit group",
    )
    rank: int | None = Field(None, description="The unit group rank")
    type: Type1 = Field(..., description="The unit group type")
    property: EmbeddedPropertyModel
    connected_unit_groups: list[ConnectedUnitGroupModel] | None = Field(
        None,
        alias="connectedUnitGroups",
        description="The list of connected unit groups this unit group is composed of",
    )


class UnitGroupListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    unit_groups: list[UnitGroupItemModel] = Field(
        ..., alias="unitGroups", description="List of unit groups"
    )
    count: int = Field(..., description="Total count of items")


class UnitGroupModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The unit group id")
    code: str = Field(
        ...,
        description="The code for the unit group that can be shown in reports and table views",
    )
    property: EmbeddedPropertyModel
    name: dict[str, str] = Field(..., description="The name for the unit group")
    member_count: int = Field(
        ..., alias="memberCount", description="Number of units in this group"
    )
    description: dict[str, str] = Field(
        ..., description="The description for the unit group"
    )
    max_persons: int = Field(
        ...,
        alias="maxPersons",
        description="Maximum number of persons for the unit group",
    )
    rank: int | None = Field(None, description="The unit group rank")
    type: Type1 = Field(..., description="The unit group type")
    connected_unit_groups: list[ConnectedUnitGroupModel] | None = Field(
        None,
        alias="connectedUnitGroups",
        description="The list of connected unit groups this unit group is composed of",
    )


class Type4(StrEnum):
    out_of_service = "OutOfService"
    out_of_order = "OutOfOrder"
    out_of_inventory = "OutOfInventory"


class UnitItemMaintenanceModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The id for the scheduled maintenance")
    type: Type4 = Field(
        ...,
        description="The type of maintenance that is planned for the unit. A small repair (OutOfService),\r\na bigger disfunction that does not allow to sell the unit (OutOfOrder) or is it\r\neven under construction and should reduce the house count (OutOfInventory)",
    )


class UnitItemStatusModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    is_occupied: bool = Field(..., alias="isOccupied")
    condition: Condition
    maintenance: UnitItemMaintenanceModel | None = None


class UnitMaintenanceModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The id for the scheduled maintenance")
    from_: AwareDatetime = Field(
        ...,
        alias="from",
        description='Date and time the scheduled maintenance window starts<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    to: AwareDatetime = Field(
        ...,
        description='Date and time the scheduled maintenance window ends<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    type: Type4 = Field(
        ...,
        description="The type of maintenance that is planned for the unit. A small repair (OutOfService),\r\na bigger disfunction that does not allow to sell the unit (OutOfOrder) or is it\r\neven under construction and should reduce the house count (OutOfInventory)",
    )
    description: str | None = Field(
        None, description="The description text for the maintenance"
    )


class UnitStatusModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    is_occupied: bool = Field(..., alias="isOccupied")
    condition: Condition
    maintenance: UnitMaintenanceModel | None = None


class Action(StrEnum):
    delete = "Delete"
    archive = "Archive"
    set_live = "SetLive"
    reset = "Reset"


class Code(StrEnum):
    delete_not_allowed_for_property_not_in_status_test = (
        "DeleteNotAllowedForPropertyNotInStatusTest"
    )
    archive_not_allowed_for_property_not_in_status_live = (
        "ArchiveNotAllowedForPropertyNotInStatusLive"
    )
    archive_not_allowed_for_property_which_is_already_archived = (
        "ArchiveNotAllowedForPropertyWhichIsAlreadyArchived"
    )
    set_to_live_not_allowed_for_property_not_in_status_test = (
        "SetToLiveNotAllowedForPropertyNotInStatusTest"
    )
    set_to_live_not_allowed_for_property_in_non_live_account = (
        "SetToLiveNotAllowedForPropertyInNonLiveAccount"
    )
    reset_not_allowed_for_property_not_in_status_test = (
        "ResetNotAllowedForPropertyNotInStatusTest"
    )


class ActionReasonModelNotAllowedPropertyActionReason(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    code: Code
    message: str = Field(..., min_length=1)


class BulkCreateUnitsModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    units: list[CreateUnitModel]


class UnitAttributeDefinitionListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    unit_attributes: list[UnitAttributeDefinitionModel] = Field(
        ..., alias="unitAttributes", description="List of unit attributes"
    )
    count: int = Field(..., description="Total count of items")


class UnitItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The unit id")
    name: str = Field(..., description="The name for the unit", min_length=1)
    description: str = Field(
        ..., description="The description for the unit", min_length=1
    )
    property: EmbeddedPropertyModel
    unit_group: EmbeddedUnitGroupModel | None = Field(None, alias="unitGroup")
    connecting_unit: EmbeddedUnitModel | None = Field(None, alias="connectingUnit")
    status: UnitItemStatusModel
    max_persons: int = Field(
        ..., alias="maxPersons", description="Maximum number of persons for the unit"
    )
    created: AwareDatetime = Field(
        ...,
        description='Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    attributes: list[UnitAttributeModel] | None = Field(
        None, description="Collection of user defined attributes of unit"
    )
    connected_units: list[ConnectedUnitModel] | None = Field(
        None, alias="connectedUnits", description="Collection of connected units"
    )


class UnitListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    units: list[UnitItemModel] = Field(..., description="List of units")
    count: int = Field(..., description="Total count of items")


class UnitModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The unit id")
    name: str = Field(..., description="The name for the unit", min_length=1)
    description: dict[str, str] = Field(..., description="The description for the unit")
    property: EmbeddedPropertyModel
    unit_group: EmbeddedUnitGroupModel | None = Field(None, alias="unitGroup")
    connecting_unit: EmbeddedUnitModel | None = Field(None, alias="connectingUnit")
    status: UnitStatusModel
    max_persons: int = Field(
        ..., alias="maxPersons", description="Maximum number of persons for the unit"
    )
    created: AwareDatetime = Field(
        ...,
        description='Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    attributes: list[UnitAttributeModel] | None = Field(
        None, description="Collection of user defined attributes of unit"
    )
    connected_units: list[ConnectedUnitModel] | None = Field(
        None, alias="connectedUnits", description="Collection of connected units"
    )


class ActionModelPropertyActionNotAllowedPropertyActionReason(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    action: Action
    is_allowed: bool = Field(..., alias="isAllowed")
    reasons: list[ActionReasonModelNotAllowedPropertyActionReason] | None = None


class PropertyItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The property id")
    code: str = Field(
        ...,
        description="The code for the property that can be shown in reports and table views",
    )
    property_template_id: str | None = Field(
        None,
        alias="propertyTemplateId",
        description="The id of the property used as a template while creating the property",
    )
    is_template: bool = Field(
        ...,
        alias="isTemplate",
        description="Whether the property can be used as a template for other properties",
    )
    name: str = Field(..., description="The name for the property", min_length=1)
    description: str | None = Field(
        None, description="The description for the property"
    )
    company_name: str = Field(
        ...,
        alias="companyName",
        description="The legal name of the company running the property.",
        min_length=1,
    )
    managing_directors: str | None = Field(
        None,
        alias="managingDirectors",
        description="The managing director(s) of the company, as they should appear on invoices",
    )
    commercial_register_entry: str = Field(
        ...,
        alias="commercialRegisterEntry",
        description="The entry in the Commercial Register of the company running the property, as it should appear on invoices",
        min_length=1,
    )
    tax_id: str = Field(
        ...,
        alias="taxId",
        description="The Tax-ID of the company running the property, as it should appear on invoices",
        min_length=1,
    )
    location: AddressModel
    bank_account: BankAccountModel | None = Field(None, alias="bankAccount")
    payment_terms: dict[str, str] = Field(
        ...,
        alias="paymentTerms",
        description="The payment terms used for all rate plans",
    )
    time_zone: str = Field(
        ...,
        alias="timeZone",
        description="The time zone name of the property from the IANA Time Zone Database.\r\n(see: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)",
        min_length=1,
    )
    currency_code: str = Field(
        ..., alias="currencyCode", description="The currency a property works with."
    )
    created: AwareDatetime = Field(
        ...,
        description='Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    status: Status = Field(..., description="The status of the property")
    is_archived: bool = Field(
        ..., alias="isArchived", description="Is the property archived"
    )
    actions: list[ActionModelPropertyActionNotAllowedPropertyActionReason] | None = (
        Field(None, description="The list of actions for this property")
    )


class PropertyListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    properties: list[PropertyItemModel] = Field(..., description="List of properties")
    count: int = Field(..., description="Total count of items")


class PropertyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="The property id")
    code: str = Field(
        ...,
        description="The code for the property that can be shown in reports and table views",
    )
    property_template_id: str | None = Field(
        None,
        alias="propertyTemplateId",
        description="The id of the property used as a template while creating the property",
    )
    is_template: bool = Field(
        ...,
        alias="isTemplate",
        description="Whether the property can be used as a template for other properties",
    )
    name: dict[str, str] = Field(..., description="The name for the property")
    description: dict[str, str | None] | None = Field(
        None, description="The description for the property"
    )
    company_name: str = Field(
        ...,
        alias="companyName",
        description="The legal name of the company running the property.",
        min_length=1,
    )
    managing_directors: str | None = Field(
        None,
        alias="managingDirectors",
        description="The managing director(s) of the company, as they should appear on invoices",
    )
    commercial_register_entry: str = Field(
        ...,
        alias="commercialRegisterEntry",
        description="The entry in the Commercial Register of the company running the property, as it should appear on invoices",
        min_length=1,
    )
    tax_id: str = Field(
        ...,
        alias="taxId",
        description="The Tax-ID of the company running the property, as it should appear on invoices",
        min_length=1,
    )
    location: AddressModel
    bank_account: BankAccountModel | None = Field(None, alias="bankAccount")
    payment_terms: dict[str, str] = Field(
        ...,
        alias="paymentTerms",
        description="The payment terms used for all rate plans",
    )
    time_zone: str = Field(
        ...,
        alias="timeZone",
        description="The time zone name of the property from the IANA Time Zone Database.\r\n(see: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)",
        min_length=1,
    )
    currency_code: str = Field(
        ..., alias="currencyCode", description="The currency a property works with."
    )
    created: AwareDatetime = Field(
        ...,
        description='Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a>',
    )
    status: Status = Field(..., description="The status of the property")
    is_archived: bool = Field(
        ..., alias="isArchived", description="Is the property archived"
    )
    actions: list[ActionModelPropertyActionNotAllowedPropertyActionReason] | None = (
        Field(None, description="The list of actions for this property")
    )
