# generated by datamodel-codegen:
#   filename:  identity_v1_identity.json
#   timestamp: 2026-04-01T19:49:42+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, Field


class Role(StrEnum):
    account_admin = "AccountAdmin"
    property_admin = "PropertyAdmin"
    accountant = "Accountant"
    revenue_manager = "RevenueManager"
    reservation_manager = "ReservationManager"
    front_desk = "FrontDesk"
    front_desk_senior = "FrontDeskSenior"
    housekeeping = "Housekeeping"
    housekeeping_manager = "HousekeepingManager"
    auditor = "Auditor"
    staff_manager = "StaffManager"


class Role1(StrEnum):
    account_admin = "AccountAdmin"
    property_admin = "PropertyAdmin"
    finance_manager = "FinanceManager"
    revenue_manager = "RevenueManager"
    reservation_office = "ReservationOffice"
    front_office = "FrontOffice"
    housekeeping = "Housekeeping"
    housekeeping_manager = "HousekeepingManager"
    auditor = "Auditor"
    staff_manager = "StaffManager"


class CreateInvitationModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    email: EmailStr = Field(
        ..., description="Email address, used as the login", min_length=1
    )
    properties: list[str] | None = Field(
        None,
        description="Properties that user has access to. If the user is invited as account admin, this will be ignored.",
    )
    is_account_admin: bool | None = Field(
        None,
        alias="isAccountAdmin",
        description="If set to `true`, user has full access to all properties. Defaults to false.",
    )
    roles: list[Role] | None = Field(
        None,
        description="Roles that user has access to. If the user is invited as account admin, this will be ignored.",
    )
    role: Role1 | None = Field(
        None,
        description="The role to be assigned to the user. If you specfiy this and 'Roles', the combination of both will be used.\r\nIf the user is invited as account admin, this will be ignored.",
    )


class InvitationAuditLogModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    aggregate_type: str | None = Field(None, alias="aggregateType")
    account_code: str | None = Field(None, alias="accountCode")
    email: str | None = None
    properties: list[str] | None = None
    roles: list[str] | None = None
    is_account_admin: bool | None = Field(None, alias="isAccountAdmin")


class InvitationModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    email: str = Field(
        ..., description="Email address, used as the login", min_length=1
    )
    properties: list[str] | None = Field(
        None, description="Properties that user has access to"
    )
    is_account_admin: bool = Field(
        ...,
        alias="isAccountAdmin",
        description="If set to `true`, user has full access to all properties.",
    )
    role: Role1 | None = Field(
        None,
        description="Role this user is invited to. If more than one, returns the first.",
    )
    roles: list[Role] | None = Field(None, description="Roles that user has access to")
    invited_by: str = Field(
        ...,
        alias="invitedBy",
        description="Email of the user making the invitation",
        min_length=1,
    )
    created: AwareDatetime = Field(..., description="Date the invitation was made")


class InvitedUserToAccountResponseModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    email: str = Field(..., description="Email of invited user", min_length=1)


class MessageItemCollection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    messages: list[str] | None = None


class Operation(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    op: str | None = None
    value: dict[str, Any] | None = None
    path: str | None = None


class PropertyRolesAuditLogModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str | None = Field(None, description="Property Id related to this change")
    roles: list[str] | None = None


class PropertyRolesItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., min_length=1)
    roles: list[Role]


class RoleListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    roles: list[Role] = Field(..., description="A list of all existing roles")


class UserAuditLogModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    first_name: str | None = Field(None, alias="firstName")
    last_name: str | None = Field(None, alias="lastName")
    email: str | None = None
    enabled: bool | None = None
    is_account_admin: bool | None = Field(None, alias="isAccountAdmin")
    properties_roles: list[PropertyRolesAuditLogModel] | None = Field(
        None, alias="propertiesRoles"
    )
    aggregate_type: str | None = Field(None, alias="aggregateType")


class UserItemModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    subject_id: UUID = Field(
        ..., alias="subjectId", description="Unique user identifier."
    )
    first_name: str = Field(
        ..., alias="firstName", description="First name", min_length=1
    )
    last_name: str = Field(..., alias="lastName", description="Last name", min_length=1)
    email: str = Field(
        ..., description="Email address, used as the login", min_length=1
    )
    properties: list[PropertyRolesItemModel] | None = Field(
        None, description="Properties that user has access to"
    )
    enabled: bool = Field(
        ...,
        description="If set to `false`, the user is disabled for this account and cannot log in",
    )
    is_account_admin: bool = Field(
        ...,
        alias="isAccountAdmin",
        description="If set to `true`, user has full access to all properties.",
    )
    is_mfa_enabled: bool = Field(
        ...,
        alias="isMfaEnabled",
        description="If set to `true` then user has the MFA enabled.",
    )
    is_passkeys_enabled: bool = Field(
        ...,
        alias="isPasskeysEnabled",
        description="If set to `true`, user has Passkeys enabled.",
    )


class UserModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    subject_id: UUID = Field(
        ..., alias="subjectId", description="Unique user identifier."
    )
    first_name: str = Field(
        ..., alias="firstName", description="First name", min_length=1
    )
    last_name: str = Field(..., alias="lastName", description="Last name", min_length=1)
    email: str = Field(
        ..., description="Email address, used as the login", min_length=1
    )
    enabled: bool | None = Field(
        None,
        description="If set to `false`, the user is disabled for this account and cannot log in",
    )
    is_account_admin: bool = Field(
        ...,
        alias="isAccountAdmin",
        description="If set to `true`, user has full access to all properties.",
    )
    is_mfa_enabled: bool = Field(
        ...,
        alias="isMfaEnabled",
        description="If set to `true` then user has the MFA enabled.",
    )
    properties: list[str] | None = Field(
        None, description="List of properties to which user has access."
    )
    property_roles: list[PropertyRolesItemModel] | None = Field(
        None,
        alias="propertyRoles",
        description="List of properties to which user has access.",
    )


class UsersListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    users: list[UserItemModel] = Field(
        ..., description="A collection of users that have access to the current account"
    )
    count: int


class InvitationListModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    invitations: list[InvitationModel] = Field(
        ..., description="All invitations to the current account"
    )
