# generated by datamodel-codegen:
#   filename:  core_v1_rateplan.json
#   timestamp: 2026-05-12T12:25:41+00:00

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any


class VatType(StrEnum):
    null = "Null"
    very_reduced = "VeryReduced"
    reduced = "Reduced"
    normal = "Normal"
    without = "Without"
    special = "Special"
    special1 = "Special1"
    special2 = "Special2"
    reduced_covid19 = "ReducedCovid19"
    normal_covid19 = "NormalCovid19"
    mixed = "Mixed"


class ServiceType(StrEnum):
    other = "Other"
    accommodation = "Accommodation"
    food_and_beverages = "FoodAndBeverages"


@dataclass(frozen=True)
class AccountingConfigModel:
    vat_type: VatType
    service_type: ServiceType
    valid_from: str
    sub_account_id: str | None = None


@dataclass(frozen=True)
class AddressModel:
    address_line1: str
    postal_code: str
    city: str
    country_code: str
    address_line2: str | None = None
    region_code: str | None = None


@dataclass(frozen=True)
class AgeCategoryCreatedModel:
    id: str


@dataclass(frozen=True)
class AgeCategoryItemModel:
    id: str
    code: str
    property_id: str
    name: str
    min_age: int
    max_age: int


@dataclass(frozen=True)
class AgeCategoryListModel:
    age_categories: list[AgeCategoryItemModel]
    count: int


@dataclass(frozen=True)
class AgeCategoryModel:
    id: str
    code: str
    property_id: str
    name: dict[str, str]
    min_age: int
    max_age: int


@dataclass(frozen=True)
class AgeCategorySurchargeModel:
    adults: int
    value: float


class Mode(StrEnum):
    arrival = "Arrival"
    departure = "Departure"
    daily = "Daily"


class DaysOfWeekEnum(StrEnum):
    monday = "Monday"
    tuesday = "Tuesday"
    wednesday = "Wednesday"
    thursday = "Thursday"
    friday = "Friday"
    saturday = "Saturday"
    sunday = "Sunday"


@dataclass(frozen=True)
class AvailabilityModel:
    mode: Mode
    quantity: int | None = None
    days_of_week: list[DaysOfWeekEnum] | None = None


@dataclass(frozen=True)
class BookingPeriodModel:
    from_: str
    to: str


@dataclass(frozen=True)
class CancellationPolicyCreatedModel(AgeCategoryCreatedModel):
    pass


class Reference(StrEnum):
    prior_to_arrival = "PriorToArrival"
    after_booking = "AfterBooking"


@dataclass(frozen=True)
class CompanyAddressModel(AddressModel):
    pass


@dataclass(frozen=True)
class CompanyCreatedModel(AgeCategoryCreatedModel):
    pass


@dataclass(frozen=True)
class CompanyRatePlanModel:
    id: str
    code: str
    corporate_code: str
    name: str


@dataclass(frozen=True)
class CorporateCodeModel:
    code: str
    company_id: str
    company_code: str
    company_name: str
    rate_plan_id: str


@dataclass(frozen=True)
class CountModel:
    count: int


@dataclass(frozen=True)
class CreateAgeCategoryModel:
    code: str
    property_id: str
    name: dict[str, str]
    min_age: int
    max_age: int


@dataclass(frozen=True)
class CreateCompanyRatePlanModel:
    id: str
    corporate_code: str | None = None


class Type(StrEnum):
    absolute = "Absolute"
    percent = "Percent"


@dataclass(frozen=True)
class CreatePricingRuleModel:
    base_rate_plan_id: str
    type: Type
    value: float


@dataclass(frozen=True)
class CreateRatePlanCompanyModel(CreateCompanyRatePlanModel):
    pass


class ChannelCode(StrEnum):
    direct = "Direct"
    booking_com = "BookingCom"
    ibe = "Ibe"
    channel_manager = "ChannelManager"
    expedia = "Expedia"
    homelike = "Homelike"
    hrs = "Hrs"
    alto_vita = "AltoVita"
    des_vu = "DesVu"


class MinGuaranteeType(StrEnum):
    pm6_hold = "PM6Hold"
    credit_card = "CreditCard"
    prepayment = "Prepayment"
    company = "Company"


class PriceCalculationMode(StrEnum):
    truncate = "Truncate"
    round = "Round"


class PricingUnit(StrEnum):
    room = "Room"
    person = "Person"


@dataclass(frozen=True)
class EmbeddedMarketSegmentModel:
    id: str
    code: str | None = None
    name: str | None = None


@dataclass(frozen=True)
class EmbeddedNoShowPolicyModel:
    id: str
    code: str | None = None
    name: str | None = None
    description: str | None = None


@dataclass(frozen=True)
class EmbeddedPropertyModel(EmbeddedNoShowPolicyModel):
    pass


@dataclass(frozen=True)
class EmbeddedRatePlanModel:
    id: str
    is_subject_to_city_tax: bool
    code: str | None = None
    name: str | None = None
    description: str | None = None


@dataclass(frozen=True)
class EmbeddedServiceModel(EmbeddedNoShowPolicyModel):
    pass


class Template(StrEnum):
    day_use = "DayUse"
    over_night = "OverNight"


@dataclass(frozen=True)
class EmbeddedTimeSliceDefinitionModel:
    id: str
    name: str
    template: Template
    check_in_time: str
    check_out_time: str


class Type1(StrEnum):
    bed_room = "BedRoom"
    meeting_room = "MeetingRoom"
    event_space = "EventSpace"
    parking_lot = "ParkingLot"
    other = "Other"


@dataclass(frozen=True)
class EmbeddedUnitGroupModel:
    id: str
    code: str | None = None
    name: str | None = None
    description: str | None = None
    type: Type1 | None = None


class Network(StrEnum):
    peppol = "Peppol"


@dataclass(frozen=True)
class InvoiceNetworkIdentityModel:
    network: Network
    id: str


@dataclass(frozen=True)
class MessageItemCollection:
    messages: list[str] | None = None


@dataclass(frozen=True)
class MonetaryValueModel:
    amount: float
    currency: str


@dataclass(frozen=True)
class NoShowPolicyCreatedModel(AgeCategoryCreatedModel):
    pass


@dataclass(frozen=True)
class Operation:
    value: Any | None = None
    path: str | None = None
    op: str | None = None
    from_: str | None = None


@dataclass(frozen=True)
class PercentValueModel:
    percent: int
    limit: int | None = None
    include_service_ids: list[str] | None = None


@dataclass(frozen=True)
class PeriodModel:
    hours: int | None = None
    days: int | None = None
    months: int | None = None


@dataclass(frozen=True)
class PricingRuleModel:
    base_rate_plan: EmbeddedRatePlanModel
    type: Type
    value: float


@dataclass(frozen=True)
class PromoCodeModel:
    code: str
    related_rateplan_ids: list[str]


@dataclass(frozen=True)
class RatePatchModel:
    from_: str
    to: str
    week_days: list[DaysOfWeekEnum] | None = None
    operations: list[Operation] | None = None


@dataclass(frozen=True)
class RatePlanAgeCategoryModel:
    id: str
    surcharges: list[AgeCategorySurchargeModel]


@dataclass(frozen=True)
class RatePlanCompanyModel:
    id: str
    code: str
    name: str
    corporate_code: str | None = None


@dataclass(frozen=True)
class RatePlanCreatedModel(AgeCategoryCreatedModel):
    pass


class PricingMode(StrEnum):
    included = "Included"
    additional = "Additional"


@dataclass(frozen=True)
class RatePlanServiceItemModel:
    service: EmbeddedServiceModel
    gross_price: MonetaryValueModel
    pricing_mode: PricingMode


@dataclass(frozen=True)
class RatePlanServiceModel:
    service_id: str
    gross_price: MonetaryValueModel
    pricing_mode: PricingMode | None = None


@dataclass(frozen=True)
class RateRestrictionsModel:
    closed: bool
    closed_on_arrival: bool
    closed_on_departure: bool
    min_length_of_stay: int | None = None
    max_length_of_stay: int | None = None


@dataclass(frozen=True)
class RatesPatchRequestModel:
    rates: list[RatePatchModel] | None = None


@dataclass(frozen=True)
class RatesRangeModel(BookingPeriodModel):
    pass


@dataclass(frozen=True)
class ReplaceCompanyRatePlanModel(CreateCompanyRatePlanModel):
    pass


@dataclass(frozen=True)
class ReplaceRateModel:
    from_: str
    to: str
    price: MonetaryValueModel | None = None
    restrictions: RateRestrictionsModel | None = None


@dataclass(frozen=True)
class ServiceCreatedModel(AgeCategoryCreatedModel):
    pass


@dataclass(frozen=True)
class ServiceItemModel:
    id: str
    name: str
    code: str
    description: str
    default_gross_price: MonetaryValueModel
    post_next_day: bool
    service_type: ServiceType
    vat_type: VatType
    availability: AvailabilityModel
    property: EmbeddedPropertyModel
    pricing_unit: PricingUnit | None = None
    sub_account_id: str | None = None
    channel_codes: list[ChannelCode] | None = None
    age_category_id: str | None = None


@dataclass(frozen=True)
class ServiceListModel:
    services: list[ServiceItemModel]
    count: int


@dataclass(frozen=True)
class ServiceModel:
    id: str
    code: str
    name: dict[str, str]
    description: dict[str, str]
    default_gross_price: MonetaryValueModel
    pricing_unit: PricingUnit
    post_next_day: bool
    availability: AvailabilityModel
    accounting_configs: list[AccountingConfigModel]
    property: EmbeddedPropertyModel
    channel_codes: list[ChannelCode] | None = None
    age_category_id: str | None = None


@dataclass(frozen=True)
class SurchargeModel:
    adults: int
    type: Type
    value: float


@dataclass(frozen=True)
class BookingRestrictionsModel:
    min_advance: PeriodModel | None = None
    max_advance: PeriodModel | None = None
    late_booking_until: str | None = None


@dataclass(frozen=True)
class CalculatedRateModel:
    adults: int
    price: MonetaryValueModel
    included_services_price: MonetaryValueModel | None = None


@dataclass(frozen=True)
class CompanyModel:
    id: str
    code: str
    property_id: str
    name: str
    address: CompanyAddressModel
    can_check_out_on_ar: bool
    invoicing_email: str | None = None
    phone: str | None = None
    tax_id: str | None = None
    additional_tax_id: str | None = None
    additional_tax_id2: str | None = None
    invoice_network_identity: InvoiceNetworkIdentityModel | None = None
    rate_plans: list[RatePlanCompanyModel] | None = None


@dataclass(frozen=True)
class CorporateCodeListModel:
    corporate_codes: list[CorporateCodeModel]
    count: int


@dataclass(frozen=True)
class CreateCompanyModel:
    code: str
    property_id: str
    name: str
    address: AddressModel
    can_check_out_on_ar: bool
    invoicing_email: str | None = None
    phone: str | None = None
    tax_id: str | None = None
    additional_tax_id: str | None = None
    additional_tax_id2: str | None = None
    invoice_network_identity: InvoiceNetworkIdentityModel | None = None
    rate_plans: list[CreateRatePlanCompanyModel] | None = None


@dataclass(frozen=True)
class CreateRatePlanModel:
    code: str
    property_id: str
    unit_group_id: str
    cancellation_policy_id: str
    channel_codes: list[ChannelCode]
    time_slice_definition_id: str
    name: dict[str, str]
    description: dict[str, str]
    min_guarantee_type: MinGuaranteeType
    no_show_policy_id: str | None = None
    promo_codes: list[str] | None = None
    is_subject_to_city_tax: bool | None = None
    price_calculation_mode: PriceCalculationMode | None = None
    booking_periods: list[BookingPeriodModel] | None = None
    restrictions: BookingRestrictionsModel | None = None
    pricing_rule: CreatePricingRuleModel | None = None
    surcharges: list[SurchargeModel] | None = None
    age_categories: list[RatePlanAgeCategoryModel] | None = None
    included_services: list[RatePlanServiceModel] | None = None
    companies: list[CreateCompanyRatePlanModel] | None = None
    accounting_configs: list[AccountingConfigModel] | None = None
    market_segment_id: str | None = None


@dataclass(frozen=True)
class CreateServiceModel:
    code: str
    name: dict[str, str]
    description: dict[str, str]
    property_id: str
    default_gross_price: MonetaryValueModel
    pricing_unit: PricingUnit
    post_next_day: bool
    availability: AvailabilityModel | None = None
    channel_codes: list[ChannelCode] | None = None
    accounting_configs: list[AccountingConfigModel] | None = None
    age_category_id: str | None = None


@dataclass(frozen=True)
class EmbeddedCancellationPolicyModel:
    id: str
    code: str | None = None
    name: str | None = None
    description: str | None = None
    period_prior_to_arrival: PeriodModel | None = None


@dataclass(frozen=True)
class FeeDetailsModel:
    vat_type: VatType
    fixed_value: MonetaryValueModel | None = None
    percent_value: PercentValueModel | None = None


@dataclass(frozen=True)
class NoShowPolicyItemModel:
    id: str
    code: str
    name: str
    description: str
    property_id: str
    fee: FeeDetailsModel


@dataclass(frozen=True)
class NoShowPolicyListModel:
    no_show_policies: list[NoShowPolicyItemModel]
    count: int


@dataclass(frozen=True)
class NoShowPolicyModel:
    id: str
    code: str
    name: dict[str, str]
    description: dict[str, str]
    property_id: str
    fee: FeeDetailsModel


@dataclass(frozen=True)
class PromoCodeListModel:
    promo_codes: list[PromoCodeModel]
    count: int


@dataclass(frozen=True)
class RateItemModel:
    from_: str
    to: str
    price: MonetaryValueModel | None = None
    included_services_price: MonetaryValueModel | None = None
    calculated_prices: list[CalculatedRateModel] | None = None
    restrictions: RateRestrictionsModel | None = None


@dataclass(frozen=True)
class RateListModel:
    rates: list[RateItemModel]
    count: int


@dataclass(frozen=True)
class RatePlanItemModel:
    id: str
    code: str
    name: str
    description: str
    min_guarantee_type: MinGuaranteeType
    property: EmbeddedPropertyModel
    unit_group: EmbeddedUnitGroupModel
    cancellation_policy: EmbeddedCancellationPolicyModel
    no_show_policy: EmbeddedNoShowPolicyModel
    channel_codes: list[ChannelCode]
    time_slice_definition: EmbeddedTimeSliceDefinitionModel
    is_bookable: bool
    is_subject_to_city_tax: bool
    is_derived: bool
    derivation_level: int
    accounting_configs: list[AccountingConfigModel]
    price_calculation_mode: PriceCalculationMode | None = None
    promo_codes: list[str] | None = None
    restrictions: BookingRestrictionsModel | None = None
    booking_periods: list[BookingPeriodModel] | None = None
    pricing_rule: PricingRuleModel | None = None
    surcharges: list[SurchargeModel] | None = None
    age_categories: list[RatePlanAgeCategoryModel] | None = None
    included_services: list[RatePlanServiceItemModel] | None = None
    companies: list[CompanyRatePlanModel] | None = None
    rates_range: RatesRangeModel | None = None
    market_segment: EmbeddedMarketSegmentModel | None = None
    is_archived: bool | None = None


@dataclass(frozen=True)
class RatePlanListModel:
    rate_plans: list[RatePlanItemModel]
    count: int


@dataclass(frozen=True)
class RatePlanModel:
    id: str
    code: str
    name: dict[str, str]
    description: dict[str, str]
    min_guarantee_type: MinGuaranteeType
    property: EmbeddedPropertyModel
    unit_group: EmbeddedUnitGroupModel
    cancellation_policy: EmbeddedCancellationPolicyModel
    no_show_policy: EmbeddedNoShowPolicyModel
    channel_codes: list[ChannelCode]
    accounting_configs: list[AccountingConfigModel]
    time_slice_definition: EmbeddedTimeSliceDefinitionModel
    is_bookable: bool
    is_subject_to_city_tax: bool
    is_derived: bool
    derivation_level: int
    price_calculation_mode: PriceCalculationMode | None = None
    promo_codes: list[str] | None = None
    restrictions: BookingRestrictionsModel | None = None
    booking_periods: list[BookingPeriodModel] | None = None
    pricing_rule: PricingRuleModel | None = None
    surcharges: list[SurchargeModel] | None = None
    age_categories: list[RatePlanAgeCategoryModel] | None = None
    included_services: list[RatePlanServiceModel] | None = None
    companies: list[CompanyRatePlanModel] | None = None
    rates_range: RatesRangeModel | None = None
    market_segment: EmbeddedMarketSegmentModel | None = None
    is_archived: bool | None = None


@dataclass(frozen=True)
class ReplaceRateListModel:
    rates: list[ReplaceRateModel]


@dataclass(frozen=True)
class ReplaceRatePlanModel:
    name: dict[str, str]
    description: dict[str, str]
    min_guarantee_type: MinGuaranteeType
    channel_codes: list[ChannelCode]
    cancellation_policy_id: str
    price_calculation_mode: PriceCalculationMode | None = None
    promo_codes: list[str] | None = None
    is_subject_to_city_tax: bool | None = None
    no_show_policy_id: str | None = None
    booking_periods: list[BookingPeriodModel] | None = None
    restrictions: BookingRestrictionsModel | None = None
    included_services: list[RatePlanServiceModel] | None = None
    companies: list[ReplaceCompanyRatePlanModel] | None = None
    pricing_rule: CreatePricingRuleModel | None = None
    surcharges: list[SurchargeModel] | None = None
    age_categories: list[RatePlanAgeCategoryModel] | None = None
    accounting_configs: list[AccountingConfigModel] | None = None
    market_segment_id: str | None = None


@dataclass(frozen=True)
class CancellationPolicyItemModel:
    id: str
    name: str
    code: str
    description: str
    property_id: str
    period_from_reference: PeriodModel
    reference: Reference
    fee: FeeDetailsModel


@dataclass(frozen=True)
class CancellationPolicyListModel:
    cancellation_policies: list[CancellationPolicyItemModel]
    count: int


@dataclass(frozen=True)
class CancellationPolicyModel:
    id: str
    code: str
    name: dict[str, str]
    description: dict[str, str]
    property_id: str
    period_from_reference: PeriodModel
    reference: Reference
    fee: FeeDetailsModel


@dataclass(frozen=True)
class CompanyListModel:
    companies: list[CompanyModel]
    count: int


@dataclass(frozen=True)
class CreateCancellationPolicyModel:
    code: str
    name: dict[str, str]
    description: dict[str, str]
    property_id: str
    reference: Reference
    fee: FeeDetailsModel
    period_from_reference: PeriodModel | None = None


@dataclass(frozen=True)
class CreateNoShowPolicyModel:
    code: str
    name: dict[str, str]
    description: dict[str, str]
    property_id: str
    fee: FeeDetailsModel
