# generated by datamodel-codegen:
#   filename:  core_v0_inventory.json
#   timestamp: 2026-02-28T07:47:25+00:00

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any


@dataclass(frozen=True)
class AddressModel:
    address_line1: str
    postal_code: str
    city: str
    country_code: str
    address_line2: str | None = None
    region_code: str | None = None


@dataclass(frozen=True)
class BankAccountModel:
    iban: str | None = None
    bic: str | None = None
    bank: str | None = None


@dataclass(frozen=True)
class BulkUnitsCreatedModel:
    ids: list[str]


@dataclass(frozen=True)
class ConnectedUnitGroupModel:
    id: str
    name: str
    description: str
    member_count: int
    max_persons: int | None = None


class Condition(StrEnum):
    clean = "Clean"
    clean_to_be_inspected = "CleanToBeInspected"
    dirty = "Dirty"


@dataclass(frozen=True)
class ConnectedUnitModel:
    id: str
    name: str
    description: str
    unit_group_id: str
    condition: Condition
    max_persons: int


@dataclass(frozen=True)
class CountModel:
    count: int


@dataclass(frozen=True)
class CountryListModel:
    country_codes: list[str]


@dataclass(frozen=True)
class CreateAddressModel(AddressModel):
    pass


@dataclass(frozen=True)
class CreateConnectedUnitGroupModel:
    unit_group_id: str
    member_count: int


@dataclass(frozen=True)
class CreateConnectedUnitModel:
    unit_id: str


@dataclass(frozen=True)
class CreatePropertyModel:
    code: str
    name: dict[str, str]
    company_name: str
    commercial_register_entry: str
    tax_id: str
    location: CreateAddressModel
    payment_terms: dict[str, str]
    time_zone: str
    default_check_in_time: str
    default_check_out_time: str
    currency_code: str
    managing_directors: str | None = None
    description: dict[str, str] | None = None
    bank_account: BankAccountModel | None = None


@dataclass(frozen=True)
class CreateUnitAttributeDefinitionModel:
    name: str
    description: str | None = None


@dataclass(frozen=True)
class CreateUnitAttributeModel:
    id: str


class Type(StrEnum):
    bed_room = "BedRoom"
    meeting_room = "MeetingRoom"
    event_space = "EventSpace"
    parking_lot = "ParkingLot"


@dataclass(frozen=True)
class CreateUnitGroupModel:
    code: str
    property_id: str
    name: dict[str, str]
    description: dict[str, str]
    max_persons: int
    rank: int | None = None
    type: Type | None = None
    connected_unit_groups: list[CreateConnectedUnitGroupModel] | None = None


@dataclass(frozen=True)
class CreateUnitModel:
    property_id: str
    name: str
    description: dict[str, str]
    max_persons: int
    unit_group_id: str | None = None
    condition: Condition | None = None
    attributes: list[CreateUnitAttributeModel] | None = None
    connected_units: list[CreateConnectedUnitModel] | None = None


@dataclass(frozen=True)
class EmbeddedPropertyModel:
    id: str
    code: str | None = None
    name: str | None = None
    description: str | None = None


class Type1(StrEnum):
    bed_room = "BedRoom"
    meeting_room = "MeetingRoom"
    event_space = "EventSpace"
    parking_lot = "ParkingLot"
    other = "Other"


@dataclass(frozen=True)
class EmbeddedUnitGroupModel:
    id: str
    code: str | None = None
    name: str | None = None
    description: str | None = None
    type: Type1 | None = None


@dataclass(frozen=True)
class EmbeddedUnitModel:
    id: str
    name: str | None = None
    description: str | None = None
    unit_group_id: str | None = None


@dataclass(frozen=True)
class MessageItemCollection:
    messages: list[str] | None = None


@dataclass(frozen=True)
class Operation:
    value: Any | None = None
    path: str | None = None
    op: str | None = None
    from_: str | None = None


@dataclass(frozen=True)
class PropertyCreatedModel(CreateUnitAttributeModel):
    pass


class Status(StrEnum):
    test = "Test"
    live = "Live"


@dataclass(frozen=True)
class ReplaceConnectedUnitGroupModel(CreateConnectedUnitGroupModel):
    pass


@dataclass(frozen=True)
class ReplaceUnitGroupModel:
    name: dict[str, str]
    description: dict[str, str]
    max_persons: int | None = None
    rank: int | None = None
    connected_unit_groups: list[ReplaceConnectedUnitGroupModel] | None = None


@dataclass(frozen=True)
class UnitAttributeDefinitionCreatedModel(CreateUnitAttributeModel):
    pass


@dataclass(frozen=True)
class UnitAttributeDefinitionModel:
    id: str
    name: str
    description: str | None = None


@dataclass(frozen=True)
class UnitAttributeModel(UnitAttributeDefinitionModel):
    pass


@dataclass(frozen=True)
class UnitCreatedModel(CreateUnitAttributeModel):
    pass


@dataclass(frozen=True)
class UnitGroupCreatedModel(CreateUnitAttributeModel):
    pass


@dataclass(frozen=True)
class UnitGroupItemModel:
    id: str
    code: str
    name: str
    description: str
    member_count: int
    type: Type1
    property: EmbeddedPropertyModel
    max_persons: int | None = None
    rank: int | None = None
    connected_unit_groups: list[ConnectedUnitGroupModel] | None = None


@dataclass(frozen=True)
class UnitGroupListModel:
    unit_groups: list[UnitGroupItemModel]
    count: int


@dataclass(frozen=True)
class UnitGroupModel:
    id: str
    code: str
    property: EmbeddedPropertyModel
    name: dict[str, str]
    member_count: int
    description: dict[str, str]
    max_persons: int
    type: Type1
    rank: int | None = None
    connected_unit_groups: list[ConnectedUnitGroupModel] | None = None


class Type4(StrEnum):
    out_of_service = "OutOfService"
    out_of_order = "OutOfOrder"
    out_of_inventory = "OutOfInventory"


@dataclass(frozen=True)
class UnitItemMaintenanceModel:
    id: str
    type: Type4


@dataclass(frozen=True)
class UnitItemStatusModel:
    is_occupied: bool
    condition: Condition
    maintenance: UnitItemMaintenanceModel | None = None


@dataclass(frozen=True)
class UnitMaintenanceModel:
    id: str
    from_: str
    to: str
    type: Type4
    description: str | None = None


@dataclass(frozen=True)
class UnitStatusModel:
    is_occupied: bool
    condition: Condition
    maintenance: UnitMaintenanceModel | None = None


class Action(StrEnum):
    delete = "Delete"
    archive = "Archive"
    set_live = "SetLive"
    reset = "Reset"


class Code(StrEnum):
    delete_not_allowed_for_property_not_in_status_test = (
        "DeleteNotAllowedForPropertyNotInStatusTest"
    )
    archive_not_allowed_for_property_not_in_status_live = (
        "ArchiveNotAllowedForPropertyNotInStatusLive"
    )
    archive_not_allowed_for_property_which_is_already_archived = (
        "ArchiveNotAllowedForPropertyWhichIsAlreadyArchived"
    )
    set_to_live_not_allowed_for_property_not_in_status_test = (
        "SetToLiveNotAllowedForPropertyNotInStatusTest"
    )
    set_to_live_not_allowed_for_property_in_non_live_account = (
        "SetToLiveNotAllowedForPropertyInNonLiveAccount"
    )
    reset_not_allowed_for_property_not_in_status_test = (
        "ResetNotAllowedForPropertyNotInStatusTest"
    )


@dataclass(frozen=True)
class ActionReasonModelNotAllowedPropertyActionReason:
    code: Code
    message: str


@dataclass(frozen=True)
class BulkCreateUnitsModel:
    units: list[CreateUnitModel]


@dataclass(frozen=True)
class UnitAttributeDefinitionListModel:
    unit_attributes: list[UnitAttributeDefinitionModel]
    count: int


@dataclass(frozen=True)
class UnitItemModel:
    id: str
    name: str
    description: str
    property: EmbeddedPropertyModel
    status: UnitItemStatusModel
    max_persons: int
    created: str
    unit_group: EmbeddedUnitGroupModel | None = None
    connecting_unit: EmbeddedUnitModel | None = None
    attributes: list[UnitAttributeModel] | None = None
    connected_units: list[ConnectedUnitModel] | None = None


@dataclass(frozen=True)
class UnitListModel:
    units: list[UnitItemModel]
    count: int


@dataclass(frozen=True)
class UnitModel:
    id: str
    name: str
    description: dict[str, str]
    property: EmbeddedPropertyModel
    status: UnitStatusModel
    max_persons: int
    created: str
    unit_group: EmbeddedUnitGroupModel | None = None
    connecting_unit: EmbeddedUnitModel | None = None
    attributes: list[UnitAttributeModel] | None = None
    connected_units: list[ConnectedUnitModel] | None = None


@dataclass(frozen=True)
class ActionModelPropertyActionNotAllowedPropertyActionReason:
    action: Action
    is_allowed: bool
    reasons: list[ActionReasonModelNotAllowedPropertyActionReason] | None = None


@dataclass(frozen=True)
class PropertyItemModel:
    id: str
    code: str
    is_template: bool
    name: str
    company_name: str
    commercial_register_entry: str
    tax_id: str
    location: AddressModel
    payment_terms: dict[str, str]
    time_zone: str
    currency_code: str
    created: str
    status: Status
    is_archived: bool
    property_template_id: str | None = None
    description: str | None = None
    managing_directors: str | None = None
    bank_account: BankAccountModel | None = None
    actions: list[ActionModelPropertyActionNotAllowedPropertyActionReason] | None = None


@dataclass(frozen=True)
class PropertyListModel:
    properties: list[PropertyItemModel]
    count: int


@dataclass(frozen=True)
class PropertyModel:
    id: str
    code: str
    is_template: bool
    name: dict[str, str]
    company_name: str
    commercial_register_entry: str
    tax_id: str
    location: AddressModel
    payment_terms: dict[str, str]
    time_zone: str
    currency_code: str
    created: str
    status: Status
    is_archived: bool
    property_template_id: str | None = None
    description: dict[str, str] | None = None
    managing_directors: str | None = None
    bank_account: BankAccountModel | None = None
    actions: list[ActionModelPropertyActionNotAllowedPropertyActionReason] | None = None
