# generated by datamodel-codegen:
#   filename:  core_v1_finance.json
#   timestamp: 2026-05-12T12:22:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any


class Command(StrEnum):
    post_charge = "PostCharge"
    post_payment = "PostPayment"
    move_line_item = "MoveLineItem"
    post_prepayment = "PostPrepayment"
    post_to_accounts_receivables = "PostToAccountsReceivables"
    post_prepayment_vat = "PostPrepaymentVat"
    post_to_loss_of_accounts_receivables = "PostToLossOfAccountsReceivables"
    system = "System"


class ReferenceType(StrEnum):
    house = "House"
    guest = "Guest"
    external = "External"
    booking = "Booking"


@dataclass(frozen=True)
class AddedChargeModel:
    id: str
    fee_charge_ids: list[str] | None = None


@dataclass(frozen=True)
class AddressModel:
    address_line1: str
    postal_code: str
    city: str
    country_code: str
    address_line2: str | None = None
    region_code: str | None = None


class ServiceType(StrEnum):
    other = "Other"
    accommodation = "Accommodation"
    food_and_beverages = "FoodAndBeverages"
    cancellation_fees = "CancellationFees"
    no_show = "NoShow"
    city_tax = "CityTax"
    second_city_tax = "SecondCityTax"


class VatType(StrEnum):
    null = "Null"
    very_reduced = "VeryReduced"
    reduced = "Reduced"
    normal = "Normal"
    without = "Without"
    special = "Special"
    special1 = "Special1"
    special2 = "Special2"
    reduced_covid19 = "ReducedCovid19"
    normal_covid19 = "NormalCovid19"
    mixed = "Mixed"


@dataclass(frozen=True)
class AmountModel:
    gross_amount: float
    net_amount: float
    vat_type: VatType
    vat_percent: float
    currency: str


@dataclass(frozen=True)
class BankAccountModel:
    iban: str | None = None
    bic: str | None = None
    bank: str | None = None


@dataclass(frozen=True)
class BulkAllowanceCreatedItemModel:
    id: str
    source_charge_id: str


@dataclass(frozen=True)
class BulkAllowanceCreatedModel:
    items: list[BulkAllowanceCreatedItemModel]


@dataclass(frozen=True)
class BulkMoveItemRequest:
    source_folio_id: str
    target_folio_id: str
    charge_ids: list[str] | None = None


@dataclass(frozen=True)
class BulkMoveRequest:
    items: list[BulkMoveItemRequest]
    reason: str


class ReasonCode(StrEnum):
    change_of_recipient_details = "ChangeOfRecipientDetails"
    change_of_invoice_recipient = "ChangeOfInvoiceRecipient"
    change_of_payment_method = "ChangeOfPaymentMethod"
    change_of_invoice_transactions = "ChangeOfInvoiceTransactions"
    other = "Other"


@dataclass(frozen=True)
class CancelInvoiceRequest:
    reason_code: ReasonCode


class Type(StrEnum):
    direct = "Direct"
    time_slice = "TimeSlice"
    included_service = "IncludedService"
    extra_service = "ExtraService"
    city_tax = "CityTax"
    no_show_fee = "NoShowFee"
    cancellation_fee = "CancellationFee"
    service_fee = "ServiceFee"
    tax = "Tax"
    second_city_tax = "SecondCityTax"


@dataclass(frozen=True)
class CommercialInfoModel:
    register_entry: str
    tax_id: str
    managing_directors: str | None = None


@dataclass(frozen=True)
class CorrectFolioRequest:
    reason: str
    charge_ids: list[str] | None = None
    allowance_ids: list[str] | None = None
    transitory_charge_ids: list[str] | None = None


@dataclass(frozen=True)
class CountModel:
    count: int


class AccountOwner(StrEnum):
    guest = "Guest"
    booker = "Booker"


class ServiceType2(StrEnum):
    other = "Other"
    accommodation = "Accommodation"
    food_and_beverages = "FoodAndBeverages"
    city_tax = "CityTax"
    second_city_tax = "SecondCityTax"


class ReferenceType1(StrEnum):
    psp_reference = "PspReference"
    authorization_id = "AuthorizationId"


class Method(StrEnum):
    cash = "Cash"
    bank_transfer = "BankTransfer"
    credit_card = "CreditCard"
    amex = "Amex"
    visa_credit = "VisaCredit"
    visa_debit = "VisaDebit"
    master_card = "MasterCard"
    master_card_debit = "MasterCardDebit"
    maestro = "Maestro"
    giro_card = "GiroCard"
    discover_card = "DiscoverCard"
    diners = "Diners"
    jcb = "Jcb"
    booking_com = "BookingCom"
    v_pay = "VPay"
    pay_pal = "PayPal"
    postcard = "Postcard"
    reka = "Reka"
    twint = "Twint"
    lunchcheck = "Lunchcheck"
    voucher = "Voucher"
    china_union_pay = "ChinaUnionPay"
    other = "Other"
    cheque = "Cheque"
    airbnb = "Airbnb"
    holiday_check = "HolidayCheck"
    representation = "Representation"
    i_deal = "IDeal"


class Type1(StrEnum):
    guest = "Guest"
    external = "External"


@dataclass(frozen=True)
class CreateInvoiceRequest:
    folio_id: str
    language_code: str


class Type2(StrEnum):
    invoice_already_exists = "InvoiceAlreadyExists"
    not_all_charges_posted = "NotAllChargesPosted"
    debitor_details_missing = "DebitorDetailsMissing"
    invoice_has_pending_payments = "InvoiceHasPendingPayments"
    no_company_found = "NoCompanyFound"
    company_cannot_check_out_on_ar = "CompanyCannotCheckOutOnAr"
    is_house_folio = "IsHouseFolio"
    cannot_create_company_invoice_for_external = "CannotCreateCompanyInvoiceForExternal"
    check_out_on_ar_is_not_allowed = "CheckOutOnArIsNotAllowed"
    is_empty_folio = "IsEmptyFolio"
    cash_payment_limit_exceeded = "CashPaymentLimitExceeded"
    folio_state = "FolioState"


@dataclass(frozen=True)
class CreateInvoiceWarningModel:
    type: Type2
    message: str | None = None


@dataclass(frozen=True)
class CreateRoutingFilterModel:
    folio_ids: list[str] | None = None
    sub_account_ids: list[str] | None = None
    service_types: list[ServiceType] | None = None
    service_ids: list[str] | None = None
    from_: str | None = None
    to: str | None = None


@dataclass(frozen=True)
class CreateRoutingModel:
    booking_id: str
    property_id: str
    destination_folio_id: str
    filter: CreateRoutingFilterModel | None = None


@dataclass(frozen=True)
class CreatedSubResourceIdModel:
    id: str


@dataclass(frozen=True)
class CurrencyListModel:
    iso_currencies: list[str]


@dataclass(frozen=True)
class EmbeddedCompanyModel:
    id: str
    code: str | None = None
    name: str | None = None
    can_check_out_on_ar: bool | None = None


@dataclass(frozen=True)
class EmbeddedFolioModel:
    id: str
    debitor: str | None = None


@dataclass(frozen=True)
class EmbeddedInvoiceModel(CreatedSubResourceIdModel):
    pass


@dataclass(frozen=True)
class EmbeddedPropertyModel:
    id: str
    code: str | None = None
    name: str | None = None
    description: str | None = None


@dataclass(frozen=True)
class EmbeddedReservationModel:
    id: str
    booking_id: str


class Type3(StrEnum):
    revenues = "Revenues"
    payments = "Payments"
    liabilities = "Liabilities"
    receivables = "Receivables"
    vat = "Vat"
    house = "House"
    accounts_receivable = "AccountsReceivable"
    city_taxes = "CityTaxes"
    transitory_items = "TransitoryItems"
    vat_on_liabilities = "VatOnLiabilities"
    loss_of_accounts_receivable = "LossOfAccountsReceivable"
    second_city_tax = "SecondCityTax"


@dataclass(frozen=True)
class ExportAccountModel:
    name: str
    number: str
    type: Type3
    parent_number: str | None = None


@dataclass(frozen=True)
class ExternalReference:
    merchant_reference: str
    psp_reference: str


@dataclass(frozen=True)
class FolioCreatedModel(CreatedSubResourceIdModel):
    pass


class Type5(StrEnum):
    booker = "Booker"
    primary_guest = "PrimaryGuest"
    company = "Company"
    additional_guest = "AdditionalGuest"
    property = "Property"


class Title(StrEnum):
    mr = "Mr"
    ms = "Ms"
    dr = "Dr"
    prof = "Prof"
    mrs = "Mrs"
    other = "Other"


class FolioWarning(StrEnum):
    incomplete_billing_address = "IncompleteBillingAddress"
    incomplete_billing_details = "IncompleteBillingDetails"


class AllowedAction(StrEnum):
    add_charge = "AddCharge"
    add_deposit_item = "AddDepositItem"
    add_allowance = "AddAllowance"
    add_cancellation_fee = "AddCancellationFee"
    add_no_show_fee = "AddNoShowFee"
    add_payment = "AddPayment"
    add_refund = "AddRefund"
    checkout_on_ar = "CheckoutOnAr"
    close = "Close"
    post_open_charges = "PostOpenCharges"
    correct_folio = "CorrectFolio"
    change_address = "ChangeAddress"
    change_address_with_simple_debitor = "ChangeAddressWithSimpleDebitor"
    delete = "Delete"
    reopen = "Reopen"
    create_invoice = "CreateInvoice"
    create_advance_invoice = "CreateAdvanceInvoice"
    cancel_last_invoice = "CancelLastInvoice"
    create_invoice_with_simple_debitor = "CreateInvoiceWithSimpleDebitor"
    create_prepayment_notice = "CreatePrepaymentNotice"
    create_pro_forma_invoice = "CreateProFormaInvoice"
    create_deposit_receipt = "CreateDepositReceipt"
    preview_invoice = "PreviewInvoice"


class Status(StrEnum):
    open = "Open"
    closed = "Closed"
    closed_with_invoice = "ClosedWithInvoice"


class Method2(StrEnum):
    cash = "Cash"
    bank_transfer = "BankTransfer"
    credit_card = "CreditCard"
    invoice = "Invoice"
    amex = "Amex"
    visa_credit = "VisaCredit"
    visa_debit = "VisaDebit"
    master_card = "MasterCard"
    master_card_debit = "MasterCardDebit"
    maestro = "Maestro"
    giro_card = "GiroCard"
    discover_card = "DiscoverCard"
    diners = "Diners"
    jcb = "Jcb"
    booking_com = "BookingCom"
    v_pay = "VPay"
    pay_pal = "PayPal"
    postcard = "Postcard"
    reka = "Reka"
    twint = "Twint"
    lunchcheck = "Lunchcheck"
    voucher = "Voucher"
    china_union_pay = "ChinaUnionPay"
    other = "Other"
    cheque = "Cheque"
    airbnb = "Airbnb"
    holiday_check = "HolidayCheck"
    psp_cash = "PspCash"
    psp_debit = "PspDebit"
    psp_banking = "PspBanking"
    psp_open_invoice = "PspOpenInvoice"
    psp_wallet = "PspWallet"
    representation = "Representation"
    i_deal = "IDeal"


class Status2(StrEnum):
    pending = "Pending"
    success = "Success"
    failure = "Failure"
    canceled = "Canceled"


class FailureCode(StrEnum):
    failed = "Failed"
    timed_out = "TimedOut"


class Type8(StrEnum):
    custom = "Custom"
    terminal = "Terminal"
    payment_account = "PaymentAccount"
    authorization = "Authorization"
    payment_link = "PaymentLink"
    pre_authorization = "PreAuthorization"


@dataclass(frozen=True)
class InvoiceCreatedModel(CreatedSubResourceIdModel):
    pass


class Type9(StrEnum):
    initial = "Initial"
    cancellation = "Cancellation"
    correction = "Correction"
    advance = "Advance"
    advance_cancellation = "AdvanceCancellation"
    advance_correction = "AdvanceCorrection"
    proforma = "Proforma"


class Status3(StrEnum):
    fully_paid = "FullyPaid"
    unpaid = "Unpaid"
    written_off = "WrittenOff"


class AllowedAction2(StrEnum):
    correct_address = "CorrectAddress"
    correct_charges = "CorrectCharges"
    mark_as_paid = "MarkAsPaid"
    cancel = "Cancel"
    write_off = "WriteOff"


class Network(StrEnum):
    peppol = "Peppol"


@dataclass(frozen=True)
class InvoiceNetworkIdentityModel:
    network: Network
    id: str


@dataclass(frozen=True)
class InvoiceSenderModel:
    name: str
    address: AddressModel | None = None


@dataclass(frozen=True)
class MessageItemCollection:
    messages: list[str] | None = None


@dataclass(frozen=True)
class MonetaryValueModel:
    amount: float
    currency: str


@dataclass(frozen=True)
class MoveAllChargesRequest:
    target_folio_id: str
    reason: str


@dataclass(frozen=True)
class MoveChargesRequest:
    target_folio_id: str
    reason: str
    charge_ids: list[str] | None = None
    allowance_ids: list[str] | None = None
    transitory_charge_ids: list[str] | None = None


@dataclass(frozen=True)
class MovePaymentsRequest:
    target_folio_id: str
    reason: str
    payment_ids: list[str]


@dataclass(frozen=True)
class NonStrictAddressModel:
    address_line1: str | None = None
    address_line2: str | None = None
    postal_code: str | None = None
    city: str | None = None
    region_code: str | None = None
    country_code: str | None = None


@dataclass(frozen=True)
class Operation:
    value: Any | None = None
    path: str | None = None
    op: str | None = None
    from_: str | None = None


@dataclass(frozen=True)
class PayInvoiceRequest:
    payment_method: Method
    receipt: str


@dataclass(frozen=True)
class PaymentCreatedModel(CreatedSubResourceIdModel):
    pass


@dataclass(frozen=True)
class PaymentMethodListModel:
    payment_methods: list[Method]


@dataclass(frozen=True)
class PaymentModel:
    id: str
    method: Method2
    amount: MonetaryValueModel
    business_date: str
    external_reference: ExternalReference | None = None
    receipt: str | None = None
    payment_date: str | None = None
    moved_from: EmbeddedFolioModel | None = None
    moved_to: EmbeddedFolioModel | None = None
    moved_reason: str | None = None
    source_payment_id: str | None = None


@dataclass(frozen=True)
class PaymentPaidChargesRequest:
    charge_id: str
    amount: float


@dataclass(frozen=True)
class PendingPaymentModel:
    id: str
    amount: MonetaryValueModel
    terminal_id: str | None = None


@dataclass(frozen=True)
class PreciseMonetaryValueModel(MonetaryValueModel):
    pass


class CreateInvoiceAction(StrEnum):
    cannot_create_invoice = "CannotCreateInvoice"
    creates_invoice = "CreatesInvoice"
    creates_invoice_and_closes_folio = "CreatesInvoiceAndClosesFolio"
    creates_ar_invoice_and_closes_folio = "CreatesArInvoiceAndClosesFolio"


class Type11(StrEnum):
    custom = "Custom"
    reservation = "Reservation"
    invoice = "Invoice"
    psp_reference = "PspReference"


@dataclass(frozen=True)
class ReceiptModel:
    number: str
    type: Type11 | None = None


@dataclass(frozen=True)
class RefundCreatedModel(CreatedSubResourceIdModel):
    pass


@dataclass(frozen=True)
class RefundModel:
    id: str
    method: Method2
    amount: MonetaryValueModel
    refund_date: str
    status: Status2
    business_date: str
    external_reference: ExternalReference | None = None
    receipt: str | None = None
    source_payment_id: str | None = None
    failure_reason: str | None = None
    failure_code: FailureCode | None = None
    moved_from: EmbeddedFolioModel | None = None
    moved_to: EmbeddedFolioModel | None = None
    moved_reason: str | None = None
    reason: str | None = None


@dataclass(frozen=True)
class RoutingCreatedModel(CreatedSubResourceIdModel):
    pass


@dataclass(frozen=True)
class RoutingFolioModel:
    id: str
    debitor_type: Type5 | None = None


@dataclass(frozen=True)
class RoutingServiceModel:
    id: str
    name: str


@dataclass(frozen=True)
class RoutingSubAccountModel(RoutingServiceModel):
    pass


@dataclass(frozen=True)
class ServiceTypeListModel:
    service_types: list[ServiceType]


class Type13(StrEnum):
    by_percent = "ByPercent"
    by_amount = "ByAmount"


@dataclass(frozen=True)
class SplitChargeRequest:
    type: Type13
    percent: float | None = None
    amount: MonetaryValueModel | None = None


@dataclass(frozen=True)
class SplitChargeResult:
    allowance_id: str
    first_charge_id: str
    second_charge_id: str


@dataclass(frozen=True)
class SplitPaymentRequest(SplitChargeRequest):
    pass


@dataclass(frozen=True)
class SplitPaymentResult:
    refund_id: str | None = None
    first_payment_id: str | None = None
    second_payment_id: str | None = None


@dataclass(frozen=True)
class StayInfoModel:
    guest_name: str
    arrival_date: str
    departure_date: str
    reservation_id: str
    room_number: str | None = None


@dataclass(frozen=True)
class TaxAmountModel:
    type: VatType
    percent: float
    amount: float


@dataclass(frozen=True)
class TaxDetailModel:
    vat_type: VatType
    vat_percent: float
    net: MonetaryValueModel
    tax: MonetaryValueModel


@dataclass(frozen=True)
class TransitoryChargeModel:
    id: str
    name: str
    amount: MonetaryValueModel
    service_date: str
    created: str
    quantity: int
    service_type: ServiceType | None = None
    receipt: str | None = None
    moved_from: EmbeddedFolioModel | None = None
    moved_to: EmbeddedFolioModel | None = None
    moved_reason: str | None = None


@dataclass(frozen=True)
class VatItemModel:
    type: VatType
    percent: float


@dataclass(frozen=True)
class VatListModel:
    vat_types: list[VatItemModel] | None = None


class Action(StrEnum):
    cancel = "Cancel"
    online_refund = "OnlineRefund"
    manual_refund = "ManualRefund"


class Action1(StrEnum):
    delete = "Delete"
    modify = "Modify"


class Code(StrEnum):
    cancel_not_allowed_for_payment_not_in_status_pending = (
        "CancelNotAllowedForPaymentNotInStatusPending"
    )
    cancel_not_allowed_for_payment_not_of_payment_link_type = (
        "CancelNotAllowedForPaymentNotOfPaymentLinkType"
    )
    online_refund_not_allowed_for_restricted_payment_method_or_acquirer = (
        "OnlineRefundNotAllowedForRestrictedPaymentMethodOrAcquirer"
    )
    manual_refund_not_allowed_when_online_refund_is_possible = (
        "ManualRefundNotAllowedWhenOnlineRefundIsPossible"
    )
    cancel_not_allowed_for_incomplete_payment_link = (
        "CancelNotAllowedForIncompletePaymentLink"
    )


@dataclass(frozen=True)
class ActionReasonModelNotAllowedPaymentActionReason:
    code: Code
    message: str


class Code1(StrEnum):
    delete_not_allowed_for_destination_folio_closed = (
        "DeleteNotAllowedForDestinationFolioClosed"
    )
    delete_not_allowed_for_destination_folio_with_advance_invoice = (
        "DeleteNotAllowedForDestinationFolioWithAdvanceInvoice"
    )
    delete_not_allowed_for_destination_folio_with_moved_out_routed_charges = (
        "DeleteNotAllowedForDestinationFolioWithMovedOutRoutedCharges"
    )
    delete_not_allowed_for_source_folios_closed = (
        "DeleteNotAllowedForSourceFoliosClosed"
    )
    delete_not_allowed_for_source_folios_with_advance_invoice = (
        "DeleteNotAllowedForSourceFoliosWithAdvanceInvoice"
    )
    modify_not_allowed_for_destination_folio_closed = (
        "ModifyNotAllowedForDestinationFolioClosed"
    )
    modify_not_allowed_for_destination_folio_with_advance_invoice = (
        "ModifyNotAllowedForDestinationFolioWithAdvanceInvoice"
    )
    modify_not_allowed_for_source_folios_with_advance_invoice = (
        "ModifyNotAllowedForSourceFoliosWithAdvanceInvoice"
    )
    modify_not_allowed_for_destination_folio_with_moved_out_routed_charges = (
        "ModifyNotAllowedForDestinationFolioWithMovedOutRoutedCharges"
    )
    delete_not_allowed_for_source_folios_with_pending_invoice = (
        "DeleteNotAllowedForSourceFoliosWithPendingInvoice"
    )
    delete_not_allowed_for_destination_folio_with_pending_invoice = (
        "DeleteNotAllowedForDestinationFolioWithPendingInvoice"
    )
    modify_not_allowed_for_source_folios_with_pending_invoice = (
        "ModifyNotAllowedForSourceFoliosWithPendingInvoice"
    )
    modify_not_allowed_for_destination_folio_with_pending_invoice = (
        "ModifyNotAllowedForDestinationFolioWithPendingInvoice"
    )


@dataclass(frozen=True)
class ActionReasonModelNotAllowedRoutingActionReason:
    code: Code1
    message: str


@dataclass(frozen=True)
class AccountingTransactionModel:
    timestamp: str
    date: str
    debited_account: ExportAccountModel
    credited_account: ExportAccountModel
    command: Command
    amount: PreciseMonetaryValueModel
    entry_number: str
    reference: str
    reference_type: ReferenceType
    entry_group_number: str
    receipt: ReceiptModel | None = None


@dataclass(frozen=True)
class AccountingTransactionPairModel:
    debited_account: ExportAccountModel
    credited_account: ExportAccountModel
    amount: PreciseMonetaryValueModel


@dataclass(frozen=True)
class AggregateTransactionItemModel:
    account: ExportAccountModel
    credited_amount: PreciseMonetaryValueModel
    debited_amount: PreciseMonetaryValueModel
    balance: PreciseMonetaryValueModel


@dataclass(frozen=True)
class AggregatesTotalModel:
    credited_amount: PreciseMonetaryValueModel
    debited_amount: PreciseMonetaryValueModel
    balance: PreciseMonetaryValueModel


@dataclass(frozen=True)
class AllowanceModel:
    id: str
    amount: AmountModel
    reason: str
    service_type: ServiceType
    service_date: str
    created: str
    moved_from: EmbeddedFolioModel | None = None
    moved_to: EmbeddedFolioModel | None = None
    moved_reason: str | None = None
    source_charge_id: str | None = None
    sub_account_id: str | None = None


@dataclass(frozen=True)
class ChargeModel:
    id: str
    service_type: ServiceType
    name: str
    is_posted: bool
    service_date: str
    created: str
    amount: AmountModel
    quantity: int
    type: Type
    translated_names: dict[str, str] | None = None
    moved_from: EmbeddedFolioModel | None = None
    moved_to: EmbeddedFolioModel | None = None
    moved_reason: str | None = None
    routed_from: EmbeddedFolioModel | None = None
    routed_to: EmbeddedFolioModel | None = None
    receipt: str | None = None
    group_id: str | None = None
    sub_account_id: str | None = None


@dataclass(frozen=True)
class CompanyInfoModel:
    name: str
    tax_id: str | None = None
    additional_tax_id: str | None = None
    additional_tax_id2: str | None = None
    invoice_network_identity: InvoiceNetworkIdentityModel | None = None


@dataclass(frozen=True)
class CreateAccountPaymentRequest:
    amount: MonetaryValueModel
    account_owner: AccountOwner | None = None
    payment_account_id: str | None = None
    paid_charges: list[PaymentPaidChargesRequest] | None = None


@dataclass(frozen=True)
class CreateAllowanceBulkItemModel:
    charge_id: str
    amount: MonetaryValueModel


@dataclass(frozen=True)
class CreateAllowanceBulkModel:
    items: list[CreateAllowanceBulkItemModel]
    reason: str
    business_date: str | None = None


@dataclass(frozen=True)
class CreateAllowanceForChargeModel:
    reason: str
    amount: MonetaryValueModel
    business_date: str | None = None


@dataclass(frozen=True)
class CreateAllowanceForFolioModel:
    service_type: ServiceType2
    vat_type: VatType
    reason: str
    amount: MonetaryValueModel
    sub_account_id: str | None = None
    business_date: str | None = None


@dataclass(frozen=True)
class CreateAuthorizationPaymentRequest:
    transaction_reference: str
    amount: MonetaryValueModel
    reference_type: ReferenceType1 | None = None
    paid_charges: list[PaymentPaidChargesRequest] | None = None


@dataclass(frozen=True)
class CreateChargeModel:
    service_type: ServiceType2
    vat_type: VatType
    name: str
    amount: MonetaryValueModel
    sub_account_id: str | None = None
    receipt: str | None = None
    quantity: int | None = None
    business_date: str | None = None


@dataclass(frozen=True)
class CreateCustomPaymentRequest:
    method: Method
    amount: MonetaryValueModel
    receipt: str | None = None
    business_date: str | None = None
    paid_charges: list[PaymentPaidChargesRequest] | None = None


@dataclass(frozen=True)
class CreateFolioRefundRequest:
    method: Method
    amount: MonetaryValueModel
    receipt: str | None = None
    business_date: str | None = None
    reason: str | None = None


@dataclass(frozen=True)
class CreatePaymentLinkRequest:
    expires_at: str
    country_code: str
    amount: MonetaryValueModel
    description: str | None = None
    payer_email: str | None = None
    paid_charges: list[PaymentPaidChargesRequest] | None = None


@dataclass(frozen=True)
class CreatePaymentRefundRequest:
    amount: MonetaryValueModel
    business_date: str | None = None
    reason: str | None = None


@dataclass(frozen=True)
class CreateTerminalPaymentRequest:
    terminal_id: str
    amount: MonetaryValueModel
    paid_charges: list[PaymentPaidChargesRequest] | None = None


@dataclass(frozen=True)
class CreateTransitoryChargeModel:
    name: str
    amount: MonetaryValueModel
    receipt: str | None = None
    group_id: str | None = None
    service_type: ServiceType2 | None = None
    quantity: int | None = None
    business_date: str | None = None


@dataclass(frozen=True)
class ExportGrossTransactionItemModel:
    timestamp: str
    date: str
    debited_account: ExportAccountModel
    credited_account: ExportAccountModel
    command: Command
    currency: str
    gross_amount: float
    net_amount: float
    receipt: ReceiptModel
    source_entry_number: str
    reference: str
    reference_type: ReferenceType
    taxes: list[TaxAmountModel] | None = None


@dataclass(frozen=True)
class ExportGrossTransactionListModel:
    transactions: list[ExportGrossTransactionItemModel]


@dataclass(frozen=True)
class FinanceAccountModel:
    account_number: str
    name: str
    type: Type3
    has_children: bool
    is_archived: bool
    parent_number: str | None = None
    transactions: list[AccountingTransactionModel] | None = None


@dataclass(frozen=True)
class FolioDebitorModel:
    type: Type5 | None = None
    title: Title | None = None
    first_name: str | None = None
    name: str | None = None
    address: NonStrictAddressModel | None = None
    company: CompanyInfoModel | None = None
    personal_tax_id: str | None = None
    reference: str | None = None
    email: str | None = None
    phone: str | None = None


@dataclass(frozen=True)
class FolioItemModel:
    id: str
    created: str
    updated: str
    balance: MonetaryValueModel
    status: Status
    type: ReferenceType | None = None
    debitor: FolioDebitorModel | None = None
    closing_date: str | None = None
    is_main_folio: bool | None = None
    is_empty: bool | None = None
    reservation: EmbeddedReservationModel | None = None
    booking_id: str | None = None
    company: EmbeddedCompanyModel | None = None
    checked_out_on_accounts_receivable: bool | None = None
    folio_warnings: list[FolioWarning] | None = None
    allowed_actions: list[AllowedAction] | None = None
    related_invoices: list[EmbeddedInvoiceModel] | None = None
    charges: list[ChargeModel] | None = None
    allowances: list[AllowanceModel] | None = None
    transitory_charges: list[TransitoryChargeModel] | None = None
    payments: list[PaymentModel] | None = None


@dataclass(frozen=True)
class FolioListModel:
    folios: list[FolioItemModel]
    count: int


@dataclass(frozen=True)
class FolioModel:
    id: str
    created: str
    updated: str
    property: EmbeddedPropertyModel
    balance: MonetaryValueModel
    status: Status
    type: ReferenceType | None = None
    debitor: FolioDebitorModel | None = None
    closing_date: str | None = None
    reservation: EmbeddedReservationModel | None = None
    booking_id: str | None = None
    company: EmbeddedCompanyModel | None = None
    charges: list[ChargeModel] | None = None
    transitory_charges: list[TransitoryChargeModel] | None = None
    payments: list[PaymentModel] | None = None
    pending_payments: list[PendingPaymentModel] | None = None
    allowances: list[AllowanceModel] | None = None
    checked_out_on_accounts_receivable: bool | None = None
    is_main_folio: bool | None = None
    is_empty: bool | None = None
    related_folios: list[EmbeddedFolioModel] | None = None
    related_invoices: list[EmbeddedInvoiceModel] | None = None
    folio_warnings: list[FolioWarning] | None = None
    allowed_actions: list[AllowedAction] | None = None
    allowed_payment: float | None = None
    maximum_allowance: float | None = None


@dataclass(frozen=True)
class IncludedLineItemModel:
    price: MonetaryValueModel
    description: str | None = None
    vat_type: VatType | None = None
    vat_percent: float | None = None


@dataclass(frozen=True)
class InvoiceItemModel:
    id: str
    number: str
    type: Type9
    language_code: str
    folio_id: str
    property_id: str
    sub_total: MonetaryValueModel
    payment_settled: bool
    status: Status3
    created: str
    series: str | None = None
    reservation_id: str | None = None
    booking_id: str | None = None
    related_invoice_number: str | None = None
    write_off_reason: str | None = None
    cancellation_reason_code: ReasonCode | None = None
    outstanding_payment: MonetaryValueModel | None = None
    guest_name: str | None = None
    guest_company: str | None = None
    allowed_actions: list[AllowedAction2] | None = None
    company: EmbeddedCompanyModel | None = None


@dataclass(frozen=True)
class InvoiceLineItemModel:
    date: str
    description: str
    price: MonetaryValueModel
    is_no_show_fee: bool
    vat_type: VatType | None = None
    vat_percent: float | None = None
    included_line_items: list[IncludedLineItemModel] | None = None
    guest: str | None = None
    quantity: int | None = None


@dataclass(frozen=True)
class InvoiceLineItemsModel:
    sub_total: MonetaryValueModel
    line_items: list[InvoiceLineItemModel] | None = None


@dataclass(frozen=True)
class InvoiceListModel:
    invoices: list[InvoiceItemModel]
    count: int


@dataclass(frozen=True)
class InvoicePaymentModel:
    id: str
    method: Method2
    method_name: str
    amount: MonetaryValueModel
    payment_date: str | None = None
    business_date: str | None = None


@dataclass(frozen=True)
class InvoiceRecipientModel:
    name: str | None = None
    address: NonStrictAddressModel | None = None
    company_name: str | None = None
    company_tax_id: str | None = None
    reference: str | None = None
    personal_tax_id: str | None = None


@dataclass(frozen=True)
class PreviewInvoiceModel:
    create_invoice_action: CreateInvoiceAction
    invoice_date: str
    folio_id: str
    from_: InvoiceSenderModel
    commercial_information: CommercialInfoModel
    line_items: InvoiceLineItemsModel
    total: MonetaryValueModel
    property_id: str
    property_country_code: str
    language_code: str
    to: InvoiceRecipientModel | None = None
    create_invoice_warning: CreateInvoiceWarningModel | None = None
    bank_account: BankAccountModel | None = None
    payment_terms: str | None = None
    payments: list[InvoicePaymentModel] | None = None
    outstanding_payment: MonetaryValueModel | None = None
    tax_details: list[TaxDetailModel] | None = None
    stay_info: StayInfoModel | None = None
    company: EmbeddedCompanyModel | None = None


@dataclass(frozen=True)
class RefundListModel:
    refunds: list[RefundModel]
    count: int


@dataclass(frozen=True)
class RoutingFilterModel:
    folio_ids: list[str] | None = None
    sub_accounts: list[RoutingSubAccountModel] | None = None
    service_types: list[ServiceType] | None = None
    services: list[RoutingServiceModel] | None = None
    from_: str | None = None
    to: str | None = None


@dataclass(frozen=True)
class SlimFinanceAccountModel:
    account_number: str
    name: str
    type: Type3
    has_children: bool
    is_archived: bool
    parent_number: str | None = None
    vat: VatItemModel | None = None
    sub_accounts: list[SlimFinanceAccountModel] | None = None


@dataclass(frozen=True)
class ActionModelPaymentActionNotAllowedPaymentActionReason:
    action: Action
    is_allowed: bool
    reasons: list[ActionReasonModelNotAllowedPaymentActionReason] | None = None


@dataclass(frozen=True)
class ActionModelRoutingActionNotAllowedRoutingActionReason:
    action: Action1
    is_allowed: bool
    reasons: list[ActionReasonModelNotAllowedRoutingActionReason] | None = None


@dataclass(frozen=True)
class AccountingTransactionListModel:
    transactions: list[AccountingTransactionModel]


@dataclass(frozen=True)
class AccountingTransactionPairListModel:
    account_transaction_pairs: list[AccountingTransactionPairModel]


@dataclass(frozen=True)
class AggregateTransactionListModel:
    aggregations: list[AggregateTransactionItemModel]
    total: AggregatesTotalModel


@dataclass(frozen=True)
class ChartOfAccountsModel:
    global_accounts: list[SlimFinanceAccountModel]
    guest_accounts: list[SlimFinanceAccountModel]
    external_accounts: list[SlimFinanceAccountModel]
    booking_accounts: list[SlimFinanceAccountModel]


@dataclass(frozen=True)
class CreateFolioModel:
    debitor: FolioDebitorModel
    reservation_id: str | None = None
    company_id: str | None = None
    type: Type1 | None = None
    property_id: str | None = None
    code: str | None = None


@dataclass(frozen=True)
class FinanceAccountListModel:
    accounts: list[SlimFinanceAccountModel]
    count: int


@dataclass(frozen=True)
class FolioPaymentModel:
    id: str
    amount: MonetaryValueModel
    payment_date: str
    status: Status2
    type: Type8
    business_date: str
    method: Method2 | None = None
    external_reference: ExternalReference | None = None
    receipt: str | None = None
    moved_from: EmbeddedFolioModel | None = None
    moved_to: EmbeddedFolioModel | None = None
    moved_reason: str | None = None
    source_payment_id: str | None = None
    failure_reason: str | None = None
    failure_code: FailureCode | None = None
    expires_at: str | None = None
    description: str | None = None
    url: str | None = None
    actions: list[ActionModelPaymentActionNotAllowedPaymentActionReason] | None = None


@dataclass(frozen=True)
class InvoiceModel:
    id: str
    number: str
    type: Type9
    to: InvoiceRecipientModel
    payment_settled: bool
    status: Status3
    created: str
    invoice_date: str
    folio_id: str
    from_: InvoiceSenderModel
    commercial_information: CommercialInfoModel
    line_items: InvoiceLineItemsModel
    total: MonetaryValueModel
    property_id: str
    property_country_code: str
    language_code: str
    series: str | None = None
    related_invoice_number: str | None = None
    write_off_reason: str | None = None
    cancellation_reason_code: ReasonCode | None = None
    allowed_actions: list[AllowedAction2] | None = None
    bank_account: BankAccountModel | None = None
    payment_terms: str | None = None
    payments: list[InvoicePaymentModel] | None = None
    outstanding_payment: MonetaryValueModel | None = None
    tax_details: list[TaxDetailModel] | None = None
    stay_info: StayInfoModel | None = None
    company: EmbeddedCompanyModel | None = None


@dataclass(frozen=True)
class PaymentListModel:
    payments: list[FolioPaymentModel]
    count: int


@dataclass(frozen=True)
class RoutingModel:
    id: str
    booking_id: str
    property_id: str
    destination_folio: RoutingFolioModel
    filter: RoutingFilterModel | None = None
    actions: list[ActionModelRoutingActionNotAllowedRoutingActionReason] | None = None


@dataclass(frozen=True)
class RoutingListModel:
    routings: list[RoutingModel]
    count: int
