# generated by datamodel-codegen:
#   filename:  core_v1_booking.json
#   timestamp: 2026-05-12T12:24:41+00:00

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any


@dataclass(frozen=True)
class AllowedValueListModel:
    allowed_values: list[str]
    count: int


class VatType(StrEnum):
    null = "Null"
    very_reduced = "VeryReduced"
    reduced = "Reduced"
    normal = "Normal"
    without = "Without"
    special = "Special"
    special1 = "Special1"
    special2 = "Special2"
    reduced_covid19 = "ReducedCovid19"
    normal_covid19 = "NormalCovid19"
    mixed = "Mixed"


@dataclass(frozen=True)
class AmountModel:
    gross_amount: float
    net_amount: float
    vat_type: VatType
    vat_percent: float
    currency: str


@dataclass(frozen=True)
class AuthorizationCreatedModel:
    id: str


class Status(StrEnum):
    pending = "Pending"
    success = "Success"
    failure = "Failure"
    canceled = "Canceled"
    expired = "Expired"
    refresh_pending = "RefreshPending"


class PayerInteraction(StrEnum):
    terminal = "Terminal"
    payment_account = "PaymentAccount"
    authorization = "Authorization"
    payment_link = "PaymentLink"


class Type(StrEnum):
    booking = "Booking"
    reservation = "Reservation"


@dataclass(frozen=True)
class AuthorizationTargetModel:
    type: Type
    id: str
    property_id: str


@dataclass(frozen=True)
class BlockCreatedModel(AuthorizationCreatedModel):
    pass


class Status1(StrEnum):
    tentative = "Tentative"
    definite = "Definite"
    canceled = "Canceled"


class Title(StrEnum):
    mr = "Mr"
    ms = "Ms"
    dr = "Dr"
    prof = "Prof"
    mrs = "Mrs"
    other = "Other"


class Gender(StrEnum):
    female = "Female"
    male = "Male"
    other = "Other"
    unknown = "Unknown"


class IdentificationType(StrEnum):
    social_insurance_number = "SocialInsuranceNumber"
    passport_number = "PassportNumber"
    id_number = "IdNumber"
    driver_license_number = "DriverLicenseNumber"
    visa_number = "VisaNumber"
    foreigner_identity_number = "ForeignerIdentityNumber"
    tax_identification_number = "TaxIdentificationNumber"
    other = "Other"


class Status3(StrEnum):
    confirmed = "Confirmed"
    in_house = "InHouse"
    checked_out = "CheckedOut"
    canceled = "Canceled"
    no_show = "NoShow"


class ChannelCode(StrEnum):
    direct = "Direct"
    booking_com = "BookingCom"
    ibe = "Ibe"
    channel_manager = "ChannelManager"
    expedia = "Expedia"
    homelike = "Homelike"
    hrs = "Hrs"
    alto_vita = "AltoVita"
    des_vu = "DesVu"


@dataclass(frozen=True)
class CountModel:
    count: int


@dataclass(frozen=True)
class CreateBlockTimeSliceModel:
    blocked_units: int


@dataclass(frozen=True)
class CreateExternalReferencesModel:
    global_distribution_system_id: str | None = None
    online_travel_agency_id: str | None = None
    online_booking_tool_id: str | None = None
    channel_manager_id: str | None = None
    central_reservation_system_id: str | None = None


class AccountOwner(StrEnum):
    guest = "Guest"
    booker = "Booker"


@dataclass(frozen=True)
class CreatePaymentAccountModel:
    account_number: str | None = None
    account_holder: str | None = None
    expiry_month: str | None = None
    expiry_year: str | None = None
    payment_method: str | None = None
    payer_email: str | None = None
    payer_reference: str | None = None
    is_virtual: bool | None = None
    inactive_reason: str | None = None


class GuaranteeType(StrEnum):
    pm6_hold = "PM6Hold"
    credit_card = "CreditCard"
    prepayment = "Prepayment"
    company = "Company"


class TravelPurpose(StrEnum):
    business = "Business"
    leisure = "Leisure"


@dataclass(frozen=True)
class EmbeddedCompanyModel:
    id: str
    code: str | None = None
    name: str | None = None
    can_check_out_on_ar: bool | None = None


@dataclass(frozen=True)
class EmbeddedGroupModel:
    id: str
    name: str | None = None


@dataclass(frozen=True)
class EmbeddedMarketSegmentModel:
    id: str
    code: str | None = None
    name: str | None = None


@dataclass(frozen=True)
class EmbeddedPropertyModel:
    id: str
    code: str | None = None
    name: str | None = None
    description: str | None = None


@dataclass(frozen=True)
class EmbeddedRatePlanModel:
    id: str
    is_subject_to_city_tax: bool
    code: str | None = None
    name: str | None = None
    description: str | None = None


@dataclass(frozen=True)
class EmbeddedServiceModel(EmbeddedPropertyModel):
    pass


class Type1(StrEnum):
    bed_room = "BedRoom"
    meeting_room = "MeetingRoom"
    event_space = "EventSpace"
    parking_lot = "ParkingLot"
    other = "Other"


@dataclass(frozen=True)
class EmbeddedUnitGroupModel:
    id: str
    code: str | None = None
    name: str | None = None
    description: str | None = None
    type: Type1 | None = None


@dataclass(frozen=True)
class EmbeddedUnitModel:
    id: str
    name: str | None = None
    description: str | None = None
    unit_group_id: str | None = None


@dataclass(frozen=True)
class ExternalAuthorizationReferenceModel:
    payment_transaction_id: str


@dataclass(frozen=True)
class ExternalPaymentAccountReferenceModel(ExternalAuthorizationReferenceModel):
    pass


@dataclass(frozen=True)
class ExternalReferencesModel:
    global_distribution_system_id: str | None = None
    online_travel_agency_id: str | None = None
    online_booking_tool_id: str | None = None
    channel_manager_id: str | None = None
    central_reservation_system_id: str | None = None
    legacy_id: str | None = None


@dataclass(frozen=True)
class GroupCreatedModel(AuthorizationCreatedModel):
    pass


class RelationshipToPrimaryGuest(StrEnum):
    grandparent = "Grandparent"
    grandchild = "Grandchild"
    great_grandparent = "GreatGrandparent"
    great_grandchild = "GreatGrandchild"
    parent = "Parent"
    child = "Child"
    sibling = "Sibling"
    parent_in_law = "ParentInLaw"
    child_in_law = "ChildInLaw"
    sibling_in_law = "SiblingInLaw"
    spouse = "Spouse"
    uncle_or_aunt = "UncleOrAunt"
    nephew_or_niece = "NephewOrNiece"
    guardian = "Guardian"
    other = "Other"


@dataclass(frozen=True)
class MessageItemCollection:
    messages: list[str] | None = None


@dataclass(frozen=True)
class MonetaryValueModel:
    amount: float
    currency: str


@dataclass(frozen=True)
class OfferCancellationFeeModel:
    code: str
    name: str
    description: str
    due_date_time: str
    fee: MonetaryValueModel


@dataclass(frozen=True)
class OfferCityTaxItemModel:
    service_date: str
    amount: AmountModel


@dataclass(frozen=True)
class OfferCityTaxModel:
    id: str
    code: str
    name: str
    total_gross_amount: MonetaryValueModel
    dates: list[OfferCityTaxItemModel]


@dataclass(frozen=True)
class OfferFeeModel:
    id: str
    code: str
    name: str
    total_amount: AmountModel


@dataclass(frozen=True)
class OfferNoShowFeeModel:
    code: str
    name: str
    description: str
    fee: MonetaryValueModel


class PricingMode(StrEnum):
    included = "Included"
    additional = "Additional"


@dataclass(frozen=True)
class OfferServiceModel:
    service: EmbeddedServiceModel
    service_date: str
    count: int
    amount: AmountModel
    pricing_mode: PricingMode
    available_count: int | None = None


@dataclass(frozen=True)
class OfferTimeSliceModel:
    from_: str
    to: str
    available_units: int
    base_amount: AmountModel
    total_gross_amount: MonetaryValueModel
    included_services: list[OfferServiceModel] | None = None


@dataclass(frozen=True)
class OfferUnitGroupModel:
    id: str
    code: str
    name: str
    description: str
    max_persons: int
    type: Type1
    rank: int | None = None


class Code(StrEnum):
    unit_group_fully_booked = "UnitGroupFullyBooked"
    unit_group_capacity_exceeded = "UnitGroupCapacityExceeded"
    rate_plan_restrictions_violated = "RatePlanRestrictionsViolated"
    rate_plan_surcharges_not_set = "RatePlanSurchargesNotSet"
    rate_restrictions_violated = "RateRestrictionsViolated"
    rate_plan_channel_not_set = "RatePlanChannelNotSet"
    rates_not_set = "RatesNotSet"
    block_fully_booked = "BlockFullyBooked"
    included_services_amount_exceeded_rate_amount = (
        "IncludedServicesAmountExceededRateAmount"
    )
    service_fully_booked = "ServiceFullyBooked"
    rate_does_not_satify_hurdles = "RateDoesNotSatifyHurdles"


@dataclass(frozen=True)
class OfferValidationMessageModel:
    code: Code
    message: str


@dataclass(frozen=True)
class Operation:
    value: Any | None = None
    path: str | None = None
    op: str | None = None
    from_: str | None = None


@dataclass(frozen=True)
class PayableAmountModel:
    guest: MonetaryValueModel


@dataclass(frozen=True)
class PaymentAccountCreatedModel(AuthorizationCreatedModel):
    pass


@dataclass(frozen=True)
class PaymentAccountDetailsModel:
    account_number: str | None = None
    account_holder: str | None = None
    expiry_month: str | None = None
    expiry_year: str | None = None
    payment_method: str | None = None
    payer_email: str | None = None


@dataclass(frozen=True)
class PaymentAccountModel:
    is_active: bool
    account_number: str | None = None
    account_holder: str | None = None
    expiry_month: str | None = None
    expiry_year: str | None = None
    payment_method: str | None = None
    payer_email: str | None = None
    payer_reference: str | None = None
    is_virtual: bool | None = None
    inactive_reason: str | None = None


@dataclass(frozen=True)
class PaymentAccountPaymentLinkModel:
    expires_at: str | None = None
    url: str | None = None


@dataclass(frozen=True)
class PaymentAccountTargetModel:
    type: Type
    id: str


class Status5(StrEnum):
    pending = "Pending"
    success = "Success"
    failure = "Failure"
    canceled = "Canceled"
    expired = "Expired"


class PayerInteraction1(StrEnum):
    pci_token = "PciToken"
    terminal = "Terminal"
    authorization = "Authorization"
    payment_link = "PaymentLink"


@dataclass(frozen=True)
class PeriodModel:
    hours: int | None = None
    days: int | None = None
    months: int | None = None


@dataclass(frozen=True)
class PersonAddressModel:
    address_line1: str | None = None
    address_line2: str | None = None
    postal_code: str | None = None
    city: str | None = None
    region_code: str | None = None
    country_code: str | None = None


@dataclass(frozen=True)
class PersonCompanyModel:
    name: str | None = None
    tax_id: str | None = None


@dataclass(frozen=True)
class PropertyValueModel:
    property: EmbeddedPropertyModel
    total_gross_amount: MonetaryValueModel
    balance: MonetaryValueModel


@dataclass(frozen=True)
class RateRestrictionsModel:
    closed: bool
    closed_on_arrival: bool
    closed_on_departure: bool
    min_length_of_stay: int | None = None
    max_length_of_stay: int | None = None


@dataclass(frozen=True)
class RegisteredCardModel:
    card_number: str | None = None
    card_holder: str | None = None
    expiry_month: str | None = None
    expiry_year: str | None = None
    payment_method: str | None = None
    payer_email: str | None = None
    note: str | None = None
    is_virtual: bool | None = None


@dataclass(frozen=True)
class ReplaceBlockModel:
    from_: str
    to: str
    gross_daily_rate: MonetaryValueModel
    time_slices: list[CreateBlockTimeSliceModel]
    market_segment_id: str | None = None


@dataclass(frozen=True)
class ReservationAssignedUnitTimeRangeModel:
    from_: str
    to: str


@dataclass(frozen=True)
class ReservationCancellationFeeModel:
    id: str
    code: str
    name: str
    description: str
    due_date_time: str
    fee: MonetaryValueModel


@dataclass(frozen=True)
class ReservationCreatedModel(AuthorizationCreatedModel):
    pass


class GuaranteeType1(StrEnum):
    pm6_hold = "PM6Hold"
    credit_card = "CreditCard"
    prepayment = "Prepayment"
    company = "Company"
    ota = "Ota"


@dataclass(frozen=True)
class ReservationNoShowFeeModel:
    id: str
    code: str
    name: str
    description: str
    fee: MonetaryValueModel


@dataclass(frozen=True)
class ReservationServiceModel:
    service: EmbeddedServiceModel
    service_date: str
    count: int
    amount: AmountModel
    booked_as_extra: bool


@dataclass(frozen=True)
class ReservationStayOfferServiceModel:
    service: EmbeddedServiceModel
    service_date: str
    count: int
    amount: AmountModel
    booked_as_extra: bool
    pricing_mode: PricingMode
    available_count: int | None = None


@dataclass(frozen=True)
class ReservationStayOfferTimeSliceModel:
    from_: str
    to: str
    rate_plan: EmbeddedRatePlanModel
    unit_group: OfferUnitGroupModel
    base_amount: AmountModel
    total_gross_amount: MonetaryValueModel
    included_services: list[ReservationStayOfferServiceModel] | None = None


class Category(StrEnum):
    offer_not_available = "OfferNotAvailable"
    auto_unit_assignment = "AutoUnitAssignment"


class Code1(StrEnum):
    unit_group_fully_booked = "UnitGroupFullyBooked"
    unit_group_capacity_exceeded = "UnitGroupCapacityExceeded"
    rate_plan_restrictions_violated = "RatePlanRestrictionsViolated"
    rate_plan_surcharges_not_set = "RatePlanSurchargesNotSet"
    rate_restrictions_violated = "RateRestrictionsViolated"
    rate_plan_channel_not_set = "RatePlanChannelNotSet"
    rates_not_set = "RatesNotSet"
    block_fully_booked = "BlockFullyBooked"
    unit_moved = "UnitMoved"
    included_services_amount_exceeded_rate_amount = (
        "IncludedServicesAmountExceededRateAmount"
    )
    rate_plan_company_restrictions_violated = "RatePlanCompanyRestrictionsViolated"
    service_fully_booked = "ServiceFullyBooked"
    rate_does_not_satify_hurdles = "RateDoesNotSatifyHurdles"


@dataclass(frozen=True)
class ReservationValidationMessageModel:
    category: Category
    code: Code1
    message: str


@dataclass(frozen=True)
class ReservationsCreatedModel:
    reservation_ids: list[ReservationCreatedModel]


@dataclass(frozen=True)
class ServiceDateItemModel:
    service_date: str
    count: int
    amount: AmountModel
    is_mandatory: bool


class PricingUnit(StrEnum):
    room = "Room"
    person = "Person"


@dataclass(frozen=True)
class ServiceModel:
    id: str
    code: str
    name: str
    description: str
    pricing_unit: PricingUnit
    default_gross_price: MonetaryValueModel


@dataclass(frozen=True)
class ServiceOfferItemModel:
    service_date: str
    amount: AmountModel
    is_default_date: bool
    is_mandatory: bool
    available_count: int | None = None


@dataclass(frozen=True)
class ServiceOfferModel:
    service: ServiceModel
    count: int
    total_amount: AmountModel
    pre_payment_amount: MonetaryValueModel
    dates: list[ServiceOfferItemModel]
    available_count: int | None = None
    fees: list[OfferFeeModel] | None = None
    validation_messages: list[OfferValidationMessageModel] | None = None


@dataclass(frozen=True)
class ServiceOffersModel:
    services: list[ServiceOfferModel]


@dataclass(frozen=True)
class SourceListModel:
    sources: list[str]


@dataclass(frozen=True)
class TaxDetailModel:
    vat_type: VatType
    vat_percent: float
    net: MonetaryValueModel
    tax: MonetaryValueModel


@dataclass(frozen=True)
class TaxesModel:
    tax: float
    city_tax: float


@dataclass(frozen=True)
class VehicleRegistrationModel:
    number: str | None = None
    country_code: str | None = None


class Action(StrEnum):
    cancel = "Cancel"
    refresh = "Refresh"
    expire_payment_link = "ExpirePaymentLink"


class Action1(StrEnum):
    delete = "Delete"
    confirm = "Confirm"
    release = "Release"
    cancel = "Cancel"
    pickup = "Pickup"
    modify = "Modify"
    wash = "Wash"


class Action2(StrEnum):
    delete = "Delete"


class Action3(StrEnum):
    cancel = "Cancel"
    expire_payment_link = "ExpirePaymentLink"


class Action4(StrEnum):
    check_in = "CheckIn"
    check_out = "CheckOut"
    cancel = "Cancel"
    amend_time_slices = "AmendTimeSlices"
    amend_arrival = "AmendArrival"
    amend_departure = "AmendDeparture"
    no_show = "NoShow"
    assign_unit = "AssignUnit"
    unassign_unit = "UnassignUnit"
    remove_city_tax = "RemoveCityTax"
    add_city_tax = "AddCityTax"
    remove_service = "RemoveService"
    add_service = "AddService"
    check_in_revert = "CheckInRevert"
    lock_unit = "LockUnit"
    unlock_unit = "UnlockUnit"


class Action5(StrEnum):
    amend = "Amend"


class Code2(StrEnum):
    only_successful_authorization_can_be_canceled = (
        "OnlySuccessfulAuthorizationCanBeCanceled"
    )
    only_successful_authorization_can_be_refreshed = (
        "OnlySuccessfulAuthorizationCanBeRefreshed"
    )
    non_active_authorization_can_not_be_refreshed = (
        "NonActiveAuthorizationCanNotBeRefreshed"
    )
    only_pending_payment_link_authorization_can_be_expired = (
        "OnlyPendingPaymentLinkAuthorizationCanBeExpired"
    )


@dataclass(frozen=True)
class ActionReasonModelNotAllowedAuthorizationActionReason:
    code: Code2
    message: str


class Code3(StrEnum):
    delete_not_allowed_for_block_with_reservations = (
        "DeleteNotAllowedForBlockWithReservations"
    )
    release_not_allowed_for_block_with_reservations = (
        "ReleaseNotAllowedForBlockWithReservations"
    )
    release_not_allowed_for_block_in_the_past = "ReleaseNotAllowedForBlockInThePast"
    release_not_allowed_for_block_not_in_status_definite = (
        "ReleaseNotAllowedForBlockNotInStatusDefinite"
    )
    confirm_not_allowed_for_block_not_in_status_tentative = (
        "ConfirmNotAllowedForBlockNotInStatusTentative"
    )
    confirm_not_allowed_for_block_in_the_past = "ConfirmNotAllowedForBlockInThePast"
    cancel_not_allowed_for_block_with_not_cancelled_reservations = (
        "CancelNotAllowedForBlockWithNotCancelledReservations"
    )
    cancel_not_allowed_for_block_not_in_status_definite_or_tentative = (
        "CancelNotAllowedForBlockNotInStatusDefiniteOrTentative"
    )
    pickup_not_allowed_for_block_not_in_status_definite = (
        "PickupNotAllowedForBlockNotInStatusDefinite"
    )
    pickup_not_allowed_for_block_in_the_past = "PickupNotAllowedForBlockInThePast"
    pickup_not_allowed_for_fully_picked_block = "PickupNotAllowedForFullyPickedBlock"
    modify_not_allowed_for_block_in_the_past = "ModifyNotAllowedForBlockInThePast"
    modify_not_allowed_for_block_in_status_canceled = (
        "ModifyNotAllowedForBlockInStatusCanceled"
    )
    wash_not_allowed_for_block_not_in_status_definite = (
        "WashNotAllowedForBlockNotInStatusDefinite"
    )
    wash_not_allowed_for_block_without_reservations = (
        "WashNotAllowedForBlockWithoutReservations"
    )


@dataclass(frozen=True)
class ActionReasonModelNotAllowedBlockActionReason:
    code: Code3
    message: str


class Code4(StrEnum):
    delete_not_allowed_for_group_with_blocks = "DeleteNotAllowedForGroupWithBlocks"


@dataclass(frozen=True)
class ActionReasonModelNotAllowedGroupActionReason:
    code: Code4
    message: str


class Code5(StrEnum):
    only_successful_payment_account_can_be_canceled = (
        "OnlySuccessfulPaymentAccountCanBeCanceled"
    )
    only_pending_payment_link_payment_account_can_be_expired = (
        "OnlyPendingPaymentLinkPaymentAccountCanBeExpired"
    )


@dataclass(frozen=True)
class ActionReasonModelNotAllowedPaymentAccountActionReason:
    code: Code5
    message: str


class Code6(StrEnum):
    check_in_not_allowed_for_reservation_not_in_status_confirmed = (
        "CheckInNotAllowedForReservationNotInStatusConfirmed"
    )
    check_in_not_allowed_before_arrival_date = "CheckInNotAllowedBeforeArrivalDate"
    check_in_not_allowed_after_departure_date_time = (
        "CheckInNotAllowedAfterDepartureDateTime"
    )
    check_in_not_allowed_without_unit_assigned_for_whole_stay = (
        "CheckInNotAllowedWithoutUnitAssignedForWholeStay"
    )
    check_in_revert_disabled = "CheckInRevertDisabled"
    check_in_revert_not_allowed_for_reservation_not_in_in_house_status = (
        "CheckInRevertNotAllowedForReservationNotInInHouseStatus"
    )
    check_in_revert_not_allowed_for_reservation_with_posted_charges = (
        "CheckInRevertNotAllowedForReservationWithPostedCharges"
    )
    check_out_not_allowed_for_reservation_not_in_status_in_house = (
        "CheckOutNotAllowedForReservationNotInStatusInHouse"
    )
    check_out_not_allowed_for_past_reservation_not_in_status_confirmed_or_in_house = (
        "CheckOutNotAllowedForPastReservationNotInStatusConfirmedOrInHouse"
    )
    check_out_not_allowed_with_departure_date_more_than_one_day_in_the_future = (
        "CheckOutNotAllowedWithDepartureDateMoreThanOneDayInTheFuture"
    )
    cancel_not_allowed_for_reservation_not_in_status_confirmed = (
        "CancelNotAllowedForReservationNotInStatusConfirmed"
    )
    amend_not_allowed_for_not_amendable_time_slices = (
        "AmendNotAllowedForNotAmendableTimeSlices"
    )
    amend_arrival_not_allowed_for_not_amendable_time_slices = (
        "AmendArrivalNotAllowedForNotAmendableTimeSlices"
    )
    amend_arrival_not_allowed_for_reservation_not_in_status_confirmed = (
        "AmendArrivalNotAllowedForReservationNotInStatusConfirmed"
    )
    amend_arrival_not_allowed_when_main_folio_is_closed_or_closing = (
        "AmendArrivalNotAllowedWhenMainFolioIsClosedOrClosing"
    )
    amend_departure_not_allowed_for_reservation_not_in_status_confirmed_or_in_house = (
        "AmendDepartureNotAllowedForReservationNotInStatusConfirmedOrInHouse"
    )
    amend_departure_not_allowed_for_reservation_departure_date_too_far_in_the_past = (
        "AmendDepartureNotAllowedForReservationDepartureDateTooFarInThePast"
    )
    amend_departure_not_allowed_when_main_folio_is_closed_or_closing = (
        "AmendDepartureNotAllowedWhenMainFolioIsClosedOrClosing"
    )
    no_show_not_allowed_for_reservation_not_in_status_confirmed = (
        "NoShowNotAllowedForReservationNotInStatusConfirmed"
    )
    no_show_not_allowed_before_arrival_date = "NoShowNotAllowedBeforeArrivalDate"
    assign_unit_not_allowed_for_reservation_in_the_past = (
        "AssignUnitNotAllowedForReservationInThePast"
    )
    assign_unit_not_allowed_for_reservation_not_in_status_confirmed_or_in_house = (
        "AssignUnitNotAllowedForReservationNotInStatusConfirmedOrInHouse"
    )
    unassign_unit_not_allowed_for_reservation_in_the_past = (
        "UnassignUnitNotAllowedForReservationInThePast"
    )
    unassign_unit_not_allowed_for_reservation_not_in_status_confirmed = (
        "UnassignUnitNotAllowedForReservationNotInStatusConfirmed"
    )
    unassign_unit_not_allowed_for_reservation_without_unit = (
        "UnassignUnitNotAllowedForReservationWithoutUnit"
    )
    remove_city_tax_not_allowed_for_reservation_not_in_status_confirmed_or_in_house = (
        "RemoveCityTaxNotAllowedForReservationNotInStatusConfirmedOrInHouse"
    )
    remove_city_tax_not_allowed_for_reservation_with_posted_charges = (
        "RemoveCityTaxNotAllowedForReservationWithPostedCharges"
    )
    remove_city_tax_not_allowed_for_reservation_without_city_tax = (
        "RemoveCityTaxNotAllowedForReservationWithoutCityTax"
    )
    add_city_tax_not_allowed_for_reservation_not_in_status_confirmed_or_in_house = (
        "AddCityTaxNotAllowedForReservationNotInStatusConfirmedOrInHouse"
    )
    add_city_tax_not_allowed_for_reservation_with_city_tax = (
        "AddCityTaxNotAllowedForReservationWithCityTax"
    )
    add_city_tax_not_allowed_for_reservation_for_rate_plan_not_subject_to_city_tax = (
        "AddCityTaxNotAllowedForReservationForRatePlanNotSubjectToCityTax"
    )
    add_city_tax_not_allowed_for_reservation_with_posted_charges = (
        "AddCityTaxNotAllowedForReservationWithPostedCharges"
    )
    remove_service_not_allowed_for_reservation_not_in_status_confirmed_or_in_house = (
        "RemoveServiceNotAllowedForReservationNotInStatusConfirmedOrInHouse"
    )
    remove_service_not_allowed_for_reservation_in_the_past = (
        "RemoveServiceNotAllowedForReservationInThePast"
    )
    add_service_not_allowed_for_reservation_not_in_status_confirmed_or_in_house = (
        "AddServiceNotAllowedForReservationNotInStatusConfirmedOrInHouse"
    )
    add_service_not_allowed_for_reservation_in_the_past = (
        "AddServiceNotAllowedForReservationInThePast"
    )
    add_service_not_allowed_when_main_folio_is_closed_or_closing = (
        "AddServiceNotAllowedWhenMainFolioIsClosedOrClosing"
    )
    lock_unit_not_allowed_for_reservation_not_in_status_confirmed_or_in_house = (
        "LockUnitNotAllowedForReservationNotInStatusConfirmedOrInHouse"
    )
    lock_unit_not_allowed_for_reservation_when_units_not_assigned = (
        "LockUnitNotAllowedForReservationWhenUnitsNotAssigned"
    )
    unlock_unit_not_allowed_for_reservation_not_locked = (
        "UnlockUnitNotAllowedForReservationNotLocked"
    )
    assign_unit_not_allowed_for_locked_reservation = (
        "AssignUnitNotAllowedForLockedReservation"
    )
    unassign_unit_not_allowed_for_locked_reservation = (
        "UnassignUnitNotAllowedForLockedReservation"
    )


@dataclass(frozen=True)
class ActionReasonModelNotAllowedReservationActionReason:
    code: Code6
    message: str


class Code7(StrEnum):
    amend_not_allowed_when_time_slice_is_in_the_past = (
        "AmendNotAllowedWhenTimeSliceIsInThePast"
    )
    amend_not_allowed_when_time_slice_is_already_posted = (
        "AmendNotAllowedWhenTimeSliceIsAlreadyPosted"
    )
    amend_not_allowed_for_reservation_in_final_status = (
        "AmendNotAllowedForReservationInFinalStatus"
    )
    amend_not_allowed_when_main_folio_is_closed_or_closing = (
        "AmendNotAllowedWhenMainFolioIsClosedOrClosing"
    )


@dataclass(frozen=True)
class ActionReasonModelNotAllowedReservationTimeSliceActionReason:
    code: Code7
    message: str


@dataclass(frozen=True)
class AssignedUnitModel:
    unit: EmbeddedUnitModel


@dataclass(frozen=True)
class AuthorizationRefreshRequest:
    amount: MonetaryValueModel


@dataclass(frozen=True)
class AutoAssignedUnitItemModel:
    unit: EmbeddedUnitModel
    from_: str
    to: str


@dataclass(frozen=True)
class AutoAssignedUnitListModel:
    time_slices: list[AutoAssignedUnitItemModel]


@dataclass(frozen=True)
class BlockTimeSliceModel:
    from_: str
    to: str
    blocked_units: int
    picked_units: int
    base_amount: AmountModel
    total_gross_amount: MonetaryValueModel


@dataclass(frozen=True)
class BookerModel:
    last_name: str
    title: Title | None = None
    gender: Gender | None = None
    first_name: str | None = None
    middle_initial: str | None = None
    email: str | None = None
    phone: str | None = None
    address: PersonAddressModel | None = None
    nationality_country_code: str | None = None
    identification_number: str | None = None
    identification_issue_date: str | None = None
    identification_expiry_date: str | None = None
    identification_type: IdentificationType | None = None
    company: PersonCompanyModel | None = None
    preferred_language: str | None = None
    birth_date: str | None = None
    birth_place: str | None = None


@dataclass(frozen=True)
class BookingCreatedModel:
    id: str
    reservation_ids: list[ReservationCreatedModel]


@dataclass(frozen=True)
class CommissionModel:
    commission_amount: MonetaryValueModel
    before_commission_amount: MonetaryValueModel | None = None


@dataclass(frozen=True)
class CreateAuthorizationPaymentAccountRequest:
    target: PaymentAccountTargetModel
    transaction_reference: str


@dataclass(frozen=True)
class CreateAuthorizationRequest:
    target: AuthorizationTargetModel
    amount: MonetaryValueModel
    transaction_reference: str


@dataclass(frozen=True)
class CreateBlockModel:
    group_id: str
    rate_plan_id: str
    from_: str
    to: str
    gross_daily_rate: MonetaryValueModel
    time_slices: list[CreateBlockTimeSliceModel] | None = None
    blocked_units: int | None = None
    promo_code: str | None = None
    corporate_code: str | None = None
    market_segment_id: str | None = None


@dataclass(frozen=True)
class CreateGroupModel:
    name: str
    booker: BookerModel
    property_ids: list[str]
    comment: str | None = None
    booker_comment: str | None = None
    payment_account: CreatePaymentAccountModel | None = None
    registered_card: RegisteredCardModel | None = None


@dataclass(frozen=True)
class CreatePaymentAccountAuthorizationRequest:
    target: AuthorizationTargetModel
    amount: MonetaryValueModel
    account_owner: AccountOwner | None = None
    payment_account_id: str | None = None


@dataclass(frozen=True)
class CreatePaymentLinkAuthorizationRequest:
    target: AuthorizationTargetModel
    expires_at: str
    country_code: str
    amount: MonetaryValueModel
    description: str | None = None
    payer_email: str | None = None


@dataclass(frozen=True)
class CreatePaymentLinkPaymentAccountRequest:
    target: PaymentAccountTargetModel
    property_id: str
    expires_at: str
    country_code: str
    description: str | None = None
    payer_email: str | None = None


@dataclass(frozen=True)
class CreateReservationTimeSliceModel:
    rate_plan_id: str
    total_amount: MonetaryValueModel | None = None


@dataclass(frozen=True)
class CreateStoredPaymentMethodAuthorizationPaymentAccountRequest:
    target: PaymentAccountTargetModel
    payer_reference: str
    stored_payment_method_id: str
    is_virtual: bool | None = None


@dataclass(frozen=True)
class CreateTerminalAuthorizationRequest:
    target: AuthorizationTargetModel
    amount: MonetaryValueModel
    terminal_id: str


@dataclass(frozen=True)
class CreateTerminalPaymentAccountRequest:
    target: PaymentAccountTargetModel
    property_id: str
    terminal_id: str


@dataclass(frozen=True)
class Date:
    service_date: str
    count: int | None = None
    amount: MonetaryValueModel | None = None


@dataclass(frozen=True)
class DesiredTimeSliceModel:
    rate_plan_id: str
    total_gross_amount: MonetaryValueModel | None = None


@dataclass(frozen=True)
class GroupBlockModel:
    id: str
    status: Status1
    property: EmbeddedPropertyModel
    rate_plan: EmbeddedRatePlanModel
    unit_group: EmbeddedUnitGroupModel
    gross_daily_rate: MonetaryValueModel
    from_: str
    to: str
    blocked_units: int
    picked_reservations: int
    created: str
    modified: str


@dataclass(frozen=True)
class GuestModel:
    last_name: str
    title: Title | None = None
    gender: Gender | None = None
    first_name: str | None = None
    middle_initial: str | None = None
    second_last_name: str | None = None
    email: str | None = None
    phone: str | None = None
    address: PersonAddressModel | None = None
    nationality_country_code: str | None = None
    identification_number: str | None = None
    identification_additional_number: str | None = None
    identification_issue_date: str | None = None
    identification_expiry_date: str | None = None
    identification_issue_place: str | None = None
    identification_type: IdentificationType | None = None
    personal_tax_id: str | None = None
    company: PersonCompanyModel | None = None
    preferred_language: str | None = None
    birth_date: str | None = None
    birth_place: str | None = None
    birth_first_name: str | None = None
    birth_last_name: str | None = None
    mother_first_name: str | None = None
    mother_last_name: str | None = None
    border_crossing_place: str | None = None
    border_crossing_date: str | None = None
    next_destination: str | None = None
    relationship_to_primary_guest: RelationshipToPrimaryGuest | None = None
    vehicle_registration: VehicleRegistrationModel | None = None


@dataclass(frozen=True)
class OfferModel:
    arrival: str
    departure: str
    unit_group: OfferUnitGroupModel
    min_guarantee_type: GuaranteeType
    available_units: int
    rate_plan: EmbeddedRatePlanModel
    total_gross_amount: MonetaryValueModel
    cancellation_fee: OfferCancellationFeeModel
    no_show_fee: OfferNoShowFeeModel
    time_slices: list[OfferTimeSliceModel]
    tax_details: list[TaxDetailModel]
    is_corporate: bool
    pre_payment_amount: MonetaryValueModel
    services: list[ServiceOfferModel] | None = None
    fees: list[OfferFeeModel] | None = None
    validation_messages: list[OfferValidationMessageModel] | None = None
    company_id: str | None = None
    corporate_code: str | None = None
    city_taxes: list[OfferCityTaxModel] | None = None


@dataclass(frozen=True)
class PriceModel:
    gross_amount: float
    before_tax: float
    after_tax: float
    taxes: TaxesModel
    currency: str


@dataclass(frozen=True)
class ReservationAssignedUnitModel:
    unit: EmbeddedUnitModel
    time_ranges: list[ReservationAssignedUnitTimeRangeModel]


@dataclass(frozen=True)
class ReservationServiceItemModel:
    service: ServiceModel
    total_amount: AmountModel
    dates: list[ServiceDateItemModel]


@dataclass(frozen=True)
class ReservationServiceListModel:
    services: list[ReservationServiceItemModel]
    count: int


@dataclass(frozen=True)
class ReservationStayOfferModel:
    arrival: str
    departure: str
    min_guarantee_type: GuaranteeType
    available_units: int
    total_gross_amount: MonetaryValueModel
    cancellation_fee: OfferCancellationFeeModel
    no_show_fee: OfferNoShowFeeModel
    time_slices: list[ReservationStayOfferTimeSliceModel]
    tax_details: list[TaxDetailModel]
    is_corporate: bool
    services: list[ServiceOfferModel] | None = None
    fees: list[OfferFeeModel] | None = None
    validation_messages: list[OfferValidationMessageModel] | None = None
    company_id: str | None = None
    corporate_code: str | None = None
    city_taxes: list[OfferCityTaxModel] | None = None


@dataclass(frozen=True)
class ReservationStayOffersModel:
    property: EmbeddedPropertyModel
    offers: list[ReservationStayOfferModel]


@dataclass(frozen=True)
class StayOffersModel:
    property: EmbeddedPropertyModel
    offers: list[OfferModel]


@dataclass(frozen=True)
class ActionModelAuthorizationActionNotAllowedAuthorizationActionReason:
    action: Action
    is_allowed: bool
    reasons: list[ActionReasonModelNotAllowedAuthorizationActionReason] | None = None


@dataclass(frozen=True)
class ActionModelBlockActionNotAllowedBlockActionReason:
    action: Action1
    is_allowed: bool
    reasons: list[ActionReasonModelNotAllowedBlockActionReason] | None = None


@dataclass(frozen=True)
class ActionModelGroupActionNotAllowedGroupActionReason:
    action: Action2
    is_allowed: bool
    reasons: list[ActionReasonModelNotAllowedGroupActionReason] | None = None


@dataclass(frozen=True)
class ActionModelPaymentAccountActionNotAllowedPaymentAccountActionReason:
    action: Action3
    is_allowed: bool
    reasons: list[ActionReasonModelNotAllowedPaymentAccountActionReason] | None = None


@dataclass(frozen=True)
class ActionModelReservationActionNotAllowedReservationActionReason:
    action: Action4
    is_allowed: bool
    reasons: list[ActionReasonModelNotAllowedReservationActionReason] | None = None


@dataclass(frozen=True)
class ActionModelReservationTimeSliceActionNotAllowedReservationTimeSliceActionReason:
    action: Action5
    is_allowed: bool
    reasons: (
        list[ActionReasonModelNotAllowedReservationTimeSliceActionReason] | None
    ) = None


@dataclass(frozen=True)
class AuthorizationModel:
    id: str
    target: AuthorizationTargetModel
    created: str
    updated: str
    amount: MonetaryValueModel
    status: Status
    payer_interaction: PayerInteraction
    external_reference: ExternalAuthorizationReferenceModel | None = None
    remaining_balance: MonetaryValueModel | None = None
    failure_reason: str | None = None
    expires_at: str | None = None
    payment_link_url: str | None = None
    actions: (
        list[ActionModelAuthorizationActionNotAllowedAuthorizationActionReason] | None
    ) = None


@dataclass(frozen=True)
class BlockItemModel:
    id: str
    group: EmbeddedGroupModel
    status: Status1
    property: EmbeddedPropertyModel
    rate_plan: EmbeddedRatePlanModel
    unit_group: EmbeddedUnitGroupModel
    gross_daily_rate: MonetaryValueModel
    from_: str
    to: str
    picked_reservations: int
    created: str
    modified: str
    market_segment: EmbeddedMarketSegmentModel | None = None
    promo_code: str | None = None
    corporate_code: str | None = None
    time_slices: list[BlockTimeSliceModel] | None = None
    actions: list[ActionModelBlockActionNotAllowedBlockActionReason] | None = None


@dataclass(frozen=True)
class BlockListModel:
    blocks: list[BlockItemModel]
    count: int


@dataclass(frozen=True)
class BlockModel(BlockItemModel):
    pass


@dataclass(frozen=True)
class BookReservationServiceModel:
    service_id: str
    count: int | None = None
    amount: MonetaryValueModel | None = None
    dates: list[Date] | None = None


@dataclass(frozen=True)
class BookingReservationModel:
    id: str
    status: Status3
    channel_code: ChannelCode
    arrival: str
    departure: str
    adults: int
    total_gross_amount: MonetaryValueModel
    property: EmbeddedPropertyModel
    rate_plan: EmbeddedRatePlanModel
    unit_group: EmbeddedUnitGroupModel
    cancellation_fee: ReservationCancellationFeeModel
    no_show_fee: ReservationNoShowFeeModel
    is_open_for_charges: bool
    external_code: str | None = None
    source: str | None = None
    payment_account: PaymentAccountModel | None = None
    has_active_payment_account: bool | None = None
    registered_card: RegisteredCardModel | None = None
    children_ages: list[int] | None = None
    services: list[ReservationServiceItemModel] | None = None
    guest_comment: str | None = None
    company: EmbeddedCompanyModel | None = None
    is_pre_checked_in: bool | None = None
    external_references: ExternalReferencesModel | None = None


@dataclass(frozen=True)
class CreateReservationModel:
    arrival: str
    departure: str
    adults: int
    channel_code: ChannelCode
    time_slices: list[CreateReservationTimeSliceModel]
    children_ages: list[int] | None = None
    comment: str | None = None
    guest_comment: str | None = None
    external_code: str | None = None
    source: str | None = None
    primary_guest: GuestModel | None = None
    additional_guests: list[GuestModel] | None = None
    guarantee_type: GuaranteeType | None = None
    travel_purpose: TravelPurpose | None = None
    services: list[BookReservationServiceModel] | None = None
    company_id: str | None = None
    corporate_code: str | None = None
    pre_payment_amount: MonetaryValueModel | None = None
    commission: CommissionModel | None = None
    promo_code: str | None = None
    external_references: CreateExternalReferencesModel | None = None
    registered_card: RegisteredCardModel | None = None


@dataclass(frozen=True)
class DesiredStayDetailsModel:
    arrival: str
    departure: str
    adults: int
    time_slices: list[DesiredTimeSliceModel]
    children_ages: list[int] | None = None
    requote: bool | None = None


@dataclass(frozen=True)
class GroupItemModel:
    id: str
    name: str
    created: str
    modified: str
    property_ids: list[str]
    from_: str | None = None
    to: str | None = None
    booker: BookerModel | None = None
    comment: str | None = None
    booker_comment: str | None = None
    payment_account: PaymentAccountModel | None = None
    has_active_payment_account: bool | None = None
    blocks: list[GroupBlockModel] | None = None
    actions: list[ActionModelGroupActionNotAllowedGroupActionReason] | None = None


@dataclass(frozen=True)
class GroupListModel:
    groups: list[GroupItemModel]
    count: int


@dataclass(frozen=True)
class GroupModel(GroupItemModel):
    pass


@dataclass(frozen=True)
class PaymentAccountV2Model:
    id: str
    target: PaymentAccountTargetModel
    created: str
    updated: str
    status: Status5
    payer_interaction: PayerInteraction1
    external_reference: ExternalPaymentAccountReferenceModel | None = None
    failure_reason: str | None = None
    payment_link: PaymentAccountPaymentLinkModel | None = None
    account_details: PaymentAccountDetailsModel | None = None
    is_virtual: bool | None = None
    actions: (
        list[ActionModelPaymentAccountActionNotAllowedPaymentAccountActionReason] | None
    ) = None


@dataclass(frozen=True)
class PerOccupancyPriceItemModel:
    adults: int
    price: PriceModel


@dataclass(frozen=True)
class PickUpReservationModel:
    block_id: str
    arrival: str
    departure: str
    adults: int
    services: list[BookReservationServiceModel] | None = None
    children_ages: list[int] | None = None
    comment: str | None = None
    guest_comment: str | None = None
    primary_guest: GuestModel | None = None
    additional_guests: list[GuestModel] | None = None
    travel_purpose: TravelPurpose | None = None


@dataclass(frozen=True)
class PickUpReservationsModel:
    reservations: list[PickUpReservationModel]


@dataclass(frozen=True)
class TimeSliceModel:
    from_: str
    to: str
    service_date: str
    rate_plan: EmbeddedRatePlanModel
    unit_group: EmbeddedUnitGroupModel
    base_amount: AmountModel
    total_gross_amount: MonetaryValueModel
    unit: EmbeddedUnitModel | None = None
    included_services: list[ReservationServiceModel] | None = None
    actions: (
        list[
            ActionModelReservationTimeSliceActionNotAllowedReservationTimeSliceActionReason
        ]
        | None
    ) = None


@dataclass(frozen=True)
class TimeSliceOfferItemModel:
    unit_group: EmbeddedUnitGroupModel
    available: int
    available_units: int
    min_guarantee_type: GuaranteeType1 | None = None
    min_advance: PeriodModel | None = None
    max_advance: PeriodModel | None = None
    restrictions: RateRestrictionsModel | None = None
    prices: list[PerOccupancyPriceItemModel] | None = None


@dataclass(frozen=True)
class AddReservationsModel:
    reservations: list[CreateReservationModel]
    transaction_reference: str | None = None


@dataclass(frozen=True)
class AuthorizationListModel:
    authorizations: list[AuthorizationModel]
    count: int


@dataclass(frozen=True)
class BookingItemModel:
    id: str
    created: str
    modified: str
    group_id: str | None = None
    booker: BookerModel | None = None
    payment_account: PaymentAccountModel | None = None
    has_active_payment_account: bool | None = None
    registered_card: RegisteredCardModel | None = None
    comment: str | None = None
    booker_comment: str | None = None
    reservations: list[BookingReservationModel] | None = None


@dataclass(frozen=True)
class BookingListModel:
    bookings: list[BookingItemModel]
    count: int


@dataclass(frozen=True)
class BookingModel:
    id: str
    created: str
    modified: str
    group_id: str | None = None
    booker: BookerModel | None = None
    payment_account: PaymentAccountModel | None = None
    has_active_payment_account: bool | None = None
    registered_card: RegisteredCardModel | None = None
    comment: str | None = None
    booker_comment: str | None = None
    property_values: list[PropertyValueModel] | None = None
    reservations: list[BookingReservationModel] | None = None


@dataclass(frozen=True)
class CreateBookingModel:
    booker: BookerModel
    reservations: list[CreateReservationModel]
    payment_account: CreatePaymentAccountModel | None = None
    registered_card: RegisteredCardModel | None = None
    comment: str | None = None
    booker_comment: str | None = None
    transaction_reference: str | None = None


@dataclass(frozen=True)
class PaymentAccountV2ListModel:
    payment_accounts: list[PaymentAccountV2Model]
    count: int


@dataclass(frozen=True)
class ReservationItemModel:
    id: str
    booking_id: str
    status: Status3
    property: EmbeddedPropertyModel
    rate_plan: EmbeddedRatePlanModel
    unit_group: EmbeddedUnitGroupModel
    total_gross_amount: MonetaryValueModel
    arrival: str
    departure: str
    created: str
    modified: str
    adults: int
    channel_code: ChannelCode
    guarantee_type: GuaranteeType1
    cancellation_fee: ReservationCancellationFeeModel
    no_show_fee: ReservationNoShowFeeModel
    balance: MonetaryValueModel
    has_city_tax: bool
    is_open_for_charges: bool
    block_id: str | None = None
    group_name: str | None = None
    check_in_time: str | None = None
    check_out_time: str | None = None
    cancellation_time: str | None = None
    no_show_time: str | None = None
    unit: EmbeddedUnitModel | None = None
    market_segment: EmbeddedMarketSegmentModel | None = None
    children_ages: list[int] | None = None
    comment: str | None = None
    guest_comment: str | None = None
    external_code: str | None = None
    source: str | None = None
    primary_guest: GuestModel | None = None
    additional_guests: list[GuestModel] | None = None
    booker: BookerModel | None = None
    payment_account: PaymentAccountModel | None = None
    has_active_payment_account: bool | None = None
    registered_card: RegisteredCardModel | None = None
    travel_purpose: TravelPurpose | None = None
    assigned_units: list[ReservationAssignedUnitModel] | None = None
    time_slices: list[TimeSliceModel] | None = None
    services: list[ReservationServiceItemModel] | None = None
    validation_messages: list[ReservationValidationMessageModel] | None = None
    actions: (
        list[ActionModelReservationActionNotAllowedReservationActionReason] | None
    ) = None
    company: EmbeddedCompanyModel | None = None
    corporate_code: str | None = None
    all_folios_have_invoice: bool | None = None
    commission: CommissionModel | None = None
    promo_code: str | None = None
    is_pre_checked_in: bool | None = None
    external_references: ExternalReferencesModel | None = None


@dataclass(frozen=True)
class ReservationListModel:
    reservations: list[ReservationItemModel]
    count: int


@dataclass(frozen=True)
class ReservationModel:
    id: str
    booking_id: str
    status: Status3
    property: EmbeddedPropertyModel
    rate_plan: EmbeddedRatePlanModel
    unit_group: EmbeddedUnitGroupModel
    total_gross_amount: MonetaryValueModel
    arrival: str
    departure: str
    created: str
    modified: str
    adults: int
    channel_code: ChannelCode
    guarantee_type: GuaranteeType1
    cancellation_fee: ReservationCancellationFeeModel
    no_show_fee: ReservationNoShowFeeModel
    balance: MonetaryValueModel
    tax_details: list[TaxDetailModel]
    has_city_tax: bool
    payable_amount: PayableAmountModel
    is_open_for_charges: bool
    block_id: str | None = None
    group_name: str | None = None
    check_in_time: str | None = None
    check_out_time: str | None = None
    cancellation_time: str | None = None
    no_show_time: str | None = None
    unit: EmbeddedUnitModel | None = None
    children_ages: list[int] | None = None
    comment: str | None = None
    guest_comment: str | None = None
    external_code: str | None = None
    source: str | None = None
    primary_guest: GuestModel | None = None
    additional_guests: list[GuestModel] | None = None
    booker: BookerModel | None = None
    payment_account: PaymentAccountModel | None = None
    has_active_payment_account: bool | None = None
    registered_card: RegisteredCardModel | None = None
    time_slices: list[TimeSliceModel] | None = None
    services: list[ReservationServiceItemModel] | None = None
    travel_purpose: TravelPurpose | None = None
    assigned_units: list[ReservationAssignedUnitModel] | None = None
    validation_messages: list[ReservationValidationMessageModel] | None = None
    actions: (
        list[ActionModelReservationActionNotAllowedReservationActionReason] | None
    ) = None
    company: EmbeddedCompanyModel | None = None
    corporate_code: str | None = None
    all_folios_have_invoice: bool | None = None
    commission: CommissionModel | None = None
    promo_code: str | None = None
    is_pre_checked_in: bool | None = None
    market_segment: EmbeddedMarketSegmentModel | None = None
    external_references: ExternalReferencesModel | None = None


@dataclass(frozen=True)
class TimeSliceItemModel:
    from_: str
    to: str
    offers: list[TimeSliceOfferItemModel] | None = None


@dataclass(frozen=True)
class TimeSliceListModel:
    count: int
    time_slices: list[TimeSliceItemModel] | None = None
