# generated by datamodel-codegen:
#   filename:  identity_v1_identity.json
#   timestamp: 2026-04-01T19:50:04+00:00

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any


class Role(StrEnum):
    account_admin = "AccountAdmin"
    property_admin = "PropertyAdmin"
    accountant = "Accountant"
    revenue_manager = "RevenueManager"
    reservation_manager = "ReservationManager"
    front_desk = "FrontDesk"
    front_desk_senior = "FrontDeskSenior"
    housekeeping = "Housekeeping"
    housekeeping_manager = "HousekeepingManager"
    auditor = "Auditor"
    staff_manager = "StaffManager"


class Role1(StrEnum):
    account_admin = "AccountAdmin"
    property_admin = "PropertyAdmin"
    finance_manager = "FinanceManager"
    revenue_manager = "RevenueManager"
    reservation_office = "ReservationOffice"
    front_office = "FrontOffice"
    housekeeping = "Housekeeping"
    housekeeping_manager = "HousekeepingManager"
    auditor = "Auditor"
    staff_manager = "StaffManager"


@dataclass(frozen=True)
class CreateInvitationModel:
    email: str
    properties: list[str] | None = None
    is_account_admin: bool | None = None
    roles: list[Role] | None = None
    role: Role1 | None = None


@dataclass(frozen=True)
class InvitationAuditLogModel:
    aggregate_type: str | None = None
    account_code: str | None = None
    email: str | None = None
    properties: list[str] | None = None
    roles: list[str] | None = None
    is_account_admin: bool | None = None


@dataclass(frozen=True)
class InvitationModel:
    email: str
    is_account_admin: bool
    invited_by: str
    created: str
    properties: list[str] | None = None
    role: Role1 | None = None
    roles: list[Role] | None = None


@dataclass(frozen=True)
class InvitedUserToAccountResponseModel:
    email: str


@dataclass(frozen=True)
class MessageItemCollection:
    messages: list[str] | None = None


@dataclass(frozen=True)
class Operation:
    op: str | None = None
    value: dict[str, Any] | None = None
    path: str | None = None


@dataclass(frozen=True)
class PropertyRolesAuditLogModel:
    id: str | None = None
    roles: list[str] | None = None


@dataclass(frozen=True)
class PropertyRolesItemModel:
    id: str
    roles: list[Role]


@dataclass(frozen=True)
class RoleListModel:
    roles: list[Role]


@dataclass(frozen=True)
class UserAuditLogModel:
    first_name: str | None = None
    last_name: str | None = None
    email: str | None = None
    enabled: bool | None = None
    is_account_admin: bool | None = None
    properties_roles: list[PropertyRolesAuditLogModel] | None = None
    aggregate_type: str | None = None


@dataclass(frozen=True)
class UserItemModel:
    subject_id: str
    first_name: str
    last_name: str
    email: str
    enabled: bool
    is_account_admin: bool
    is_mfa_enabled: bool
    is_passkeys_enabled: bool
    properties: list[PropertyRolesItemModel] | None = None


@dataclass(frozen=True)
class UserModel:
    subject_id: str
    first_name: str
    last_name: str
    email: str
    is_account_admin: bool
    is_mfa_enabled: bool
    enabled: bool | None = None
    properties: list[str] | None = None
    property_roles: list[PropertyRolesItemModel] | None = None


@dataclass(frozen=True)
class UsersListModel:
    users: list[UserItemModel]
    count: int


@dataclass(frozen=True)
class InvitationListModel:
    invitations: list[InvitationModel]
